### ISSUE TITLE
Missing documentation: How to pull a docker Ubuntu e.g. 20.04 image?

### ISSUE THREAD

**Issue by soerendip** [docker-library/official-images#10000]
This might be obvious for people who are very experienced, but for newcomers, this is not obvious at all.
Most of the tutorials explain how to use the latest version of Ubuntu, but almost nowhere it is explained how to pull a specific versions. There are tags given, but the information how to use them is not.

I figured pulling and Ubuntu 20.04 version I can use 

     FROM ubuntu:focal 

in my docker file. 

Though, a quick note here https://hub.docker.com/_/ubuntu?tab=reviews&page=1&ordering=last_updated would be very welcome.
Cheers

**Comment by wglambert** [comment]
Generally the individual image documentation doesn't note the basic usage of Docker (as it could get too verbose but at the same time not verbose enough)
Docker has extensive documentation for all the commands, arguments, and directives. Such as https://docs.docker.com/engine/reference/run/#imagetag

But also we (the Official-Images team) don't maintain the `Ubuntu` image directly https://hub.docker.com/_/ubuntu
>Maintained by: [Canonical](https://partner-images.canonical.com/core/) and [Tianon (Debian Developer)](https://github.com/tianon/docker-brew-ubuntu-core)
