### ISSUE TITLE
postgres: would it be possible to enable pg_basebackup?

### ISSUE THREAD

**Issue by PeterGrace** [docker-library/official-images#1020]
I'd love to be able to use `docker exec` to initiate a `pg_basebackup` that would save a tar.gz backup in a directory on the exposed volume so that I can offsite backups from the container.

**Comment by yosifkit** [comment]
The command is in the container, so something like this should work (maybe some tweaks for using a password or a different superuser):

```console
$ docker run -it --link some-postgres:postgres --rm postgres sh -c 'exec pg_basebackup -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U postgres -D /dir/to/save/'
```

Can probably leave of the `-h` and `-p` options if using `docker exec`.

**Comment by PeterGrace** [comment]
When I tried it inside the `docker exec` there was a complaint that pg_hba didn't have a local record that would permit replication.

**Comment by yosifkit** [comment]
I made this issue over in https://github.com/docker-library/postgres/issues/88 so it can be discussed with other postgres users.
