### ISSUE TITLE
Update Alpine Docker image to 3.14

### ISSUE THREAD

**Issue by iPurpl3x** [docker-library/official-images#10289]
The version 3.14 of Alpine Linux released yesterday. 

Could someone update the [docker image](https://hub.docker.com/_/alpine/) ?

**Comment by tianon** [comment]
This is a better question for https://github.com/alpinelinux/docker-alpine. :+1:

**Comment by tianon** [comment]
(but also, I can't find any reference to 3.14 on https://alpinelinux.org/ officially yet)
