### ISSUE TITLE
Security for image build section discouraging checksums is less-secure is confusing

### ISSUE THREAD

**Issue by rugk** [docker-library/official-images#10500]
I'm talking about this second: https://github.com/docker-library/official-images#image-build

It says there:
> **Less Secure Alternate**: *embed the checksum into the `Dockerfile`.*

…and:
* it shows SHA256 hash verification
* and adds a warning that MD5 and SHA1 should not be used

## Problems

* First of all, of course what it says about MD5 and SHA1 is correct.
* However, I'd argue that there is no _security_ problem with SHA256, which is a cryptographically secure hash for that purpose.
* It may be inconvenient, because you cannot change the binary you hardcode there, but that is not what it says there. It says "Less secure", which IMHO is not true…

Even if we consider advanced attacks like downgrade/rollback attacks or so, a hash is actually IMHO never easy to manipulate as it refers to the whole binary content. And the binary you've created the hash from also comes from an authenticated source (someone you trust, ideall at least), so authenticity is "implied".
Apt-get can AFAIK be attacked via a downgrade attack, at least if the previous version of a software is not yet installed, which is of course the case in a container build environment. A hash always forces a particular version (for better [security] or worse [usability]), so this is not really a disadvantage here…

The only thing the hash does not protect in your case is the file name, which can actually be relevant if some later build step chooses that file name it _assumes_ it must be. This _could_ e.g. lead to downgrade attacks or wrong software installations (if it uses a different file to install than what we wanted). If there is another `curl` request to the same directory, this can then actually lead to a downgrade attack, because you can then switch the files and make the first curl request download a e.g. compromised or outdated binary.
**However** your preferred method with `gpg --batch --verify` potentially would have the same issue, as it also could be used to download a file and then verify some files (potentially made worse with wildcards like `*`).
Yet again, the code you actually use there as examples looks secure, because it does always specify the _output file name_ for `curl` downloads. – Yet, this is not a thing you actually explicitly recommend.

For more things to consider, let's learn from the awesome TUF project: https://theupdateframework.io/security/

## Proposed solution

* Explain that the checksum-way is inconvenient and rather not argue that it is somewhat less secure.
* Possibly explain how to properly verify the checksum, if that is used, i.e. make sure to have and stay in control over the file name (for the reasons explained above)

**Comment by rugk** [comment]
Also why does it use a star/wildcard here `*`?

> echo "$PYTHON_DOWNLOAD_SHA512 *python.tar.xz" | sha512sum --strict --check;

I'm not sure whether that is a security advantage or disadvantage, it just is not explained anywhere and the usual syntax of sha512sum is of course not that problem…

**Comment by rugk** [comment]
And here, the duplicate usage of `-c` and `--check` in the same command (they are alias'es according to the man page), is wrong, is not it?

```shell
echo "$RUBY_DOWNLOAD_SHA256 *ruby.tar.gz" | sha256sum -c --strict --check;
```

**Comment by tianon** [comment]
"Less" there is in the context of the "Preferred" solution which is _both_ checksum **and** some kind of signature verification (with OpenPGP/GnuPG being the simplest and definitely most commonly used solution).  "Secure" was perhaps the wrong word choice, and we'd be very open to alternative suggestions.

As for the `*`, see https://manpages.debian.org/sha256sum:

> When checking, the input should be a former output of this program. The default mode is to print a line with checksum, a space, a character indicating input mode ('*' for binary, ' ' for text or where binary is insignificant), and name for each FILE.

On `-c` + `--check`, great catch, thanks!  I'll fix that in a jiffy.
