### ISSUE TITLE
Explicitly disallow the use of "alpine-pkg-glibc"

### ISSUE THREAD

**Issue by tianon** [docker-library/official-images#10794]
This is definitely a piece of #6282, but in light of https://ariadne.space/2021/08/26/there-is-no-such-thing-as-a-glibc-based-alpine-image/ (and https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/24647), we plan to enforce the no-glibc-in-Alpine-based-images (and even not mixing release pockets like 3.14 and edge) more strictly.

Fortunately, there are only two images which are currently using this:

- `sonarqube`: @christophelevis @pierre-guillot-sonarsource @tobias-trabelsi-sonarsource @lukasz-jarocki-sonarsource
- `ibmjava`: @jayasg12

Please make (short term) plans to either migrate off this solution or deprecate the affected image variants.

(See also https://github.com/docker-library/official-images/pull/10779#issuecomment-906240756 for an example of a concrete issue with the usage of this in the context of Java.)

**Comment by J0WI** [comment]
Question (maybe to @kaniini?): does this affect any image using the `libc6-compat` package or is this still an acceptable workaround?

**Comment by kaniini** [comment]
`libc6-compat` has largely been superseded by gcompat and needs to be retired, especially since musl no longer supports that hack

**Comment by jayasg12** [comment]
Hi @tianon Is there a way to get stats of download for ibmjava Alpine images , so it helps us to take next step of action. Thanks !!

**Comment by tianon** [comment]
Closing this now as anything left is really part of https://github.com/docker-library/official-images/issues/6282. :+1:
