### ISSUE TITLE
Bashbrew does not work

### ISSUE THREAD

**Issue by ikbear** [docker-library/official-images#1083]
```
➜  bashbrew git:(master) ./bashbrew.sh
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

This is the output when executing this bashbrew script, there are no helps. And `build` command does not work too:

```
➜  bashbrew git:(master) ./bashbrew.sh build
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

**Comment by md5** [comment]
`bashbrew.sh` and pretty much every other script in this repo will only work in a GNU shell environment. It looks like you're running under OS X or another BSD-based environment.

I've played around in the past with trying to get them to run directly under the OS X shell by doing something like this:

```console
$ brew install coreutils gnu-sed gnu-tar
$ exec env PATH="$(find /usr/local/opt -follow -name gnubin | tr $'\n' ':')$PATH" $(brew --prefix bash)/bin/bash
```

It ends up working pretty well until I run into some other GNU utility that's not in my `PATH` by default.

I generally just end up running these things under a Docker container though, which has its own warts. I'd be curious if anyone's come out with a nice way to use the scripts in this repo and other Official Image scripts under OS X.

**Comment by yosifkit** [comment]
Closing because bashbrew works in a GNU/Linux environment.  If you would like to discuss portability to non-GNU environments like MacOSX, feel free to open an issue.
