### ISSUE TITLE
Simplify

### ISSUE THREAD

**Issue by yosifkit** [docker-library/official-images#1085]
As [pointed out](https://microblog.pierre-o.fr/2015/docker-hub-and-official-images-are-complicated) by @pierreozoux in https://github.com/docker-library/owncloud/pull/28#issuecomment-144043634, the process and management of Official Images is complicated.

This issue is for us to discuss possible solutions to simplify the process and/or the code involved with concrete ideas becoming proposal issues and pull requests.  We can also discuss the reasoning for the current architecture decisions in the hope that we can learn from the past and create something better.

**Comment by pierreozoux** [comment]
Can we have a codestyle for `Dockerfile`? My dream :) I can make a proposal if you want?

I like this kind: https://github.com/indiehosters/wordpress/blob/master/Dockerfile

**Comment by Moghedrin** [comment]
In terms of *"solutions to simplify the process and/or the code involved""*, I feel like mandating a coding style is silly. There's no reason we should enforce, for example, spacing in a Dockerfile as long as it follows best practices. The maintainer should be able to use whatever style the feel most comfortable with. There's no reason we should arbitrate an arbitrary style.

**Comment by pierreozoux** [comment]
@Moghedrin of course not for an external maintainer, but for the `Dockerfile` [maintained by docker](https://github.com/docker-library).

**Comment by Moghedrin** [comment]
Most, if not all, of the official images maintained by us already follow a set coding style. Are you recommending that we change that coding style to something preferred by you?

**Comment by pierreozoux** [comment]
@Moghedrin no :) Just having a clear codestyle :) I would have love to have a clear codestyle when I started to write my first Dockerfile, that's all.
All companies have codestyle, and I think it is cool.

But you know, just ignore my comment about the codestyle. I was just a bit overexcited maybe. And we are not discussing about the heart of the problem, just bike shedding.
