### ISSUE TITLE
(ruby) Recommended way to run `bundle outdated` and `bundle update`

### ISSUE THREAD

**Issue by odigity** [docker-library/official-images#1098]
I'm using the ruby:2.2-onbuild container for my app which sets BUNDLE_FROZEN to 1.

Based on the suggestion in the docs, I'm running one-off ruby:2.2 containers to run the `bundle install` command whenever I change my Gemfile in order to update Gemfile.lock, then rebuilding my app container.  That's fine.

But now there's a new version of a gem (sequel) I want to upgrade to.  So, I want to be able to run `bundle outdated` to notice that, and then `bundle update sequel` to update my Gemfile.lock to the latest version of it.

However, I can't run the commands in my app container where I spend most of my time because the FROZEN setting makes bundler not even bother checking rubygems for new versions (why bother when it's illegal to install something new in a FROZEN state).  Nor can I run it as a one-off like I do with `bundle install` because the `bundle outdated` command fails if you haven't first installed the gems in your Gemfile.lock, and the ruby:2.2 container starts without your gems installed.

I suppose I can run a compound command of `bundle install && bundle outdated` (to notice new versions), followed by `bundle install && bundle update sequel`, but that complicates my helper scripts and consumes even more time installing gems in temporary one-command containers.

Would appreciate some guidance as to the best approach to this task.  Would probably also be useful to mention in the docs so others will benefit.  (I'd be willing to submit a PR for that if that's desired.)

**Comment by yosifkit** [comment]
We have been thinking of the possibility of dropping the `BUNDLE_FROZEN`, but the easier solution might just be to copy the dockerfile commands from the `onbuild` [Dockerfile](https://github.com/docker-library/ruby/blob/5d04363db6f7ae316ef7056063f020557db828e1/2.2/onbuild/Dockerfile) to your Dockerfile and no longer inherit from the onbuild image.   Be sure to drop the `ONBUILD` from each line.

**Comment by odigity** [comment]
I've considered doing that.  I already have once, when working on a rack middleware gem, because the ONBUIILD version copies the Gemfiles but not the .gemspec, so the bundle install wasn't able to do it's job.

But I'm hesitated so far because the FROZEN thing seemed like a good practice for a container destined for production.

Of course, that's the problem -- using the same container for development.  :)
