### ISSUE TITLE
The CI for amd64 seems to have a problem

### ISSUE THREAD

**Issue by ldez** [docker-library/official-images#11023]
It seems like your CI have an issue with the amd4:

- https://doi-janky.infosiftr.net/job/multiarch/view/images/view/traefik/job/amd64/job/traefik/
- https://doi-janky.infosiftr.net/job/multiarch/view/images/view/friendica/job/amd64/job/friendica/
- https://doi-janky.infosiftr.net/job/multiarch/view/images/view/influxdb/job/amd64/job/influxdb/
- https://doi-janky.infosiftr.net/job/multiarch/view/images/view/clearlinux/job/amd64/job/clearlinux/
- https://doi-janky.infosiftr.net/job/multiarch/view/images/view/docker/job/amd64/job/docker/
- https://doi-janky.infosiftr.net/job/multiarch/view/images/view/rocket.chat/job/amd64/job/rocket.chat/

**Comment by benlangfeld** [comment]
```
java.nio.file.FileSystemException: /mnt/docker/jenkins/doi-janky/amd64/workspace/multiarch/amd64/docker: No space left on device
```

It seems someone just let a disk fill up.
