### ISSUE TITLE
rails bootstrap new app with default command fails

### ISSUE THREAD

**Issue by pshoukry** [docker-library/official-images#1104]
```
docker run -it --rm --user "$(id -u):$(id -g)" -v "$PWD":/usr/src/app -w /usr/src/app rails rails new webapp
```

fails with error
```
Errno::ENOENT: No such file or directory @ rb_sysopen - /.gem/ruby/2.2.0/cache/json-1.8.3.gem
```

**Comment by pshoukry** [comment]
Appears to be a permission problem since removing --user "$(id -u):$(id -g)" and running as root makes bundler complete installing.

**Comment by pshoukry** [comment]
A working workaround

1- ```
docker run -it  -v "$PWD":/usr/src/app -w /usr/src/app rails gem install minitest -v '5.8.1'
```
2- Commit the container
3- ```
docker run -it --rm --user "$(id -u):$(id -g)" -v "$PWD":/usr/src/app -w /usr/src/app rails rails new webapp
```

**Comment by yosifkit** [comment]
Looks like we just need to skip the `bundle install` since this is a throw away container anyway.  Updated the docs: https://github.com/docker-library/docs/pull/362.

**Comment by pshoukry** [comment]
If you skip bundle install, adding gems or running bundle install as normal user still fails ( must be root ) when you try bundle install as root you get a message that rails will fail for all non root users from now on.
