### ISSUE TITLE
vault 1.9 amd64 image is missing

### ISSUE THREAD

**Issue by sfc-gh-jelsesiy** [docker-library/official-images#11336]
For some reason the Vault 1.9 tag is incomplete missing the `amd64` arch.
See https://hub.docker.com/_/vault?tab=tags

<img width="685" alt="Screen Shot 2021-11-18 at 9 49 14 AM" src="https://user-images.githubusercontent.com/64176666/142469686-c2dd86c4-0374-4100-a18c-dcf675c59fb3.png">

**Comment by yosifkit** [comment]
The official images build queue is unfortunately still very full from the backlog of https://github.com/docker-library/official-images/pull/11308, which is the reason this tag isn't built for `linux/amd64` just yet.

**Comment by sfc-gh-jelsesiy** [comment]
Is the queue publicly available or do I have to wait & periodically check? Thanks!

**Comment by yosifkit** [comment]
It's public:  https://doi-janky.infosiftr.net/

**Comment by sfc-gh-jelsesiy** [comment]
@yosifkit Looks like a few jobs are hanging due to a jenkins restart and cannot be resumed e.g. https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/vault/187/console. Does it make sense to cancel and re-queue this one?

**Comment by tianon** [comment]
The job you linked to is finished (the resulting images can currently be
found under https://hub.docker.com/r/amd64/vault/tags); it also has
appropriately triggered
https://doi-janky.infosiftr.net/job/put-shared/job/light/job/vault/ which
should run very soon (and will update the manifest lists under the
"library" namespace to include "amd64").

**Comment by tianon** [comment]
Manifest lists are now up: https://hub.docker.com/_/vault?tab=tags
