### ISSUE TITLE
'apt update'  doesn't work on raspberrypi3 and raspberry-pi2

### ISSUE THREAD

**Issue by antmak** [docker-library/official-images#11447]
I tried to use balenalib/rpi-raspbian:buster , balenalib/raspberry-pi2:buster , balenalib/raspberrypi3:buster. The first one works fine, but the latter two don't work. I can't complete `apt update` command. My hosts are on several places (Europe and Asia).

Could you help me with it, please?

```
# on amd64 host
$ docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
$ docker run --rm -it balenalib/raspberrypi3:buster bash
...
apt update
<geting stuck here>
```

**Comment by antmak** [comment]
probably it's not related place for the question, I posted on the forum https://forums.balena.io/t/apt-update-doesnt-work-on-raspberrypi3-and-raspberry-pi2-11447/350402

**Comment by tianon** [comment]
I think that forum is probably the right place to ask for help with this issue -- this doesn't have anything to do with the project of this GitHub repository. :sweat_smile:
