### ISSUE TITLE
File not found on execute or rename.

### ISSUE THREAD

**Issue by rvm2015** [docker-library/official-images#1146]
Busybox is returning a file not found error when trying to either execute or rename my executable. Happens with both latest and ubuntu varients with the following docker file:

    FROM busybox

    COPY ./httpenv /httpenv
    RUN chmod +x /httpenv

    CMD /httpenv
    EXPOSE 8080

Running docker logs containerid shows the file not found error. Shelling into the container shows the following:

    / # ls -la
    total 7072
    drwxr-xr-x   12 root     root          4096 Oct 26 19:56 .
    drwxr-xr-x   12 root     root          4096 Oct 26 19:56 ..
    -rwxr-xr-x    1 root     root             0 Oct 26 19:56 .dockerenv
    -rwxr-xr-x    1 root     root             0 Oct 26 19:56 .dockerinit
    drwxr-xr-x    2 root     root         12288 Oct 19 18:03 bin
    drwxr-xr-x    5 root     root           380 Oct 26 19:56 dev
    drwxr-xr-x    2 root     root          4096 Oct 26 19:56 etc
    drwxr-xr-x    3 root     root          4096 Oct 19 18:03 home
    -rwxr-xr-x    1 root     root       7194704 Oct 26 18:55 httpenv
    dr-xr-xr-x  152 root     root             0 Oct 26 19:56 proc
    drwxr-xr-x    2 root     root          4096 Oct 26 19:56 root
    dr-xr-xr-x   13 root     root             0 Oct 26 19:56 sys
    drwxrwxrwt    2 root     root          4096 Oct 19 18:03 tmp
    drwxr-xr-x    3 root     root          4096 Oct 19 18:03 usr
    drwxr-xr-x    4 root     root          4096 Oct 19 18:03 var
    / # ls /httpenv
    /httpenv
    / # /httpenv
    sh: /httpenv: not found

Same problem happens if I try to move httpenv.

**Comment by tianon** [comment]
This would be better filed under https://github.com/docker-library/busybox.
:wink:

On your host, can you run "ldd httpenv" ?  My guess is that "httpenv" is
dynamically linked to some libraries on your host which don't exist inside
the "busybox" image (hence the cryptic "not found" error message which is
referring to the libraries "httpenv" is trying to load, not the "httpenv"
executable itself).

**Comment by rvm2015** [comment]
ldd: warning: you do not have execution permission for `./httpenv'
	linux-vdso.so.1 =>  (0x00007ffcd5473000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f1017ff3000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f1017c32000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1018219000)

What would be causing mv to also not be able to do anything with the file?
