### ISSUE TITLE
Is the CentOS image still maintained?

### ISSUE THREAD

**Issue by raesene** [docker-library/official-images#11679]
Looking at the CentOS images on Docker Hub at the moment, it looks like they've not had patched applied in 4 months, and this results in them having a number of [unfixed security issues](https://try.trivy.dev/results/zmX7RaQQ2Y5CgREKhLwkbxyE).

Is this image still maintained? I was just thinking that (especially as centos is a pretty heavily used base image) , if it's not, it might be worth indicating that it's unmaintained on Docker hub (like the other unmaintained official images).

**Comment by tianon** [comment]
Yeah, it has been a bit since the last update :disappointed: :grimacing: 

@bstinsonmhk any plan to do an update soon? :pray:

**Comment by jamshid** [comment]
This is weird I assumed centos:8 would just become a continuously updated (stream?) image. But nope, it's pretty useless now:
```
% docker run -ti centos:8 bash      
[root@5dcdae78e366 /]# yum update
Failed to set locale, defaulting to C.UTF-8
CentOS Linux 8 - AppStream                                                                                                        128  B/s |  38  B     00:00    
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```
Is centos:8 really dead, RedHat is making everyone switch to stream8?
```
% docker run -ti quay.io/centos/centos:stream8 bash
[root@821b3f36fa02 /]# cat /etc/centos-release 
CentOS Stream release 8
[root@821b3f36fa02 /]# yum update
...hundreds of package need updating what kind of a stream is this?...
Complete!
```

**Comment by tianon** [comment]
Ouch, I guess https://www.centos.org/centos-linux-eol/ means we should probably add a deprecation notice to Docker Hub?  cc @bstinsonmhk :pray: :bow:

**Comment by yeroc** [comment]
The centos7 image has now been unpatched for 7 months.  I thought there was some expectation that images with the "Docker Official Image" label would be kept up to date?  Am I out to lunch here?

**Comment by tianon** [comment]
Yeah, thanks for the reminder - I've opened https://github.com/docker-library/docs/pull/2205 now :disappointed:

**Comment by yeroc** [comment]
Thanks.  Will there be a deprecation notice put on Docker Hub as well? 

The strange thing here is that CentOS 7 isn't actually EOL...

**Comment by tianon** [comment]
Yes, that repository is the "source of truth" for the image descriptions on Docker Hub, so that deprecation notice will feature prominently on the top of the page after the PR is merged.

I agree WRT CentOS 7 - I'd love to see an update to the image and drop my PR (or revert it, as the case/timing may be), but there's only so much _I_ can do. :disappointed:
