### ISSUE TITLE
Question on base images

### ISSUE THREAD

**Issue by sarahethompson** [docker-library/official-images#11705]
Hi
HashiCorp Release Engineering here.
We had a question on some changes that we are hoping to make to the dockerfiles for our official images (Consul and Vault).

Is it possible for us to derive our official images from the images that we push to [hashicorp/consul](https://hub.docker.com/r/hashicorp/consul) [hashicorp/vault](https://hub.docker.com/r/hashicorp/vault)?

e.g
`FROM hashicorp/vault:4.3.2`

Due to the way we currently build our docker images, this would help significantly and avoid us having to maintain two separate dockerfiles for each product.

I notice that [here](https://github.com/docker-library/official-images#repeatability) it states that official images can only be derived from other official images with a few notable exceptions. However I see elasticsearch are doing what we would like to do and rebundling images that they maintain (https://github.com/docker-library/elasticsearch/blob/master/7/Dockerfile).

```
# This image re-bundles the Docker image from the upstream provider, Elastic.
FROM docker.elastic.co/elasticsearch/elasticsearch:7.16.3@sha256:0efc3a054ae97ad00cccc33b9ef79ec022970b2a9949893db4ef199edcdca2ce
```

Thanks for any clarity you can give us

**Comment by tianon** [comment]
Unfortunately, `elasticsearch` (and `logstash` + `kibana`) was a one-time exception and honestly hasn't gone well, so that model is not one we'll be likely to accept again.

**Comment by tianon** [comment]
As an alternative, can we help maintain the `Dockerfile`s in some way?

**Comment by yosifkit** [comment]
It's not a hard requirement for the Dockerfiles to be in a separate repo, but a quick warning about putting the Dockerfile in the root of the upstream repo: https://github.com/docker-library/official-images/pull/11100#issuecomment-1023481834.  As noted in that comment, there are a few issues that could crop up: `Dockerfile` and other "packaging" changes between upstream releases and the need for extreme care about `docker build` context (`COPY` targets) and how that might affect the generated diffs (`diff-pr.sh`).

**Comment by sarahethompson** [comment]
Thanks @yosifkit. We are only doing a `COPY .release/docker/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh` in the [new default target](https://github.com/hashicorp/vault/blob/0407ac0527c470be04ee12f31ae5de5ea0e460b3/Dockerfile#L143) so this should be ok. I take your point about potentially having to make changes to the dockerfile between releases of the software itself. We have really only ever [modified the version number](https://github.com/hashicorp/docker-vault/commits/master/0.X/Dockerfile) in the dockerfile in the last number of years (and twice updated the PGP key - although we could add a additional step to our build workflow to run a `bashbrew build` to verify things like this).

We're building all of our release artifacts on every commit now from the product repo (including the docker image that we push to hashicorp/vault) so we're trying to avoid having to maintain an almost identical dockerfile (and identical entrypoint.sh) in a separate repo (for the official image). A product engineer could make an update to the dockerfile or entrypoint.sh in the product repo but forget to do it in the [docker-vault](https://github.com/hashicorp/docker-vault) repo for example.

We could have automation to try to keep them in sync but this would introduce overhead and complexity that we're trying to avoid if possible.

**Comment by yosifkit** [comment]
Unfortunately, since we don't have any configuration points to just build a single target within a multistage build, I think that Dockerfile would fail to build for us (since our process would attempt to build the first stage and fail to `COPY` the file). We can handle a custom Dockerfile name, so two Dockerfiles in the one directory with one named `Dockerfile.official` or something can work (like [mysql](https://github.com/docker-library/official-images/blob/77ab6cb740a16028eaf46c10f839c9ddb44cc6dd/library/mysql#L11)).

**Comment by yosifkit** [comment]
The information above is still correct and answers the questions about being `FROM` an image outside of Docker Official Images and about hosting the Dockerfile in the upstream code repo.

Given the transition to deprecate the Hashicorp images in DOI, I'll go ahead and close this issue. (https://github.com/docker-library/docs/pull/2283, https://github.com/docker-library/docs/pull/2291)
