### ISSUE TITLE
amd64 arch tags missing for traefik

### ISSUE THREAD

**Issue by q0rban** [docker-library/official-images#11714]
I'm unable to pull some traefik tags for amd64:

```
$ docker pull traefik:v2.5.7
v2.5.7: Pulling from library/traefik
no matching manifest for linux/amd64 in the manifest list entries
```

Note that on [Docker Hub](https://hub.docker.com/_/traefik?tab=tags) certain architectures are missing:

![traefik Tags | Docker Hub 2022-01-20 16-35-06](https://user-images.githubusercontent.com/66118/150425878-5d59e2fe-d6fc-4740-bd3f-df43335f2701.png)

Not sure if it is related, but I noticed [this Jenkins job](https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/traefik/) seems stuck with `Waiting for next available executor on ‘multiarch-amd64’`:

![traefik  multiarch » amd64   Jenkins  2022-01-20 16-32-39](https://user-images.githubusercontent.com/66118/150425547-28e4024f-ee15-4d65-a3a0-79ecdf0fe591.png)

**Comment by yosifkit** [comment]
Fortunately, it is not stuck. There were just other images still being built so it is in a queue (and some take a while, like `php`).

**Comment by q0rban** [comment]
Wonderful, thank you!
