### ISSUE TITLE
Elixir Language Image

### ISSUE THREAD

**Issue by vovimayhem** [docker-library/official-images#1171]
Hi! I'm opening this issue to start up a discussion about having an official [Elixir](http://elixir-lang.org) Docker image.

I'm basically an Elixir/Erlang/OTP newbie, so I don't know about the common use cases found by the Elixir community in regards of how much of Erlang/OTP and other dependencies are required by Elixir to work properly during the development/deployment lifecycle. I'm taking a look at the dependencies listed on the `elixir` apt package.

I think the project should:
 - Leverage the existing docker official libraries (buildpack-deps, etc) by starting off from an official Erlang/OTP image (which is also being discussed at #1075) 
 - Release an image that supports a smooth development flow.
 - Release a 'slim' image that serves as a base for a production-ish deployment.
 - Both releases should be ideal to work with Docker-Compose flows.
 - Focus on not including any bloat, but stay away from aggressively small image sizes, as we're leveraging existing docker images.
 - Support the latest, active, or current versions of Elixir.
 - Use only the Erlang/OTP version suggested for the maintained versions of Elixir.

I've seen some similar projects focusing on smaller image sizes, but IMHO that's no real gain, as you'll end up using other official/non-official docker images for other services (postgres, rabbitmq, etc) and you'll not benefit from this.

**Comment by vovimayhem** [comment]
I don't foresee a cool use for an `onbuild` version, but I guess it wouldn't cause harm to have one...

**Comment by vovimayhem** [comment]
This is my analysis of the most-popular, currently available elixir images on the hub:

* [trenpixster/elixir](https://hub.docker.com/r/trenpixster/elixir/) by @trenpixster (41 stars, 8.7k pulls, [See Dockerfile](https://github.com/trenpixster/elixir-dockerfile/blob/master/Dockerfile)): 
  - Seems to be actively maintained: The last push was 23 days ago, using Elixir v1.1.1 Erlang OTP 18.1
  - It is based on [phusion/baseimage](https://github.com/phusion/baseimage-docker/blob/master/image/Dockerfile), which is based on an [Official Ubuntu 14.04 Image](https://hub.docker.com/_/ubuntu/) - already bloated -, adding more complexity/bloat to make it more ['Docker-friendly'](https://github.com/phusion/baseimage-docker#why-use-baseimage-docker). The [Official Debian Image](https://hub.docker.com/_/debian/) seems to be friendly enough, so much in fact that is used for some official images. That added complexity permeates back to @trenpixster 's [Dockerfile](https://github.com/trenpixster/elixir-dockerfile/blob/master/Dockerfile), which would otherwise be simpler.
  - It's not based on an available Erlang/OTP docker image, but rather installed in the same [Dockerfile](https://github.com/trenpixster/elixir-dockerfile/blob/master/Dockerfile#L64).
  - In terms of [build security](https://github.com/docker-library/official-images#security), It's got a 'good' security download, but could be better.
  - I'd prefer the binaries placed at `/usr/local/bin` which is already in `$PATH`, rather than in `/elixir/bin`.
  - It installs `hex` (a package manager akin to Ruby's `gem` command) and `rebar` (akin to Ruby's `rake` command?), and *this is cool*. Ruby official image bundles `bundler` to the same effect. We should consider which additional package managers and tools are used on day-by-day basis by Elixir developers & users.

* [marcelocg/phoenix](https://hub.docker.com/r/marcelocg/phoenix/) by @marcelocg (11 stars, 938 pulls, [See Dockerfile](https://github.com/marcelocg/phoenix-docker/blob/master/Dockerfile)):
  - The last push was 2 months ago... looks sort-of maintained.
  - Based on the latest [Official Ubuntu Image](https://hub.docker.com/_/ubuntu/). I feel Ubuntu by itself is already bloated, so much I don't use it for Docker images at all.
  - Installs Erlang, Elixir and Phoenix in the same image. We'd rather split this into discrete Images, and base each from the previous one.
  - The [Erlang install command](https://github.com/marcelocg/phoenix-docker/blob/master/Dockerfile#L15) is not [secure](https://github.com/docker-library/official-images#security).
  - It installs nodejs, which seems to be a dependency for a particular project, so it's not the best fit for an official Elixir/Phoenix image.

* [nifty/elixir](https://hub.docker.com/r/nifty/elixir/) by @niftyn8 (8 stars, 565 pulls, [See Dockerfile](https://github.com/niftyn8/docker-elixir/blob/master/Dockerfile)):
  - Looks very outdated, the last push was a year ago, while the last commit was 11 months ago.
  - Based on this Erlang Docker Image: [nitfy/erlang](https://hub.docker.com/r/nifty/erlang/) ([See Dockerfile](https://github.com/niftyn8/docker-erlang/blob/master/Dockerfile)), but this one is also based on an [Official Ubuntu Image](https://hub.docker.com/_/ubuntu/) (Trusty). I'd prefer be spared from bloat using the [Official Debian Image](https://hub.docker.com/_/debian/).
  - Uses the official debian packages for Erlang and Elixir via apt, but the [build security](https://github.com/docker-library/official-images#security) could be improved.
  - Somewhat simple [Dockerfile](https://github.com/niftyn8/docker-elixir/blob/master/Dockerfile) ([and this](https://github.com/niftyn8/docker-erlang/blob/master/Dockerfile)) :) Using the official debian packages is desirable.

* [msaraiva/elixir](https://hub.docker.com/r/msaraiva/elixir/) by @msaraiva (5 stars, 381 pulls, [See github repo](https://github.com/msaraiva/docker-alpine)):
  - Looks somewhat outdated, the last commit was 2 months ago.
  - The attention to image size is admirable, using images based on [Alpine Linux](https://hub.docker.com/_/alpine/)... but the project is so split up into many dependent images that I feel his efforts are diluted by maintaining all those images.

**Comment by msaraiva** [comment]
> ...the project is so split up into many dependent images that I feel his efforts are diluted by maintaining all those images.

You're absolutely right! What a coincidence. Yesterday I opened this issue: 
<https://github.com/msaraiva/alpine-erlang/issues/2>

After this, I'll be able to keep the images always up to date. 

Anyway, I think it's better if use an image from the ubuntu/debian family. They are huge, but that's what most people are familiar with. Feel free to contact me or ping me on [twitter](https://twitter.com/MarlusSaraiva) if you need any help.

Cheers!
-marlus

**Comment by vovimayhem** [comment]
Cool @msaraiva! In the end we all win if we can focus our efforts on the correct places :)

**Comment by c0b** [comment]
the `https://github.com/c0b/docker-erlang-otp/blob/master/elixir/Dockerfile` is my initial implementation and sure it can be in a separate repo. As #1075 will be the dependency, and it's pending over a month, any one know how to push it to be merged? any maintainer of official-images can talk about acceptance criteria?

**Comment by vovimayhem** [comment]
For the time being, we'll refer to https://github.com/c0b/docker-erlang-otp until we figure it out :)

**Comment by ivan-kolmychek** [comment]
That would be really nice to have an official `elixir` lang image.

I found https://github.com/voidlock/docker-elixir to be a nice image based on Debian.

**Comment by ivan-kolmychek** [comment]
I think we should file a separate issue for image with `phoenix` framework - like we have `ruby` and `rails` as two separate images (even if later is based on former).

**Comment by vovimayhem** [comment]
@ivan-kolmychek I'm also on the same page :)
