### ISSUE TITLE
Question about Image with arm64v8 architecture

### ISSUE THREAD

**Issue by kaissun** [docker-library/official-images#11880]
Hello team, 

I have changed the architecture of my fargate task for my application (serverless container in AWS) to ARM architecture. 
So I need to retrieve the Arm image of amazoncorretto. Actually I am using the default one: ```FROM amazoncorretto:11```
I would like to know if this image is defined as multi-architecture image (Arm and x86 ) i.e. it works for all platforms. Or I have to use this specific image ```arm64v8/amazoncorretto:11```

Thanks in advance.

**Comment by wglambert** [comment]
Both would work. The first is a "shared" tag and the latter a "simple" one
https://github.com/docker-library/faq#whats-the-difference-between-shared-and-simple-tags
