### ISSUE TITLE
pypy 7.3.8 tags

### ISSUE THREAD

**Issue by olliemath** [docker-library/official-images#11901]
Hello, I noticed that you've already built the 7.3.8 images upstream https://github.com/docker-library/pypy

Any idea when you'll be updating the images here?

I tried replicating the instructions here https://github.com/docker-library/official-images/issues/1589 to create a PR, but the mentioned script doesn't seem to exist any more

**Comment by olliemath** [comment]
Oh, I found the script in the upstream repo - PR opened

**Comment by tianon** [comment]
Closing in favor of tracking this via https://github.com/docker-library/official-images/pull/11902 and/or https://github.com/docker-library/official-images/pull/11903.
