### ISSUE TITLE
Update jenkins "full description"

### ISSUE THREAD

**Issue by carlossg** [docker-library/official-images#1197]
Seems there's a disconnection between the "full description" in the hub and the https://github.com/jenkinsci/docker/blob/master/README.md 
how can we get the description updated to match the README ?

https://github.com/jenkinsci/docker/issues/168

**Comment by tianon** [comment]
I think it's mentioned in the Hub description somewhere, but docs for the
official images are maintained in https://github.com/docker-library/docs,
so a PR over there would be great! :+1:

**Comment by carlossg** [comment]
got it, opened https://github.com/docker-library/docs/pull/399
