### ISSUE TITLE
Docker PUSH/PULL with HTTPS

### ISSUE THREAD

**Issue by postalC** [docker-library/official-images#1212]
Hi team,

## NUTSHELL
Pull and run the latest docker registry 2.2, technically everything work fine, but not able to make it work the same with HTTPS only.

## BACKGROUND
For security reason, I run a nginx in-front of the docker registry with SSL and Basic Auth. So, the idea is only the request with auth successfully would redirect to the actual registry port.

## ISSUE
With that setting, I am able to do docker login and list the docker repo via the registry API. 

But failed to do docker PULL or PUSH, it encountered HTTP ERROR 503.  After few trouble-shoot, notice that the docker PUSH is calling HTTP PATCH at HTTP default port 80.

As work-around, i forced to open-up HTTP port 80 as well to able to do docker PUSH/PULL.

Is this correct behavior? because it seem to be a security threat to allowing HTTP port 80 on registry.

Please let me know if something could be configure to avoid this? Thanks

regards,
CHAI

**Comment by tianon** [comment]
This would probably be more appropriate as an issue over on https://github.com/docker/distribution so that the maintainers of that image see it. :smile: :+1:

**Comment by postalC** [comment]
Created an issue in docker distribution as suggested by tianon - https://github.com/docker/distribution/issues/1209

**Comment by stevvooe** [comment]
@tianon Close this out please. This is support issue to be handled in docker/distribution.

**Comment by tianon** [comment]
:+1:
