### ISSUE TITLE
Official AlmaLinux images - Add additional category and missing DCT

### ISSUE THREAD

**Issue by srbala** [docker-library/official-images#12132]
Team,

* We would like to add two categories `Base Images` and `Operating Systems` to AlmaLinux images.
* Our images are missing Docker content trust (DCT). When inspecting docker image trust returns `No signatures` message on following `almalinux` image tags `almalinux:minimal`, `almalinux:8-minimal`, `almalinux:8.5`, `almalinux:8.5-20220306` and `almalinux:8.5-minimal-20220306`. 
* Only `almalinux:latest` image returns proper signature.

$ docker trust inspect --pretty almalinux:latest
```
Signatures for almalinux:latest

SIGNED TAG   DIGEST                                                             SIGNERS
latest       a21996e1faa92e26a48c7fe3ae5652efc4b0eacb4ead710f0cca9167251dd27e   (Repo Admin)

Administrative keys for almalinux:latest

  Repository Key:       6d877ea8650b9ae02b6c34fad11ab0c593e55840a15558e883eac013ede69be4
  Root Key:     0cbdf8fcba9ff932fff1d8a11d53937fb56d4754c16787941176582f8f75f5ce
```
$ docker trust inspect --pretty almalinux:8
```
No signatures for almalinux:8


Administrative keys for almalinux:8

  Repository Key:       6d877ea8650b9ae02b6c34fad11ab0c593e55840a15558e883eac013ede69be4
  Root Key:     0cbdf8fcba9ff932fff1d8a11d53937fb56d4754c16787941176582f8f75f5ce
```

Please help to enable us to trust the signature on these tags.

**Comment by srbala** [comment]
@tianon, @yosifkit Our image DCT is related to a few outstanding issues. https://github.com/docker-library/official-images/issues?q=is%3Aissue+dct+
Backlink to #6838 seems to contain more discussions

Any suggestions to update the category of images?

**Comment by tianon** [comment]
Unfortunately, we don't have direct control over the listed categories (https://github.com/docker/roadmap/issues/76 :sweat_smile:), but I'll ask some folks on the Hub team. :+1:

**Comment by srbala** [comment]
@tianon Thank you, our community appreciates you and your team support

**Comment by yosifkit** [comment]
It looks like the categories feature has been removed from Docker Hub.

Still talking with Docker Hub folks about the missing signature for `almalinux:8`.

**Comment by tianon** [comment]
I think this is fixed now! :smile:
