### ISSUE TITLE
[varnish] missing tags

### ISSUE THREAD

**Issue by gquintard** [docker-library/official-images#12141]
looking at https://github.com/docker-library/official-images/blob/ac2c4bc9035aca25f144552659f814cfd60870b7/library/varnish#L10 , it seems there should be a `7.1.0` image for `arm64v8` (there's a `7.1` one) , but it doesn't appear to be on the hub: https://hub.docker.com/_/varnish?tab=tags&page=1&name=7.1

(reported by [kforsthoevel](https://github.com/kforsthoevel) on https://github.com/varnish/docker-varnish/issues/50)

**Comment by yosifkit** [comment]
It looks like both the Debian and Alpine versions are failing some of the `check-TESTS` of vmod-dynamic:

(https://doi-janky.infosiftr.net/job/multiarch/view/images/view/varnish/job/arm64v8/job/varnish/33/consoleFull)
```console
make  check-TESTS
make[2]: Entering directory '/work/vmod-dynamic/src'
make[3]: Entering directory '/work/vmod-dynamic/src'
SKIP: tests/test07.vtc
SKIP: tests/test02.vtc
SKIP: tests/test04.vtc
SKIP: tests/test03.vtc
FAIL: tests/stale_obj.vtc
FAIL: tests/test06.vtc
FAIL: tests/test01.vtc
FAIL: tests/test05.vtc
SKIP: tests/test12.vtc
SKIP: tests/test13.vtc
FAIL: tests/test09.vtc
SKIP: tests/test14.vtc
FAIL: tests/test10.vtc
FAIL: tests/test08.vtc
FAIL: tests/test11.vtc
============================================================================
Testsuite summary for libvmod-dynamic trunk
============================================================================
# TOTAL: 15
# PASS:  0
# SKIP:  7
# XFAIL: 0
# FAIL:  8
# XPASS: 0
# ERROR: 0
```

**Comment by tianon** [comment]
Found the reason for the disparity between `7.1` and `7.1.0`: https://github.com/docker-library/official-images/commit/8657dc71f43afb77e38c0a1268dc50642d03bd3b (and the https://github.com/docker-library/official-images/commit/676a14d7606735b0acb88d61d0bdb78489634310 follow-up) :sweat_smile:

**Comment by tianon** [comment]
(In other words, the architectures that are missing from `7.1.0` but exist on `7.1` are from that old mistaken tagging.)

**Comment by gquintard** [comment]
ah! thank you. I need to update the repo to dump the logs on failed tests, will it be possible to trigger a jenkins build without merging? (not sur I can reproduce de issue as I don't have access to that architecture)

**Comment by gquintard** [comment]
you're amazing, thanks a bunch!

**Comment by gquintard** [comment]
actually, don't worry about it, I was able to reproduce:
```
**** v2    CLI RX|Message from VCC-compiler:
**** v2    CLI RX|Could not open VMOD dynamic
**** v2    CLI RX|\tFile name: /work/vmod-dynamic/src/.libs/libvmod_dynamic.so
**** v2    CLI RX|\tdlerror: /work/vmod-dynamic/src/.libs/libvmod_dynamic.so: undefined symbol: vmb_pthread
**** v2    CLI RX|('<vcl.inline>' Line 5 Pos 16)
**** v2    CLI RX|        import dynamic from "/work/vmod-dynamic/src/.libs/libvmod_dynamic.so";
**** v2    CLI RX|---------------#######--------------------------------------------------------
**** v2    CLI RX|
**** v2    CLI RX|Running VCC-compiler failed, exited with 2
**** v2    CLI RX|VCL compilation failed
---- v2    FAIL VCL does not compile
```
