### ISSUE TITLE
please merge PHP7 Stable

### ISSUE THREAD

**Issue by Lewiscowles1986** [docker-library/official-images#1238]
When I posted to gitter.im RE: RC8 I was told to raise an issue although I am not sure how useful it is to create non-issues. In the case this was incorrect, sorry.

Please merge PHP7-stable
https://github.com/docker-library/official-images/pull/1237

**Comment by yosifkit** [comment]
Thanks!  We were waiting on notifying the docker hub team as to not overwhelm their system when linked builds get triggered after pushing.  It should be available shortly (currently building).

**Comment by Lewiscowles1986** [comment]
:+1:
