### ISSUE TITLE
Almalinux ppc64le images points to older version

### ISSUE THREAD

**Issue by srbala** [docker-library/official-images#12424]
Team,

Are there any delays build/publishing `ppc64le` arch images?

We have released `8.6` version release today for `almalinux`, `latest` points to that version. But `ppc64le` still points to the older version `8.5`

https://hub.docker.com/r/ppc64le/almalinux/tags  `8.6` tags missing
https://hub.docker.com/r/amd64/almalinux/tags   `8.6` tags exists
https://hub.docker.com/r/arm64v8/almalinux/tags  `8.6` tags exists

Please advise how to resolve it

**Comment by tianon** [comment]
It's still in-queue -- it will be built/uploaded soon (unfortunately, `ppc64le` is one of our slower workers).

**Comment by srbala** [comment]
Thank you, I'll follow up later
