### ISSUE TITLE
Public API for pull tracking

### ISSUE THREAD

**Issue by gdams** [docker-library/official-images#12587]
Are there any APIs available for us to get better metrics on how many people are using the `eclipse-temurin` images?

I have discovered https://hub.docker.com/v2/repositories/library/eclipse-temurin/ which gives us the total `pull_count` but it would be great to see this on a per-tag basis?

CC @tianon @yosifkit

**Comment by tianon** [comment]
This is a great question -- I've circulated it to the appropriate folks inside Docker, and someone will be emailing you soon to discuss further. :smile:

**Comment by gdams** [comment]
Great thanks for getting back to me @tianon!

**Comment by gdams** [comment]
@tianon I haven't heard from anyone yet, which email did you give them?

**Comment by tianon** [comment]
Doh, sorry, I'd lost track of this -- I've followed up again and hopefully we can get you connected to the right folks to discuss. :bow:

The "george.adams@microsoft.com" address in your GH profile is a good place to reach you, right?

**Comment by gdams** [comment]
> Doh, sorry, I'd lost track of this -- I've followed up again and hopefully we can get you connected to the right folks to discuss. 🙇
> 
> The "[george.adams@microsoft.com](mailto:george.adams@microsoft.com)" address in your GH profile is a good place to reach you, right?

that's perfect, yes please!
