### ISSUE TITLE
node:16.15.1-buster-slim broken npm cache

### ISSUE THREAD

**Issue by mbenzenhoefer** [docker-library/official-images#12601]
It seems like the latest version of `node:16.15.1-buster-slim` is having a broken/outdated npm cache. Everytime I am trying to install my node modules (having a 3rd part dependency to `npm`) in a newly created container I am getting the following error:

```
npm WARN tarball tarball data for https://registry.npmjs.org/npm/-/npm-8.12.1.tgz (sha512-0yOlhfgu1UzP6UijnaFuIS2bES2H9D90EA5OVsf2iOZw7VBrjntXKEwKfCaFA6vMVWkCP8qnPwCxxPdnDVwlNw==) seems to be corrupted. Trying again.
npm WARN tarball tarball data for https://registry.npmjs.org/npm/-/npm-8.12.1.tgz (sha512-0yOlhfgu1UzP6UijnaFuIS2bES2H9D90EA5OVsf2iOZw7VBrjntXKEwKfCaFA6vMVWkCP8qnPwCxxPdnDVwlNw==) seems to be corrupted. Trying again.
npm ERR! code EINTEGRITY
npm ERR! sha512-0yOlhfgu1UzP6UijnaFuIS2bES2H9D90EA5OVsf2iOZw7VBrjntXKEwKfCaFA6vMVWkCP8qnPwCxxPdnDVwlNw== integrity checksum failed when using sha512: wanted sha512-0yOlhfgu1UzP6UijnaFuIS2bES2H9D90EA5OVsf2iOZw7VBrjntXKEwKfCaFA6vMVWkCP8qnPwCxxPdnDVwlNw== but got sha512-d3/o5QR8tYkCnfXdXadWE4Bv5XklvtTNVfqW0yZxFWTfwqAHDqb1eAvmp2bJv3WeVP0CYRZSf37wxb/PvgFFKQ==. (13270 bytes)
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-08T11_00_41_273Z-debug-0.log
```

- this error is not reproducible with same node/npm version on my machine
- with `node:16.15.0-buster-slim` the install is running fine
- when I perform `npm update` before the install in the container, it also works fine

Is it possible to provide a new version of the image?

**Comment by wglambert** [comment]
We don't maintain the `node` image https://hub.docker.com/_/node

I'd try asking over at https://github.com/nodejs/docker-node/issues
