### ISSUE TITLE
ubuntu:jammy sigill in jenkins for ppc64le builds

### ISSUE THREAD

**Issue by grooverdan** [docker-library/official-images#12726]
Per [the answer](https://stackoverflow.com/questions/72790436/docker-run-apt-get-update-returned-a-non-zero-code132/72823033#72823033) I just gave on SO, the "The command '/bin/sh -c groupadd -r mysql && useradd -r -g mysql mysql' returned a non-zero code: 132" error in the [mariadb 333 build of jammy based 10.9 /10.8](https://doi-janky.infosiftr.net/job/multiarch/job/ppc64le/job/mariadb/), is a SIGILL.

So is a non-ppc64le ubuntu:jammy somehow being used in the build?

**Comment by yosifkit** [comment]
Unfortunately our current `ppc64le` server is a `power8` CPU and so can't build jammy-based images that are `power9` architecture (https://lists.ubuntu.com/archives/ubuntu-devel/2021-December/041740.html). We are working with IBM to get a server with a `power9` CPU.

**Comment by grooverdan** [comment]
Thanks @yosifkit. Ouch, I didn't notice the architecture bump in [jammy](https://cdimage.ubuntu.com/releases/22.04/release/).

**Comment by tianon** [comment]
Yeah, neither did we -- I spent a long time trying to figure out why our server was running into seccomp-looking problems it really _shouldn't_ be before I realized it was `SIGILL` and it finally clicked that it was probably a baseline bump (and then, sure enough :sob:). :grimacing: :disappointed:

**Comment by KILLER1030** [comment]
hi

**Comment by yosifkit** [comment]
And now we have a `power9` machine! Thanks IBM! https://doi-janky.infosiftr.net/job/multiarch/job/ppc64le/job/mariadb/
