### ISSUE TITLE
Rocky Linux 8.6 Tag Name

### ISSUE THREAD

**Issue by robertej09** [docker-library/official-images#12822]
@NeilHanlon 
Tag name for RockyLinux 8.6.20220707 is listed as 8.6.20227707

https://github.com/docker-library/official-images/blob/5306230e99ba5d59126657d7e62559f103db50f2/library/rockylinux#L19

Close the issue if this is intentional or if this is not the appropriate place to report this. Thanks.

**Comment by yosifkit** [comment]
CC maintainer @neilhanlon

**Comment by tianon** [comment]
I think https://bugs.rockylinux.org/ or https://github.com/rocky-linux/sig-cloud-instance-images are the right place to report/discuss (per "Where to file issues" on https://hub.docker.com/_/rockylinux), but the line you've identified is where the fix would be. :+1:
