### ISSUE TITLE
eclipse-temurin jdk-alpine versions don't support linux/arm64/v8

### ISSUE THREAD

**Issue by nightswimmings** [docker-library/official-images#13021]
Would it be possible to build them with ARM support, provided alpine base images already support this arch?
It'd be nice being able to build images over them on newer MacBooks

**Comment by tianon** [comment]
:eyes: from https://hub.docker.com/_/eclipse-temurin:

> -	**Maintained by**:  
> 	[Adoptium](https://github.com/adoptium/containers)
> 
> -	**Where to get help**:  
> 	[Adoptium Slack](https://adoptium.net/slack); [Adoptium Support](https://github.com/adoptium/adoptium-support/issues/new/choose)
> 
> ...
> 
> -	**Where to file issues**:  
> 	[GitHub](https://github.com/adoptium/containers/issues); The [adoptium support](https://adoptium.net/support) page has more information on quality, roadmap and support levels for Eclipse Temurin builds. Vulnerabilities not related to Eclipse Temurin itself should be be raised to their respective projects (e.g Ubuntu vulnerabilities need to be raised directly to the Ubuntu project).
