### ISSUE TITLE
Ubuntu 18.04 Docker image libsystemd0 version issue

### ISSUE THREAD

**Issue by hwdsl2** [docker-library/official-images#13097]
Hello! The Ubuntu 18.04 Docker image includes an incorrect libsystemd0 version (237-3ubuntu10.54). The version in the official repos is 237-3ubuntu10.53, as of 2022-09-03:
https://packages.ubuntu.com/bionic-updates/libsystemd0

As a result, attempting to install libsystemd-dev fails:
```
# docker run --rm -it ubuntu:18.04 /bin/sh
# apt-get update
... ...
# apt-cache policy libsystemd0
libsystemd0:
  Installed: 237-3ubuntu10.54
  Candidate: 237-3ubuntu10.54
  Version table:
 *** 237-3ubuntu10.54 100
        100 /var/lib/dpkg/status
     237-3ubuntu10.53 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
     237-3ubuntu10.50 500
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
     237-3ubuntu10 500
        500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages
# apt-get install libsystemd-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libsystemd-dev : Depends: libsystemd0 (= 237-3ubuntu10.53) but 237-3ubuntu10.54 is to be installed
E: Unable to correct problems, you have held broken packages.
#
```

The libsystemd0 version 237-3ubuntu10.54 isn't in the official Ubuntu repos at all, as of 2022-09-03. It's unclear how that got included in the official Docker image.

/cc @woky @cjdcordeiro @mwhudson @toabctl

Thank you for looking into this.

**Comment by hwdsl2** [comment]
Also cc: @tianon

**Comment by hugofpaiva** [comment]
up

**Comment by mwhudson** [comment]
Oh right 237-3ubuntu10.54 got reverted, we should republish an image with 237-3ubuntu10.53 in. (Unless a 10.55 is imminent...)

**Comment by mwhudson** [comment]
here is the bug about the revert fwiw https://bugs.launchpad.net/ubuntu/bionic/+source/systemd/+bug/1988119

**Comment by toabctl** [comment]
and https://bugs.launchpad.net/cloud-images/+bug/1988498 is the bug tracking the OCI/docker image update.

**Comment by sacru2red** [comment]
I have similar Issue, cant install "libsnmp-dev"

**Comment by woky** [comment]
There's open PR to fix this already: https://github.com/docker-library/official-images/pull/13090

There's an issue with PR bot which I'll try to resolve ASAP.
