### ISSUE TITLE
Official images as listed on the AWS ECR Public Gallery falling out-of-sync

### ISSUE THREAD

**Issue by ldebrouwer** [docker-library/official-images#13152]
Apologies for raising this here, but I previously raised this with our AWS TAM, in the Docker Slack, and in #docker-library on Libera, to no avail. However I do believe that this is the right group of people to address this with. If I'm wrong about this, please feel free to close this ticket, and maybe point me in the right direction.

It seems that occasionally the official Docker images, as hosted on the AWS ECR public gallery, fall "out-of-sync" with Docker Hub. These images, I've been led to believe, are maintained by this fine group of people, hence me raising it here.

A current example of such an instance is; https://gallery.ecr.aws/docker/library/php
As you can tell, for more recent tags, the tags are there but they're sized at 0MB, because none of the image layers seem to have been pushed.

This is the second occurrence for the https://gallery.ecr.aws/docker/library/php repository, and we've also seen it previously for the https://gallery.ecr.aws/docker/library/node repository. Which leads me to believe that the process that should publish the images there, occasionally fails.

**Comment by matwilsondocker** [comment]
Hi @ldebrouwer we are the right people. Thank you for raising this, we are aware of this issue and are working with AWS to resolve it. We know what is causing this issue and hopefully will have an update and a permanent fix soon.

**Comment by ldebrouwer** [comment]
Hi @milosgajdos, I can confirm that this seems to be resolved now. Thank you for looking into this.
