### ISSUE TITLE
Use your automated system

### ISSUE THREAD

**Issue by pierreozoux** [docker-library/official-images#1321]
I recognize that it is [complicated](https://github.com/docker-library/official-images/issues/1085) but yet efficient :)

How Could we use your infra to automate the updating process for [Rocket.Chat](https://github.com/RocketChat/Docker.Official.Image) I made it ready with `update.sh` and `generate-stackbrew-library.sh`.

Thanks for your work!

**Comment by tianon** [comment]
Sure, I'm willing to include this in the set of repos I normally hit in my
docker-library updates; want to add me as a collaborator on the repo there
so I can commit the version bumps directly?

**Comment by pierreozoux** [comment]
Thanks for Rocket.Chat :)

Could you add piwik to your system, and knonw, just added the [PR](https://github.com/docker-library/official-images/pull/1763)
(Then you can close)

**Comment by jospoortvliet** [comment]
added @tianon  ;-)
