### ISSUE TITLE
riscv64 image of Debian neither running nor could be pulled

### ISSUE THREAD

**Issue by advancedwebdeveloper** [docker-library/official-images#13228]
Hi.

> $ docker run riscv64/debian
> Unable to find image 'riscv64/debian:latest' locally
> docker: Error response from daemon: manifest for riscv64/debian:latest not found: manifest unknown: manifest unknown.
> See 'docker run --help'.
> $ docker pull riscv64/debian
> Using default tag: latest
> Error response from daemon: manifest for riscv64/debian:latest not found: manifest unknown: manifest unknown

> $ docker version
> Client:
>  Version:           unknown-version
>  API version:       1.41
>  Go version:        go1.16.2
>  Git commit:        d3c36a2a73
>  Built:             Thu Mar 18 22:37:13 2021
>  OS/Arch:           linux/riscv64
>  Context:           default
>  Experimental:      true
> 
> Server:
>  Engine:
>   Version:          dev
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.16.2
>   Git commit:       788f2883d2
>   Built:            Thu Mar 18 23:11:36 2021
>   OS/Arch:          linux/riscv64
>   Experimental:     false
>  containerd:
>   Version:          v1.5.0-beta.4-20-g969b3d638
>   GitCommit:        969b3d638bbf5fe0296f7b80adda24838266e92e
>  runc:
>   Version:          1.0.0-rc93+dev
>   GitCommit:        0ae14750669f42209a1f974943408df754148e9d
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        b9f42a0
>

**Comment by advancedwebdeveloper** [comment]
More up-to-date version Docker's CLI also unable to handle:

> $ ./docker-linux-riscv64 pull riscv64/debian
> Using default tag: latest
> Error response from daemon: manifest for riscv64/debian:latest not found: manifest unknown: manifest unknown
> $ ./docker-linux-riscv64 version
> Client:
>  Version:           22.06.0-dev
>  API version:       1.41 (downgraded from 1.42)
>  Go version:        go1.19.1
>  Git commit:        
>  Built:             Wed Sep 21 21:26:42 2022
>  OS/Arch:           linux/riscv64
>  Context:           default
> 
> Server:
>  Engine:
>   Version:          dev
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.16.2
>   Git commit:       788f2883d2
>   Built:            Thu Mar 18 23:11:36 2021
>   OS/Arch:          linux/riscv64
>   Experimental:     false
>  containerd:
>   Version:          v1.5.0-beta.4-20-g969b3d638
>   GitCommit:        969b3d638bbf5fe0296f7b80adda24838266e92e
>  runc:
>   Version:          1.0.0-rc93+dev
>   GitCommit:        0ae14750669f42209a1f974943408df754148e9d
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        b9f42a0
>

**Comment by advancedwebdeveloper** [comment]
CC @lazyparser @carlosedp

**Comment by orangecms** [comment]
I ran into the same issue. There is no `latest` tag, but `sid`, `experimental` and others.

See: https://hub.docker.com/r/riscv64/debian/tags

**Comment by yosifkit** [comment]
Thanks @orangecms, that is correct; to use `riscv/debian`, a `sid*`, `experimental*`, or `unstable*` tag must be used.  There is no `latest` since that only points to stable releases of Debian (like `bullseye`). You can see the current "supported" tags on the Hub page: https://hub.docker.com/r/riscv64/debian.

`riscv64` is only built on `sid` and `experimental` because that is all that is available since it is still not an official port architecture. See https://www.debian.org/ports/ and https://wiki.debian.org/RISC-V.

**Comment by tianon** [comment]
See also https://github.com/docker-library/official-images/pull/10502 for links to ways you can help with RISC-V in Debian!
