### ISSUE TITLE
Questions about the build process

### ISSUE THREAD

**Issue by 1oglop1** [docker-library/official-images#13326]
Hello,
Python official image does not support ubuntu as per https://github.com/docker-library/python/issues/745 so
I need to modify the official python image with `ubuntu` as the base OS + push it to our internal registry.

I'd like to replicate the process as closely as possible but I could not find how the official images are being built.
I understand `versions.sh` and `apply-templates.sh` as well as the `ci` job for tests.

Here is what I did: 

1. I forked the python repo and modified the `Dockerfile-linux.template` 
2. updated the CI job https://github.com/docker-library/python/blob/master/.github/workflows/ci.yml#L25 to include tags I need by extending `.matrix.include.runs` with a step which builds tags for the internal registry.
3. Added the push stage to `test` job 

This was enough to get the amd64 image built and pushed to the internal registry.
However, I'd like to extend for multiarch as well.

Can anyone explain the general process of how the images are being built and pushed to the docker hub?
I found some Jenkins here https://doi-janky.infosiftr.net/job/multiarch/job/_generator/ but I do not know much about that yet.

Thank you

**Comment by grooverdan** [comment]
Here's a [gh workflow](https://github.com/MariaDB/buildbot/blob/main/.github/workflows/eco_containers.yml#L39-L74) I did to push multiarch to quay.io, however any `registry:` can be used. You just need a step to transform the python Dockerfile-linux.template.

**Comment by yosifkit** [comment]
The github workflows on the repos in `docker-library` are only for testing the images to smoke test with `amd64` (and sometimes `i386` and `win-amd64`). The builds are all currently equivalent to a `docker build` (without buildkit) done on the matching architecture. The full process is described here: https://github.com/docker-library/faq/tree/0ad5fd60288109c875a54a37f6581b2deaa836db#an-images-source-changed-in-git-now-what.

The jenkins jobs seen on `https://doi-janky.infosiftr.net` are all from https://github.com/docker-library/oi-janky-groovy/ with the key jobs being under `multiarch` (builds and pushes the images), and `put-shared` (pushes the manifest list).
