### ISSUE TITLE
UTF8 Encoded SQL

### ISSUE THREAD

**Issue by wdch-nseeley** [docker-library/official-images#1336]
I recently completed a project that required the initial database to contain UTF8 encoded text. Since the initdb scripts are assumed to be ascii encoded, I had to make a minor modification to `docker-entrypoint.sh`.

`
mysql=( mysql --protocol=socket --default_character_set=utf8 -uroot )
`

This change was not a big deal for me, but I am raising the question as to whether this would be a good default. I can't think of any way it breaks compatibility with existing scripts, and the new default would provide a real benefit to anyone working with UTF8 encoded data.

Of course, an even better solution may be to use a variable.
(One step at a time...)

**Comment by tianon** [comment]
This really ought to be reported over on
https://github.com/docker-library/mysql, but
https://github.com/docker-library/mysql/pull/14 appears to contain the
really relevant discussion.

**Comment by wdch-nseeley** [comment]
That pull request is regarding the default character-set of the initial database. This issue, however, is about the encoding of sql scripts run from initdb. The scripts can easily change the encoding of the database, but the encoding of the script file itself is the problem I would like to address.

I will try creating another issue on the other page.

**Comment by wdch-nseeley** [comment]
docker-library/mysql#131
