### ISSUE TITLE
bashbrew Mac Support

### ISSUE THREAD

**Issue by zhouhaibing089** [docker-library/official-images#1341]
bashbrew does not work on mac.

```sh
$ ./bashbrew.sh --help
readlink: illegal option -- f
usage: readlink [-n] [file ...]
error: library directory './library' does not exist
```

**Comment by andyshinn** [comment]
I actually started working on this. The main problem is that gnu readlink is so prolific throughout the scripts. For starts, you can try something like this in `bashbrew`:

```shell
gnureadlink() {
	if hash greadlink 2>/dev/null; then
		greadlink "$@"
	else
		readlink "$@"
	fi
}
```

Then replace all instances of `readlink` with `gnureadlink`. Then install `greadlink` with `brew install coreutils`. Though, there are some other places broken that I am working on.

**Comment by tianon** [comment]
The newer `bashbrew` is written in Go, and thus no longer suffers from this particular issue! :tada: :+1:
