### ISSUE TITLE
Rebuild ubuntu:jammy and ubuntu:kinetic based images to fix OpenSSL vulnerabilities

### ISSUE THREAD

**Issue by tbroyer** [docker-library/official-images#13463]
Many images based on Ubuntu (including eclipse-temurin for example, https://dso.docker.com/cve/DSA-2022-0001 lists 22 linux/amd64 images) install curl, wget, ca-certificates, etc. (to download archives of installed software) and thus openssl, and Jammy and Kinetic use OpenSSL 3.
Images built before Nov 1st therefore include a vulnerable version of OpenSSL, and *just* ™ rebuilding them would be enough to get the fixed version of the package.

Is this something you can trigger? (similar to #13259 IIUC)

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/13457 :+1: (in-progress already)
