### ISSUE TITLE
Download statistics per official tags?

### ISSUE THREAD

**Issue by andyshinn** [docker-library/official-images#1352]
We're looking at removing unmaintained upstream Alpine images (https://github.com/gliderlabs/docker-alpine/pull/130). I'm wondering if there is a way to find some per-tag statistics so we can make an easier determination if these 2.x images are even in use at all?

**Comment by tianon** [comment]
I don't have access to (nor know whether there exist) stats per-tag, sorry. :disappointed:

Generally, we recommend that official images simply track whatever release granularity their upstream supports, so in this specific case I don't see any problem with removing them.  The existing tags won't be removed (will still be available for use via `alpine:2.x`), but they won't be listed under `Supported tags` anymore on the main description.

**Comment by psftw** [comment]
Some rough numbers based on the past 30 days:  The vast majority are pulling "latest" or a 3.x tag.  "2.7" is about 1.5% of pulls and "2.6" is about 0.5%.

**Comment by andyshinn** [comment]
OK, that is helpful. Should I also update the docs repo README to add the unsupported notice for 2.x somewhere?

**Comment by psftw** [comment]
@andyshinn I don't think a 2.x notice is needed.  /my2cents

**Comment by tianon** [comment]
Yeah, that's up to you but my personal thought is that it's not really
necessary.

**Comment by andyshinn** [comment]
:+1:
