### ISSUE TITLE
Problems with today's ubuntu containers on dockerhub

### ISSUE THREAD

**Issue by DrDaveD** [docker-library/official-images#13983]
I found this github repo by following the links on docker hub from the ubuntu images to [doijanky](https://hub.docker.com/u/doijanky) to [Jenkins](https://doi-janky.infosiftr.net/) to here.

When reading any of the ubuntu containers pushed to dockerhub today (it says 2 hours ago) using the go [containerd](github.com/containerd/containerd) library, the following error occurs:
```
unsupported image-specific operation on artifact with type "application/vnd.docker.container.image.v1+json
```
This error happens for example with podman and apptainer (formerly known as singularity), but it doesn't happen with docker.  Can you help narrow down what changed to figure out what is causing the problem?  Would it be possible to back out the current tags until the problem is resolved?

**Comment by DrDaveD** [comment]
Actually the error is coming from the [github.com/containers/image/v5/docker](https://github.com/containers/image/tree/main/docker) library in the [manifest package](https://github.com/containers/image/blob/929f14a56f5c0f048121f72159acbc4df37ac054/internal/manifest/errors.go#L31).

**Comment by DrDaveD** [comment]
That code was added in this [PR](https://github.com/containers/image/pull/1574) which says in part of its description:
```
- Reject image-specific operations (like inspect, image ID) on OCI artifacts
```

**Comment by tianon** [comment]
Ahhhh, commented in https://github.com/docker-library/official-images/pull/13950#issuecomment-1411007800 with my discovery so the image maintainers hopefully see it:

> The container is using the OCI media type for the manifest, but the objects inside (config and layer blob) are using _Docker_ media types, and Docker is apparently more forgiving than other runtimes about the envelope and contents matching.

**Comment by paleozogt** [comment]
This does in fact break podman/buildah:

```
$ docker run \
>   --rm -it --privileged quay.io/buildah/stable:v1.27.0 \
>   buildah pull ubuntu:bionic
Resolved "ubuntu" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/ubuntu:bionic...
copying system image from manifest list: parsing image configuration: unsupported image-specific operation on artifact with type "application/vnd.docker.container.image.v1+json"
```

**Comment by cjdcordeiro** [comment]
Yes, we're aware of it. It has indeed slipped through the cracks. We've fixed it and are now working on re-publishing new images. @tianon can either revert the https://github.com/docker-library/official-images/pull/13950 or accept the new (whichever comes first)

**Comment by cjdcordeiro** [comment]
there's a new revision waiting for approval in https://github.com/docker-library/official-images/pull/13988

the image being published here has already been published to other registries, and tools like `podman` seem to be happy now.

**Comment by tianon** [comment]
The fixed images are all pushed now. :+1:

**Comment by paleozogt** [comment]
omg its working:

```bash
$ docker run \
     --rm -it --privileged quay.io/buildah/stable:latest \
     buildah pull ubuntu:bionic
Resolved "ubuntu" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/ubuntu:bionic...
Getting image source signatures
Copying blob 72d9f18d70f3 done
Copying config 5d2df19066 done
Writing manifest to image destination
Storing signatures
5d2df19066aca89df8e5317544a1cb599dc657830184762ff6fdefaaf708db65

```
