### ISSUE TITLE
ubuntu:22.04 (at least) - no such manifest when getting the manifest with docker manifest inspect

### ISSUE THREAD

**Issue by CarpathianUA** [docker-library/official-images#13999]
I think it might be related to https://github.com/docker-library/official-images/issues/13983

Today I've realized that the image manifest is inconsistent after recent changes to the `ubuntu:22.04` image

Docker stopped to see the manifest of the image while inspecting it with `docker manifest inspect` (yesterday everything was OK in terms of inspecting the image's manifest with `docker manifest inspect`):
```
docker manifest inspect ubuntu:22.04
no such manifest: docker.io/library/ubuntu:22.04
```

my `docker` client version:
```
Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:41 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true
 ```
The same behavior with slightly older `amd64` docker client:
```
Client:
 Version:           20.10.6
 API version:       1.41
 Git commit:        370c289
 Built:             Fri Apr  9 22:42:10 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

**Comment by yosifkit** [comment]
The `ubuntu` images are now using OCI manifests and `docker manifest` does not work with in :cry:. See https://github.com/docker/cli/pull/3990 for the fix merged in Docker to fix it.

I think `docker buildx imagetools inspect --format '{{ json . }}' ubuntu:22.04` is, roughly, an alternative way to get the same information.

**Comment by CarpathianUA** [comment]
@yosifkit Got it! Thanks for quick reply!
