### ISSUE TITLE
SonarQube 9.9 (LTS) image did not get published as arm64

### ISSUE THREAD

**Issue by carminevassallo** [docker-library/official-images#14024]
Dear team,

in the context of [this PR](https://github.com/docker-library/official-images/pull/13990), we attempted to release a new SonarQube image containing both the new SonarQube 9.9 LTS application and the arm64 support for Docker users.

The PR got merged and the new images were published on [DockerHub](https://hub.docker.com/_/sonarqube); unfortunately, the only architecture supported is still `amd64`.

Could you please review our PR again and tell us if there are any issues from our side? If no more changes are required, what's the timeline for having the image supporting `arm64v8` as well? (We are gonna announce our new LTS features tomorrow).

p.s.
On the auto-generated [DockerHub quick references](https://hub.docker.com/_/sonarqube), we see the new architecture (`arm64v8`) supported already.

**Comment by yosifkit** [comment]
Sorry for the delay. It is fixed now!

Arch-specific builds: https://doi-janky.infosiftr.net/job/multiarch/view/images/view/sonarqube/
Image index combiner: https://doi-janky.infosiftr.net/job/put-shared/job/light/job/sonarqube/

Completely new architectures for a given repo mean that jenkins requires us to re-approve the job dsl script in order for the new jobs to be created and we forgot to do it.
