### ISSUE TITLE
Update 8.6.2 elastic official images

### ISSUE THREAD

**Issue by DaveSys911** [docker-library/official-images#14128]
The elastic official images tag for `8.6.2` were updated yesterday, I wanted to ask what would be the ETA for the new tags to be publically available in docker hub?

Reference:
https://github.com/docker-library/logstash
https://github.com/docker-library/kibana
https://github.com/docker-library/elasticsearch

**Comment by yosifkit** [comment]
https://github.com/docker-library/elasticsearch/tree/f04f67eeac5a73b49e7c6e9cffadd7554b708f13#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

So, they will be pushed as soon as https://github.com/docker-library/official-images/pull/14133 is merged
