### ISSUE TITLE
library/vault tags missing from latest releases

### ISSUE THREAD

**Issue by netsandbox** [docker-library/official-images#14197]
The tags from the latest vault releases are missing:
* 1.13.0
* 1.12.4
* 1.11.8
* 1.10.11

These tags are available at https://hub.docker.com/r/hashicorp/vault but are missing at https://hub.docker.com/_/vault

**Comment by yosifkit** [comment]
There hasn't been a PR since https://github.com/docker-library/official-images/pull/14037.

https://github.com/docker-library/official-images/pulls?q=is%3Apr+is%3Aclosed+label%3Alibrary%2Fvault

**Comment by mladlow** [comment]
We recommend using our Verified Publisher images on DockerHub (https://hub.docker.com/r/hashicorp/vault). Creating the official images (https://hub.docker.com/_/vault) is a manual process which we plan to deprecate with the upcoming release of Vault 1.14. You can see more information on our deprecation notice page in the Vault docs (https://developer.hashicorp.com/vault/docs/deprecation).

**Comment by netsandbox** [comment]
@mladlow Thanks for the info, I totally missed this.
Maybe you can also place a deprecation notice at https://hub.docker.com/_/vault.

**Comment by mladlow** [comment]
@netsandbox agreed, thank you for the suggestion! I've filed https://github.com/docker-library/docs/pull/2291.
