### ISSUE TITLE
[Question] Whether images of this repo impact by "Docker team organization sunsetting"

### ISSUE THREAD

**Issue by westwind-sc** [docker-library/official-images#14258]
Whether images of this repo impact by "Docker team organization sunsetting"?

https://web.docker.com/rs/790-SSB-375/images/privatereposfaq.pdf

**Comment by tianon** [comment]
The Docker Official Images are not on a Free Team, and are thus not impacted.

**Comment by tianon** [comment]
https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/
