### ISSUE TITLE
Question about Intellectual Property note

### ISSUE THREAD

**Issue by hairyhenderson** [docker-library/official-images#14346]
Hi! 👋

Someone in our community noticed this note in the [Docker Official Images docs](https://docs.docker.com/docker-hub/official_images/):

> **Note**
>
> Docker Official Images are an intellectual property of Docker.

and was curious what this meant... I'm also curious what this means, as it seems to be fairly obvious that most of the content of the official images are not _actually_ Docker Inc's IP.

Also the term "intellectual property" appears nowhere in this repo - I would hope that if Docker Inc was claiming IP rights over official images that would at least be documented on the official-images README.

_Relatedly, but probably just a docs bug - the same note exists in https://docs.docker.com/registry/recipes/mirror/ and seems a bit out of place..._

**Comment by yosifkit** [comment]
Great question. Yeah, all the Docker Official Images' Dockerfiles (+ context), and build scripts/tools are all under OSI-approved open source licenses (as far as I remember); most of the contained software is as well.

I've asked some internal people at Docker, and I'll let you know what they say.

**Comment by nemobis** [comment]
To avoid risks of FUD, it would also help to use more precise terminology. What is being claimed? Copyright? Patents? Trademarks? Something else? https://www.gnu.org/philosophy/not-ipr.html

**Comment by yosifkit** [comment]
> I've asked some internal people at Docker, and I'll let you know what they say.

I'm still waiting on a response and will continue to follow up with them and respond here.

**Comment by whalelines** [comment]
What this phrase means is that the use of Docker Official Images is subject to [Docker's Terms of Service](https://www.docker.com/legal/docker-terms-service/). We are [updating the docs](https://github.com/docker/docs/pull/19745/files#r1561067142) to more clearly reflect this intention. Thanks for your patience.

**Comment by tianon** [comment]
Updated via https://github.com/docker/docs/pull/19745 :heart:
