### ISSUE TITLE
How to update docker registry?

### ISSUE THREAD

**Issue by koenlek** [docker-library/official-images#1437]
Hi all,

I host my own docker registry. I ran it using this command:

```
docker run -d -p 5000:5000 --restart=always --name registry registry:2
```

It is version v2.2.1. Now, I want to update to v2.3. What is the proper way to do this, without loss of data (downtime is ok with me). I am clueless...

**Comment by koenlek** [comment]
I think I figured out a way to migrate to a more update-able setup:

```
docker stop registry
docker rename registry registry_backup
docker inspect registry_backup # to find volume name hash
#manually migrate data from old data container to a named container "registry_data"
sudo -s
mkdir -p /var/lib/docker/volumes/registry_data/_data/
cp -r /var/lib/docker/volumes/1d30a9cdaa6f99c2a5ef288e55e5a87e630747252cbdaa9916a505121bec0233/_data/* /var/lib/docker/volumes/registry_data/_data/
exit

#run using named container "registry_data"
docker run -d -p 127.0.0.1:5000:5000 --restart=always --name registry -v registry_data:/var/lib/registry registry:2 #I made it listen to "localhost only" for security reasons. I expose it via a reverse proxy.
```

Tested it. Had to remove the old container (`docker rm registry_backup`), as it had "--restart=always", and I do not know of another way to block it from starting on system reboot.

Now in the future, I guess I can simply update like this:

```
docker pull registry:2
docker stop registry
docker rename registry registry_backupX
docker run -d -p 127.0.0.1:5000:5000 --restart=always --name registry -v registry_data:/var/lib/registry registry:2
```

**Comment by tianon** [comment]
Hey, sorry this got lost -- in the future, issues like this for the `registry` image would be more appropriately filed over at https://github.com/docker/distribution-library-image/issues.

Glad you got it figured out!

**Comment by tinours** [comment]
With docker-ce you could use docker update registry_backup --restart=no to disable the auto-restart of the backup containers.
