### ISSUE TITLE
Is there a place to get image pull statistic from?

### ISSUE THREAD

**Issue by dpwspoon** [docker-library/official-images#1446]
Not sure if this is the right place to ask.  I would like to be able to get image pull statistics, preferably via an API.  For example, on docker hub I can see the number of pulls [here](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=kaazing-gatewaY&starCount=0).

Additionally, if possible I would like to be able to correlate the downloads to other events, tweets, conferences, etc.  I.e. get the statistics at specific dates/over time.

**Comment by bboreham** [comment]
https://hub.docker.com/v2/repositories/kaazing/gateway/

**Comment by dpwspoon** [comment]
Thanks

**Comment by dpwspoon** [comment]
@bboreham, how about for official images?  I was hoping this would work:

https://hub.docker.com/v2/repositories/_/kaazing-gateway/

for

https://hub.docker.com/_/kaazing-gateway/

**Comment by tianon** [comment]
Give https://hub.docker.com/v2/repositories/library/kaazing-gateway/ a try :+1:

**Comment by dpwspoon** [comment]
Thanks Again

**Comment by otravers** [comment]
Not sure if I should necro-post in a closed issue, but is there a way to retrieve historical data for stars and pulls by month?

**Comment by rsamban** [comment]
Is there a way to get the statistics by tag

**Comment by yosifkit** [comment]
@otravers and @rsamban, no api endpoint that I know of. I'm not even sure that they store those data points.  You could generate at least the pullls and stars by month with a small transformation script to periodically scrape the Docker Hub and store it in a metrics database.

**Comment by ruffsl** [comment]
I found a way as @yosifkit describes to poll the API and keep track of the history yourself:
https://www.brianchristner.io/how-to-track-docker-hub-metrics/

![image](https://user-images.githubusercontent.com/2293573/30573480-03f97ca2-9ca9-11e7-9607-d11f868b7ef0.png)


> note that some of the APIs have changed since the dashboard was created, eg
> docker_hub_pulls_total{image="ubuntu"} to
> docker_hub_image_pulls_total{image="ubuntu",user="library"}

Also, if you had to putz around like I did to figure out what datasource you need for the dashboard, given the docker-compose file in this repo:

https://github.com/vegasbrianc/docker-pulls/blob/880fe4c9c59eda5e88a01856b609085d3b3bcd39/docker-compose.yml

here is an example that worked for me:

![image](https://user-images.githubusercontent.com/2293573/30573379-5e4baa46-9ca8-11e7-8119-0b29d20f55fa.png)

**Comment by hgasimov** [comment]
How about tracking using Google Apps Script and Google Sheet? It's quick and doesn't need any installation. You can find more about that here https://www.gasimof.com/blog/track_docker_image_pulls/

**Comment by rajko-rad** [comment]
Any updates here? Would be awesome if there is a database handy somewhere

**Comment by tianon** [comment]
I think https://github.com/docker/roadmap/issues/162 is probably a more appropriate place to ask about / track this feature for Hub in general.
