### ISSUE TITLE
Question about tag version

### ISSUE THREAD

**Issue by Yikun** [docker-library/official-images#14506]
As you might noticed in: https://github.com/docker-library/official-images/pull/13089, the Apache Spark image is in the review queue.

We have a question about tag version: we can see the guidline in [1], does the DOI required all image must use someting like `3.4.0`?

In Apache Spark, we are using something like `v3.4.0` tag (with prefix `v`) before.

In order to keep backward compatibility, can we still keep the original name rules? or we have to use `3.4.0` in DOI.

[1] https://github.com/docker-library/official-images#tags-and-aliases

**Comment by tianon** [comment]
We suggest dropping the `v` prefix, but we don't block on it - the choice is officially up to the image maintainer.

(Keep in mind that users switching to the official image will have to adjust their image references anyways though, so "backwards compatibility" from a naming perspective isn't necessarily the strongest argument.)

**Comment by Yikun** [comment]
@tianon Thanks!
