### ISSUE TITLE
The Containers are not coming up healthy 

### ISSUE THREAD

**Issue by Pushparaj171** [docker-library/official-images#14574]
Hi! 👋 
The issue is  we are recently migrated to the ubuntu 22.04 Jammy as base image before it is ubuntu 20.04
We are using the docker version 19.03.  
when we are building our services on top of the base image the images are not coming up healthy its restarting again and again 
when I go into the container and executing the java version command its giving this error 
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create GC thread. Out of system resources.
# An error report file with more information is saved as:
# //hs_err_pid70.log

**### but in the focal image the container is healthy state** 
### in this file hs_err_pid70.log
# cat //hs_err_pid70.log
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create GC thread. Out of system resources.
# Possible reasons:
#   The system is out of physical RAM or swap space
#   The process is running with CompressedOops enabled, and the Java Heap may be blocking the growth of the native heap
# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
#   Check if swap backing store is full
#   Decrease Java heap size (-Xmx/-Xms)
#   Decrease number of Java threads
#   Decrease Java thread stack sizes (-Xss)
#   Set larger code cache with -XX:ReservedCodeCacheSize=
# This output file may be truncated or incomplete.
#
#  INVALID (0xe0000001) at pc=0x0000000000000000, pid=70, tid=0x00007fcb4ca30000
#
# JRE version:  (8.0_322-b06) (build )
# Java VM: OpenJDK 64-Bit Server VM (25.322-b06 mixed mode linux-amd64 compressed oops)
# Core dump written. Default location: //core or core.70
#

---------------  T H R E A D  ---------------

Current thread (0x0000559b9e8df800):  JavaThread "Unknown thread" [_thread_in_vm, id=70, stack(0x00007ffda5bd8000,0x00007ffda5cd8000)]

Stack: [0x00007ffda5bd8000,0x00007ffda5cd8000],  sp=0x00007ffda5cd2c10,  free space=1003k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0xb48542]  VMError::report_and_die()+0x2d2
V  [libjvm.so+0x4efc77]  report_vm_out_of_memory(char const*, int, unsigned long, VMErrorType, char const*)+0x67
V  [libjvm.so+0x5d69af]  GCTaskThread::GCTaskThread(GCTaskManager*, unsigned int, unsigned int)+0x13f
V  [libjvm.so+0x5d5b0d]  GCTaskManager::initialize()+0x36d
V  [libjvm.so+0x99d742]  ParallelScavengeHeap::initialize()+0x3a2
V  [libjvm.so+0xb0b98a]  Universe::initialize_heap()+0x16a
V  [libjvm.so+0xb0bc76]  universe_init()+0x36
V  [libjvm.so+0x64fc4d]  init_globals()+0x5d
V  [libjvm.so+0xaee0e9]  Threads::create_vm(JavaVMInitArgs*, bool*)+0x419
V  [libjvm.so+0x72ba40]  JNI_CreateJavaVM+0x50
C  [libjli.so+0x7ee0]  JavaMain+0x90
C  [libjli.so+0xd829]  ContinueInNewThread0+0x69
C  [libjli.so+0x9c92]  ContinueInNewThread+0x52
C  [libjli.so+0xa398]  JLI_Launch+0x5b8
C  [java+0x671]
C  [libc.so.6+0x29d90]

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )

Other Threads:

=>0x0000559b9e8df800 (exited) JavaThread "Unknown thread" [_thread_in_vm, id=70, stack(0x00007ffda5bd8000,0x00007ffda5cd8000)]

VM state:not at safepoint (not fully initialized)

VM Mutex/Monitor currently owned by a thread: None

heap address: 0x00000003d3c00000, size: 16068 MB, Compressed Oops mode: Non-zero based:0x00000003d3bff000, Oop shift amount: 3
Narrow klass base: 0x0000000000000000, Narrow klass shift: 0

GC Heap History (0 events):
No events

Deoptimization events (0 events):
No events

Classes redefined (0 events):
No events

Internal exceptions (0 events):
No events

Events (0 events):
No events

Dynamic libraries:
3d3c00000-3fdb00000 rw-p 00000000 00:00 0
3fdb00000-671400000 ---p 00000000 00:00 0
671400000-686300000 rw-p 00000000 00:00 0
686300000-7c0000000 ---p 00000000 00:00 0
559b9dd5a000-559b9dd5b000 r-xp 00000000 08:03 50563000                   /opt/zulu8.60.0.21-ca-jre8.0.322-linux_x64/bin/java
559b9dd5b000-559b9dd5c000 r--p 00000000 08:03 50563000                   /opt/zulu8.60.0.21-ca-jre8.0.322-linux_x64/bin/java
559b9dd5c000-559b9dd5d000 rw-p 00001000 08:03 50563000                   /opt/zulu8.60.0.21-ca-jre8.0.322-linux_x64/bin/java
559b9e8c2000-559b9e91e000 rw-p 00000000 00:00 0                          [heap]
7fcb38ed4000-7fcb392bd000 rw-p 00000000 00:00 0
7fcb392bd000-7fcb3a659000 ---p 00000000 00:00 0
7fcb3a659000-7fcb3a7a9000 rw-p 00000000 00:00 0
7fcb3a7a9000-7fcb3bb45000 ---p 00000000 00:00 0
7fcb3bb45000-7fcb3bbed000 rw-p 00000000 00:00 0
7fcb3bbed000-7fcb3c5bb000 ---p 00000000 00:00 0
7fcb3c5bb000-7fcb3c5c6000 rw-p 00000000 00:00 0
7fcb3c5c6000-7fcb3c97c000 ---p 00000000 00:00 0
7fcb3c97c000-7fcb3cbec000 rwxp 00000000 00:00 0
7fcb3cbec000-7fcb4b97c000 ---p 00000000 00:00 0
7fcb4b97c000-7fcb4b998000 r-xp 00000000 08:03 16821367                   /opt/zulu8.60.0.21-ca-jre8.0.322-linux_x64/lib/amd64/libzip.so
7fcb4b998000-7fcb4b999000 r--p 0001b000 08:03 16821367                   /opt/zulu8.60.0.21-ca-jre8.0.322-linux_x64/lib/amd64/libzip.so
7fcb4b999000-7fcb4b99a000 rw-p 0001c000 08:03 16821367                   /opt/zulu8.60.0.21-ca-jre8.0.322-linux_x64/lib/amd64/libzip.so
7fcb4b99a000-7fcb4b9a2000 rw-s 00000000 08:03 18683478                   /tmp/hsperfdata_root/70
7fcb4b9a2000-7fcb4b9cb000 r-xp 00000000 08:03 16821347                   /opt/zulu8.60.0.21-ca-jre8.0.322-linux_x64/lib/amd64/libjava.so
7fcb4b9cb000-7fcb4b9cc000 ---p 00029000 08:03 16821347                   /opt/zulu8.60.0.21-ca-jre8.0.322-linux_x64/lib/amd64/libjava.so
7fcb4b9cc000-7fcb4b9cd000 r--p 00029000 08:03 16821347                   /opt/zulu8.60.0.21-ca-jre8.0.322-linux_x64/lib/amd64/libjava.so
7fcb4b9cd000-7fcb4b9cf000 rw-p 0002a000 08:03 16821347                   /opt/zulu8.60.0.21-ca-jre8.0.322-linux_x64/lib/amd64/libjava.so
7fcb4b9cf000-7fcb4b9dc000 r-xp 00000000 08:03 16821366                   /opt/zulu8.60.0.21-ca-jre8.0.322-linux_x64/lib/amd64/libverify.so
7fcb4b9dc000-7fcb4b9de000 r--p 0000c000 08:03 16821366                   /opt/zulu8.60.0.21-ca-jre8.0.322-linux_x64/lib/amd64/libverify.so
7fcb4b9de000-7fcb4b9df000 rw-p 0000e000 08:03 16821366                   /opt/zulu8.60.0.21-ca-jre8.0.322-linux_x64/lib/amd64/libverify.so
7fcb4b9df000-7fcb4b9e0000 r--p 00000000 08:03 90752                      /usr/lib/x86_64-linux-gnu/librt.so.1
7fcb4b9e0000-7fcb4b9e1000 r-xp 00001000 08:03 90752                      /usr/lib/x86_64-linux-gnu/librt.so.1
7fcb4b9e1000-7fcb4b9e2000 r--p 00002000 08:03 90752                      /usr/lib/x86_64-linux-gnu/librt.so.1
7fcb4b9e2000-7fcb4b9e3000 r--p 00002000 08:03 90752                      /usr/lib/x86_64-linux-gnu/librt.so.1
7fcb4b9e3000-7fcb4b9e4000 rw-p 00003000 08:03 90752                      /usr/lib/x86_64-linux-gnu/librt.so.1
7fcb4b9e4000-7fcb4b9e5000 ---p 00000000 00:00 0
7fcb4b9e5000-7fcb4bae5000 rw-p 00000000 00:00 0
7fcb4bae5000-7fcb4baf3000 r--p 00000000 08:03 90707                      /usr/lib/x86_64-linux-gnu/libm.so.6
7fcb4baf3000-7fcb4bb6f000 r-xp 0000e000 08:03 90707                      /usr/lib/x86_64-linux-gnu/libm.so.6
7fcb4bb6f000-7fcb4bbca000 r--p 0008a000 08:03 90707                      /usr/lib/x86_64-linux-gnu/libm.so.6
7fcb4bbca000-7fcb4bbcb000 r--p 000e4000 08:03 90707                      /usr/lib/x86_64-linux-gnu/libm.so.6
7fcb4bbcb000-7fcb4bbcc000 rw-p 000e5000 08:03 90707                      /usr/lib/x86_64-linux-gnu/libm.so.6
7fcb4bbcc000-7fcb4c93b000 r-xp 00000000 08:03 50562887                   /opt/zulu8.60.0.21-ca-jre8.0.322-linux_x64/lib/amd64/server/libjvm.so
7fcb4c93b000-7fcb4c9d2000 r--p 00d6e000 08:03 50562887                   /opt/zulu8.60.0.21-ca-jre8.0.322-linux_x64/lib/amd64/server/libjvm.so
7fcb4c9d2000-7fcb4c9fb000 rw-p 00e05000 08:03 50562887                   /opt/zulu8.60.0.21-ca-jre8.0.322-linux_x64/lib/amd64/server/libjvm.so
7fcb4c9fb000-7fcb4ca31000 rw-p 00000000 00:00 0
7fcb4ca31000-7fcb4ca59000 r--p 00000000 08:03 90655                      /usr/lib/x86_64-linux-gnu/libc.so.6
7fcb4ca59000-7fcb4cbee000 r-xp 00028000 08:03 90655                      /usr/lib/x86_64-linux-gnu/libc.so.6
7fcb4cbee000-7fcb4cc46000 r--p 001bd000 08:03 90655                      /usr/lib/x86_64-linux-gnu/libc.so.6
7fcb4cc46000-7fcb4cc4a000 r--p 00214000 08:03 90655                      /usr/lib/x86_64-linux-gnu/libc.so.6
7fcb4cc4a000-7fcb4cc4c000 rw-p 00218000 08:03 90655                      /usr/lib/x86_64-linux-gnu/libc.so.6
7fcb4cc4c000-7fcb4cc59000 rw-p 00000000 00:00 0
7fcb4cc59000-7fcb4cc5a000 r--p 00000000 08:03 90669                      /usr/lib/x86_64-linux-gnu/libdl.so.2
7fcb4cc5a000-7fcb4cc5b000 r-xp 00001000 08:03 90669                      /usr/lib/x86_64-linux-gnu/libdl.so.2
7fcb4cc5b000-7fcb4cc5c000 r--p 00002000 08:03 90669                      /usr/lib/x86_64-linux-gnu/libdl.so.2
7fcb4cc5c000-7fcb4cc5d000 r--p 00002000 08:03 90669                      /usr/lib/x86_64-linux-gnu/libdl.so.2
7fcb4cc5d000-7fcb4cc5e000 rw-p 00003000 08:03 90669                      /usr/lib/x86_64-linux-gnu/libdl.so.2
7fcb4cc5e000-7fcb4cc75000 r-xp 00000000 08:03 33719227                   /opt/zulu8.60.0.21-ca-jre8.0.322-linux_x64/lib/amd64/jli/libjli.so
7fcb4cc75000-7fcb4cc76000 r--p 00016000 08:03 33719227                   /opt/zulu8.60.0.21-ca-jre8.0.322-linux_x64/lib/amd64/jli/libjli.so
7fcb4cc76000-7fcb4cc77000 rw-p 00017000 08:03 33719227                   /opt/zulu8.60.0.21-ca-jre8.0.322-linux_x64/lib/amd64/jli/libjli.so
7fcb4cc77000-7fcb4cc78000 r--p 00000000 08:03 90750                      /usr/lib/x86_64-linux-gnu/libpthread.so.0
7fcb4cc78000-7fcb4cc79000 r-xp 00001000 08:03 90750                      /usr/lib/x86_64-linux-gnu/libpthread.so.0
7fcb4cc79000-7fcb4cc7a000 r--p 00002000 08:03 90750                      /usr/lib/x86_64-linux-gnu/libpthread.so.0
7fcb4cc7a000-7fcb4cc7b000 r--p 00002000 08:03 90750                      /usr/lib/x86_64-linux-gnu/libpthread.so.0
7fcb4cc7b000-7fcb4cc7c000 rw-p 00003000 08:03 90750                      /usr/lib/x86_64-linux-gnu/libpthread.so.0
7fcb4cc7d000-7fcb4cc80000 rw-p 00000000 00:00 0
7fcb4cc80000-7fcb4cc82000 r--p 00000000 08:03 90637                      /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7fcb4cc82000-7fcb4ccac000 r-xp 00002000 08:03 90637                      /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7fcb4ccac000-7fcb4ccb7000 r--p 0002c000 08:03 90637                      /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7fcb4ccb7000-7fcb4ccb8000 r--p 00000000 00:00 0
7fcb4ccb8000-7fcb4ccba000 r--p 00037000 08:03 90637                      /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7fcb4ccba000-7fcb4ccbc000 rw-p 00039000 08:03 90637                      /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7ffda5bd8000-7ffda5bdc000 ---p 00000000 00:00 0
7ffda5bdc000-7ffda5cd8000 rw-p 00000000 00:00 0                          [stack]
7ffda5d6e000-7ffda5d70000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

VM Arguments:
java_command: <unknown>
java_class_path (initial): .
Launcher Type: SUN_STANDARD

Environment Variables:
JAVA_HOME=/opt/zulu8.60.0.21-ca-jre8.0.322-linux_x64
JRE_HOME=/opt/zulu8.60.0.21-ca-jre8.0.322-linux_x64
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/zulu8.60.0.21-ca-jre8.0.322-linux_x64/bin

Signal Handlers:
SIGSEGV: [libjvm.so+0xb49bd0], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGBUS: [libjvm.so+0xb49bd0], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGFPE: [libjvm.so+0x96d660], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGPIPE: [libjvm.so+0x96d660], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGXFSZ: [libjvm.so+0x96d660], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGILL: [libjvm.so+0x96d660], sa_mask[0]=11111111011111111101111111111110, sa_flags=SA_RESTART|SA_SIGINFO
SIGUSR1: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
SIGUSR2: [libjvm.so+0x96dc10], sa_mask[0]=00000000000000000000000000000000, sa_flags=SA_RESTART|SA_SIGINFO
SIGHUP: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
SIGINT: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
SIGTERM: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none
SIGQUIT: SIG_DFL, sa_mask[0]=00000000000000000000000000000000, sa_flags=none

---------------  S Y S T E M  ---------------

OS:DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

uname:Linux 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64
libc:glibc 2.35 NPTL 2.35
rlimit: STACK 8192k, CORE infinity, NPROC infinity, NOFILE 1048576, AS infinity
load average:0.05 0.03 0.05

/proc/meminfo:
MemTotal:       65807748 kB
MemFree:        52707984 kB
MemAvailable:   64154996 kB
Buffers:            3892 kB
Cached:         11614304 kB
SwapCached:            0 kB
Active:           761420 kB
Inactive:       11116840 kB
Active(anon):     249104 kB
Inactive(anon):    36808 kB
Active(file):     512316 kB
Inactive(file): 11080032 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       4196348 kB
SwapFree:        4196348 kB
Dirty:                 4 kB
Writeback:             0 kB
AnonPages:        259904 kB
Mapped:           105792 kB
Shmem:             25856 kB
Slab:             448284 kB
SReclaimable:     386536 kB
SUnreclaim:        61748 kB
KernelStack:        5008 kB
PageTables:        11848 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    37100220 kB
Committed_AS:    2719840 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      252932 kB
VmallocChunk:   34359341052 kB
Percpu:             1952 kB
HardwareCorrupted:     0 kB
AnonHugePages:     88064 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       96128 kB
DirectMap2M:    67012608 kB

container (cgroup) information:
container_type: cgroupv1
cpu_cpuset_cpus: 0-7
cpu_memory_nodes: 0
active_processor_count: 8
cpu_quota: -1
cpu_period: 100000
cpu_shares: -1
memory_limit_in_bytes: -1
memory_and_swap_limit_in_bytes: -1
memory_soft_limit_in_bytes: -1
memory_usage_in_bytes: 9199616
memory_max_usage_in_bytes: 9236480

VMWare virtualization detected

CPU:total 8 (initial active 8) (2 cores per cpu, 1 threads per core) family 6 model 15 stepping 1, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, tsc, tscinvbit

/proc/cpuinfo:
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
stepping        : 1
microcode       : 0xb000040
cpu MHz         : 2596.992
cache size      : 35840 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc arch_perfmon nopl tsc_reliable nonstop_tsc eagerfpu pni ssse3 cx16 tsc_deadline_timer hypervisor lahf_lm tsc_adjust arat
bogomips        : 5193.98
clflush size    : 64
cache_alignment : 64
address sizes   : 45 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
stepping        : 1
microcode       : 0xb000040
cpu MHz         : 2596.992
cache size      : 35840 KB
physical id     : 0
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc arch_perfmon nopl tsc_reliable nonstop_tsc eagerfpu pni ssse3 cx16 tsc_deadline_timer hypervisor lahf_lm tsc_adjust arat
bogomips        : 5193.98
clflush size    : 64
cache_alignment : 64
address sizes   : 45 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
stepping        : 1
microcode       : 0xb000040
cpu MHz         : 2596.992
cache size      : 35840 KB
physical id     : 1
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc arch_perfmon nopl tsc_reliable nonstop_tsc eagerfpu pni ssse3 cx16 tsc_deadline_timer hypervisor lahf_lm tsc_adjust arat
bogomips        : 5193.98
clflush size    : 64
cache_alignment : 64
address sizes   : 45 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
stepping        : 1
microcode       : 0xb000040
cpu MHz         : 2596.992
cache size      : 35840 KB
physical id     : 1
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc arch_perfmon nopl tsc_reliable nonstop_tsc eagerfpu pni ssse3 cx16 tsc_deadline_timer hypervisor lahf_lm tsc_adjust arat
bogomips        : 5193.98
clflush size    : 64
cache_alignment : 64
address sizes   : 45 bits physical, 48 bits virtual
power management:

processor       : 4
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
stepping        : 1
microcode       : 0xb000040
cpu MHz         : 2596.992
cache size      : 35840 KB
physical id     : 2
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 4
initial apicid  : 4
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc arch_perfmon nopl tsc_reliable nonstop_tsc eagerfpu pni ssse3 cx16 tsc_deadline_timer hypervisor lahf_lm tsc_adjust arat
bogomips        : 5193.98
clflush size    : 64
cache_alignment : 64
address sizes   : 45 bits physical, 48 bits virtual
power management:

processor       : 5
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
stepping        : 1
microcode       : 0xb000040
cpu MHz         : 2596.992
cache size      : 35840 KB
physical id     : 2
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 5
initial apicid  : 5
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc arch_perfmon nopl tsc_reliable nonstop_tsc eagerfpu pni ssse3 cx16 tsc_deadline_timer hypervisor lahf_lm tsc_adjust arat
bogomips        : 5193.98
clflush size    : 64
cache_alignment : 64
address sizes   : 45 bits physical, 48 bits virtual
power management:

processor       : 6
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
stepping        : 1
microcode       : 0xb000040
cpu MHz         : 2596.992
cache size      : 35840 KB
physical id     : 3
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 6
initial apicid  : 6
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc arch_perfmon nopl tsc_reliable nonstop_tsc eagerfpu pni ssse3 cx16 tsc_deadline_timer hypervisor lahf_lm tsc_adjust arat
bogomips        : 5193.98
clflush size    : 64
cache_alignment : 64
address sizes   : 45 bits physical, 48 bits virtual
power management:

processor       : 7
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
stepping        : 1
microcode       : 0xb000040
cpu MHz         : 2596.992
cache size      : 35840 KB
physical id     : 3
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 7
initial apicid  : 7
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc arch_perfmon nopl tsc_reliable nonstop_tsc eagerfpu pni ssse3 cx16 tsc_deadline_timer hypervisor lahf_lm tsc_adjust arat
bogomips        : 5193.98
clflush size    : 64
cache_alignment : 64
address sizes   : 45 bits physical, 48 bits virtual
power management:

Memory: 4k page, physical 65807748k(52707984k free), swap 4196348k(4196348k free)

vm_info: OpenJDK 64-Bit Server VM (25.322-b06) for linux-amd64 JRE (Zulu 8.60.0.21-CA-linux64) (1.8.0_322-b06), built on Jan 13 2022 09:49:59 by "zulu_re" with gcc 7.3.0

time: Wed May  3 11:56:54 2023
timezone: UTC
elapsed time: 0.025679 seconds (0d 0h 0m 0s)

**### Solutions I has tried :**
- increased the swap size to 4gb 
- Checked if swap backing store is full
-  Decrease Java heap size (-Xmx/-Xms)

**When I gave started the container --privileged flag that is working fine** 

### **Reference :** 
https://stackoverflow.com/questions/72841549/container-fails-to-start-insufficient-memory-for-the-java-runtime-environment-t
https://github.com/adoptium/temurin-build/issues/3020
In the above link they are asking to update the docker to the latest version or above 20.10.10 to resolve the issue 
 
if the solution is need to update the docker to the latest version can i get the solution

**Comment by tianon** [comment]
Please check the "Where to get help" links on Docker Hub for the image you're using -- this is definitely not the appropriate place, sorry!
