### ISSUE TITLE
Node 16 got published twice in last two days

### ISSUE THREAD

**Issue by abdullah2993** [docker-library/official-images#14581]
Whats the reason behind node:16 and postgres:15 images being pushed again? This causes cache invalidation and have to pull images again from the internet.

**Comment by yosifkit** [comment]
Not all architectures build at the same time or at the same speed so the list is updated when each is finished. Each architecture usually only changes once, but the [image index](https://github.com/opencontainers/image-spec/blob/v1.0/image-index.md) has to be updated each time. 

The `postgres:15.2-bullseye` images only changed once per architecture (but the image index was updated more than once).

You can see each change that happened in the history of our `repo-info` repository. For example: https://github.com/docker-library/repo-info/blame/6bd1648d45ce48f83ea557af6ab96a755347573e/repos/node/remote/16.20.0.md

I've looked though the history of the changes to the `amd64` image via the `repos/node/remote/16.20.0.md` file. We merged https://github.com/docker-library/official-images/pull/14559 and https://github.com/docker-library/official-images/pull/14557 at the same time, but it looks each of them caused a separate `node` rebuild 😞:

 - [this commit](https://github.com/docker-library/repo-info/commit/f5585bbeff0c2451177aad4b9d52adbf98654c2d#diff-b8da900cf19cad17b21ffdfa7b5183414f2eb9cede2287120d55c883c4a4bf92) shows the `buildpack-deps` triggered rebuild
 - [this commit](https://github.com/docker-library/repo-info/commit/8a7e497b4f64ded24e3450239ac995316fc2908c#diff-b8da900cf19cad17b21ffdfa7b5183414f2eb9cede2287120d55c883c4a4bf92) shows the `debian` triggered rebuild.
