### ISSUE TITLE
Unable to pull; registry-1.docker.io returns code: UNAUTHORIZED

### ISSUE THREAD

**Issue by quinncomendant** [docker-library/official-images#1489]
I've just noticed I'm unable to `docker pull` any images. I've tried with several official images (`ubuntu`, `node`, `busybox`):

	[q@x/0 ~] docker pull busybox
	Using default tag: latest
	Error response from daemon: Get https://registry-1.docker.io/v2/library/busybox/manifests/latest: Received unexpected HTTP status: 500 Internal Server Error

[That URL](https://registry-1.docker.io/v2/library/busybox/manifests/latest) returns this JSON:

    {"errors":[{"code":"UNAUTHORIZED","message":"access to the requested resource is not authorized","detail":[{"Type":"repository","Name":"library/busybox","Action":"pull"}]}]}

**Comment by tianon** [comment]
Indeed -- I think there's some kind of Hub infra issue going on (I'm seeing issues as well).  There's not much we can do about it, so I'm closing this issue, but the appropriate venue for reporting this sort of failure in the future would likely be support@docker.com.  Hopefully they at least get https://status.docker.com/ updated soon to note the issues.

**Comment by tianon** [comment]
I've sent a note to Support just now to let them know something's up. :+1:

**Comment by quinncomendant** [comment]
It seems to be working again. 🐳

**Comment by zuchi** [comment]
I have the same issue, but the message that have received  is: attempting next endpoint for pull after error: manifest unknown: manifest unknown. Anybody know if the docker repository has any problem? I have tried with many images too.

**Comment by tianon** [comment]
See https://status.docker.com/ -- we don't have any control over this, and only have hearts and hugs for the ops folks currently trying to figure out what's going on and fix it. :heart: :confounded:

**Comment by zuchi** [comment]
thanks @tianon, I have just seen the status... let's waiting that they fix it. Thanks again.

**Comment by col-panic** [comment]
Just got this message on Get https://registry-1.docker.io/v2/sonatype/nexus/manifests/oss: unauthorized: incorrect username or password

**Comment by cparadigm** [comment]
Still very much a live issue.

**Comment by tianon** [comment]
@col-panic this repo is simply another consumer of Hub; I'd recommend contacting support@docker.com if you're experiencing issues with any of Docker's hosted services (which as noted above, we have no control over or visibility into)

**Comment by gcameo** [comment]
I have been having an issue with this whenever I do a build from Jenkins for about a week now. 

Step 1/5 : FROM openjdk:8
Get https://registry-1.docker.io/v2/library/openjdk/manifests/8: unauthorized: incorrect username or password

Any ideas how to resolve this?

**Comment by yosifkit** [comment]
@gcameo, I'd suggest the same thing as above, contact support@docker.com. 

My wild guess is that some algorithm that detects and blocks bad actors has misjudged your Jenkins IP, but as tianon noted, "we have no control over or visibility into" Docker Hub.

**Comment by gcameo** [comment]
@yosifkit Thank you very much. I will reach out to them then

**Comment by gcameo** [comment]
I have changed the IP address of the Jenkins server but still getting the issue. Is it possible to configure docker to use a different public repository?
