### ISSUE TITLE
Documentation: FAQ on "Consistency" is inconsistent

### ISSUE THREAD

**Issue by ericbuehl** [docker-library/official-images#14918]
The FAQ regarding [Consistency](https://github.com/docker-library/official-images#consistency) leaves some open questions.

It states that 
1:
> All official images should provide a consistent interface. A beginning user should be able to docker run official-image bash (or sh) without needing to learn about --entrypoint.

and 2:
> It is also nice for advanced users to take advantage of entrypoint, so that they can docker run official-image --arg1 --arg2 without having to specify the binary to execute.

It then goes on to suggest:
> If the startup process does not need arguments, just use CMD

However, to my knowledge, it is not possible to satisfy both 1 and 2 using the CMD alone.  Does this mean that if an image can accept extra arguments a separate wrapper script should be added to decide if the user intends to overwrite the entrypoint?  The example script provided acknowledges that it only will work when all arguments begin with a hyphen.  Is this not error-prone and counter to the goal of consistency?

**Comment by tianon** [comment]
Thanks for the question!  Number 1 is essentially a clarification of how a given `ENTRYPOINT` has to work, number 1 is a firmer requirement than number 2, and number 2 is only recommended for unambiguous/reliable cases (and yes, a wrapper script/`ENTRYPOINT` _is_ required if you wish to satisfy both, but at this point there are quite a few examples images which do so successfully). :+1:

**Comment by ericbuehl** [comment]
Thanks for the info!  One suggestion could be to always include a script such as the one in 2.  Is there a reason not to do this?

**Comment by Mroczek1992** [comment]
********

**Comment by tianon** [comment]
That'd be primarily because it's left up to each image maintainer to make that choice (not something we require of them) explicitly because it is added maintenance burden on those maintainers, so it seems unreasonable to _require_ they maintain such a thing.
