### ISSUE TITLE
Wrong mediaType in ubuntu 22.04, 22.10, errors in Gitlab.

### ISSUE THREAD

**Issue by anutator** [docker-library/official-images#14938]
Gitlab doesn't work with old `application/vnd.oci.image.index.v1+json` by default.
In old image ubuntu:20.10 the mediaType was correct `application/vnd.docker.distribution.manifest.list.v2+json`.
Please, make new images with `application/vnd.docker.distribution.manifest.list.v2+json`.

```bash
$ docker manifest inspect ubuntu:22.10
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
....

$ docker manifest inspect ubuntu:20.10
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
....
```

Error in Gitlab:

Job failed: prepare environment: waiting for pod running: pulling image "hub.mysite.ru/docker/library/ubuntu:22.04": image pull failed: rpc error: code = Unknown desc = Error response from daemon: mediaType in manifest list should be 'application/vnd.docker.distribution.manifest.list.v2+json' not 'application/vnd.oci.image.index.v1+json'. Check [https://docs.gitlab.com/runner/shells/index.html#shell-profile-loading](https://docs.gitlab.com/runner/shells/index.html#shell-profile-loading "Пройти по ссылке") for more information

**Comment by yosifkit** [comment]
`application/vnd.oci.image.index.v1+json` is not old; it is the correct type from the newer [OCI specification](https://github.com/opencontainers/image-spec/blob/main/spec.md) that supersedes the Docker types. Eventually all Docker Official Images will be using the OCI specification.

As far as I can tell, GitLab should support OCI media types. Perhaps your GitLab server or the container runtime that is running the pods needs to be updated.
