### ISSUE TITLE
Adding a new image to the xwiki official images

### ISSUE THREAD

**Issue by vmassol** [docker-library/official-images#15069]
Hi official image admins,

I'm from the XWiki dev team and we already publish official docker images for XWiki at https://hub.docker.com/_/xwiki

They are images that extend Tomcat and target specific databases.

We'd like to also offer a new custom image of Solr for XWiki for when XWiki users want to configure an external Solr instance (instead of the embedded one that comes with XWiki).

Would it be acceptable for you if we add 2 new entries in the https://github.com/docker-library/official-images/blob/master/library/xwiki file for building and providing an XWiki Solr image?

Thank you
-Vincent
XWiki committer

cc @yosifkit (who knows what we're doing with XWiki :)).

**Comment by tianon** [comment]
Conceptually that sounds reasonable, although the `Dockerfile`/Dockerization will need to pass the same review. :+1:
