### ISSUE TITLE
Broken automation for 7.x ELK image diffs

### ISSUE THREAD

**Issue by DaveSys911** [docker-library/official-images#15091]
Hi team, the automation for diffs seems to not be kept the new `7.12.11` tags published by us. For exp https://github.com/docker-library/logstash/commit/c38bad7ead134a62b8ef6b26b917ca2757582ffc. So docker-bot automation isn't processing `7.x` updates

**Comment by yosifkit** [comment]
The github workflows are known to be a little flaky and aren't the ones doing the updates.

👀 It seems that the `update.sh` jobs for `elasticsearch`, `logstash` and `kibana` in Jenkins are failing at this same [part](https://github.com/docker-library/elasticsearch/blob/b57fb36f0db4f7969999ddf3781d55ec2e7210e5/update.sh#L104-L108) of their `update.sh` scripts. The published Dockerfiles for tag `v8.9.0` in `elastic/dockerfiles` do not match the tag: e.g. https://github.com/elastic/dockerfiles/blob/v8.9.0/elasticsearch/Dockerfile (52af994dfd1a365cdf3f8c46993e1dab8f1fd4ef) is a Dockerfile for `7.3.1`.  Perhaps that git tag can be updated to the correct commit for `8.9.0` Dockerfiles?

**Comment by yosifkit** [comment]
Looks like the automation picked it up while I was asleep. PR to update the images on Docker Hub here: https://github.com/docker-library/official-images/pull/15246

**Comment by xeraa** [comment]
Great, thanks so much!

Is there a way to backfill the other releases we missed, namely 7.17.11, 8.8.2, 8.9.0?

**Comment by DaveSys911** [comment]
@yosifkit, thank you!
and joining in on the question, anything to be done about the missed releases?

**Comment by yosifkit** [comment]
🤔 Our elasticsearch, kibana, and logstash repos were not designed for keeping an old version. I'll see if I can find a way to add them temporarily.

**Comment by DaveSys911** [comment]
Thx @yosifkit, Did you manage to find any workaround to build the old versions?

**Comment by yosifkit** [comment]
Yeah, I have some PRs I was going to attempt moving forward today:
- https://github.com/docker-library/elasticsearch/pull/208
- https://github.com/docker-library/logstash/pull/106
- https://github.com/docker-library/kibana/pull/100

**Comment by yosifkit** [comment]
Everything looks good to me; images will be added once https://github.com/docker-library/official-images/pull/15276 is merged.

**Comment by xeraa** [comment]
Thanks a lot! Looks like we got them all :)

The default sorting shows the newest ones first (so 8.9.0 now before 8.9.1) but I think that's so minor that we can just ignore it. Going forward, we'll make sure to get them up right away — thanks again!
