### ISSUE TITLE
The Eclipse Temurin Alpine images do not contain binutils

### ISSUE THREAD

**Issue by AtesComp** [docker-library/official-images#15287]
The Eclipse Temurin docker images are Java images as a replacement for the deprecated OpenJDK images. 

The Java "jlink" command requires objcopy from the binutils package. The non-Alpine images contain this package. However, it doesn't seem to be installed on the Alpine images.  My test shows:
* eclipse-temurin:17-jammy has the binutils package by default
* eclipse-temurin:17-alpine doesn't contain the binutils package

Generally, this is not an issue since it is easily corrected with "apk install binutils". However, in a protected environment, the Alpine repository must be replicated to get these essential tools or some other special process to get the binutils package.

This may or may not be true for other suggested OpenJDK replacement images:
[amazoncorretto](https://hub.docker.com/_/amazoncorretto)
[eclipse-temurin](https://hub.docker.com/_/eclipse-temurin)
[ibm-semeru-runtimes](https://hub.docker.com/_/ibm-semeru-runtimes)
[ibmjava](https://hub.docker.com/_/ibmjava)
[sapmachine](https://hub.docker.com/_/sapmachine)

**Comment by yosifkit** [comment]
The Alpine images are usually meant to be smaller and often missing tools that are included in the larger images. As for adding packages to the `eclipse-temurin:*-alpine` images, that would be up to the maintainers of the image and should be filed in their repo:

> -	**Where to file issues**:  
>	[GitHub](https://github.com/adoptium/containers/issues); The [adoptium support](https://adoptium.net/support) page has more information on quality, roadmap and support levels for Eclipse Temurin builds. Vulnerabilities not related to Eclipse Temurin itself should be be raised to their respective projects (e.g Ubuntu vulnerabilities need to be raised directly to the Ubuntu project).
>
>\- Docker Hub description (https://github.com/docker-library/docs/tree/6c2877d498fa33a8cc98d6301993a05c35227326/eclipse-temurin#quick-reference-cont)

As for the other openjdk-providing images, only `amazoncorretto` has current Alpine images (and it would be up to them to add any packages):

>-	**Where to file issues**:  
>	[https://github.com/corretto/corretto-docker/issues](https://github.com/corretto/corretto-docker/issues?q=)
>
> \- Docker Hub description (https://github.com/docker-library/docs/tree/6c2877d498fa33a8cc98d6301993a05c35227326/amazoncorretto#quick-reference-cont)

---

Closing since it is up to image maintainers which extra tools/packages to include in their images.
