### ISSUE TITLE
Insights and analytics available for Docker Official Images

### ISSUE THREAD

**Issue by grooverdan** [docker-library/official-images#15306]
Is the [Insights and analytics](https://docs.docker.com/docker-hub/insights-analytics/) features of Docker Hub for [Docker Verified Publisher](https://www.docker.com/partners/programs/) and [Docker-Sponsored Open Source](https://www.docker.com/community/open-source/application/#) collected on Docker Official Images? And can that data be made available (Either raw, API or web pages, public and/or to maintainers)?

**Comment by yosifkit** [comment]
@grooverdan, thanks for reaching out. By default there are no extended metrics made available on the Docker Hub DOI repositories, but you can contact Jeff Hadfield (`jeff.hadfield at docker.com`) to discuss possible options.
