### ISSUE TITLE
Update amazoncorretto with 11.0.20, 17.0.8, 20.0.2 #

### ISSUE THREAD

**Issue by bszeliga** [docker-library/official-images#15337]
See  https://github.com/corretto/corretto-docker/pull/176

**Comment by yosifkit** [comment]
The image maintainers need to provide a [PR](https://github.com/docker-library/official-images/pulls?q=is%3Apr+label%3Alibrary%2Famazoncorretto) like they have before to update the [`library/amazoncorretto` file](https://github.com/docker-library/official-images/blob/master/library/amazoncorretto).  We don't pull updates they haven't given to us.
