### ISSUE TITLE
Missing Elastic Stack images for 8.10.3 8.10.4  and 7.17.14

### ISSUE THREAD

**Issue by alpar-t** [docker-library/official-images#15647]
We had the same issue as reported in https://github.com/docker-library/official-images/issues/15091 the tags for 8.10.3 8.10.4  and 7.17.14 were incorrect. I fixed them now, but we need to make sure that the images for these tags are released. 

@yosifkit would be great if you could help us agin. 

Apologies for the inconvenience, we're taking measure in our processes to make sure it doesn't happen again.

**Comment by LaurentGoderre** [comment]
#15659

**Comment by alpar-t** [comment]
Thanks! I can see 8.0.4 and 7.17.14 are now pushed. Any chance we can get 8.10.3 too ?

**Comment by LaurentGoderre** [comment]
@yosifkit can correct me if im wrong but we don't usually go back in version history and only do the latest.

**Comment by yosifkit** [comment]
Working on getting the backfill `8.10.3` version in. Hopefully we won't need to do this again.
