### ISSUE TITLE
Parameter for pointing to local (parent) maven repo

### ISSUE THREAD

**Issue by juliangamble** [docker-library/official-images#1566]
When building a docker file with 

```
docker build -t my-maven .
```

with even the simplest of maven files (eg `surefire`) the build process freshly downloads all the maven dependencies, ignoring those in the repository on the parent machine. (The one running vagrant - not inside the vagrant machine). 

My question is - how can we pass a parameter to create a link back the maven repository on the parent machine so we don't download the world each time we build a docker image?

**Comment by Moghedrin** [comment]
This isn't really an issue with the official images. The docker documentation lists the best places to get help for things like this [here](https://docs.docker.com/opensource/get-help/)! :)
