### ISSUE TITLE
Elixir/Erlang observer

### ISSUE THREAD

**Issue by bdubaut** [docker-library/official-images#1576]
Erlang and Elixir have something called the *[observer](http://elixir-lang.org/getting-started/mix-otp/supervisor-and-application.html#observer)* that allows to visualise the tree of processes of your app.

If it runs perfectly when you are running Elixir on your own local machine, but if you try to launch it when Elixir runs inside the elixir official image, you get this kind of message:

```
$> docker run -it --rm elixir
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.2.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :observer.start

04:06:43.972 [error] ERROR: Could not find 'wxe_driver.so' in: /usr/local/lib/erlang/lib/wx-1.6/priv

{:error,
 {{:load_driver, 'No driver found'},
  [{:wxe_server, :start, 1, [file: 'wxe_server.erl', line: 65]},
   {:wx, :new, 1, [file: 'wx.erl', line: 115]},
   {:observer_wx, :init, 1, [file: 'observer_wx.erl', line: 96]},
   {:wx_object, :init_it, 6, [file: 'wx_object.erl', line: 337]},
   {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}

```

It would be awesome to be able to do this, especially if you are investigating something on your remote servers.

**Comment by yosifkit** [comment]
I think this issue would be more appropriate in either https://github.com/c0b/docker-elixir/issues or https://github.com/c0b/docker-erlang-otp/issues.

Thanks!
