### ISSUE TITLE
ARM32 image missing for eclipse-temurin:21-jre-jammy

### ISSUE THREAD

**Issue by matthiasfeurer** [docker-library/official-images#15799]
Hey,
eclipse-temurin:21-jre-jammy currently does not have support for ARM32. Is there a plan to include this?

Thanks, Matthias

**Comment by tianon** [comment]
This is probably a better question for https://github.com/adoptium/containers (we don't maintain that image directly; we're more like the publishing channel for it).

**Comment by matthiasfeurer** [comment]
> This is probably a better question for https://github.com/adoptium/containers (we don't maintain that image directly; we're more like the publishing channel for it).

True, thanks for the hint.
