### ISSUE TITLE
Tag pypy 5.0.1

### ISSUE THREAD

**Issue by GaretJax** [docker-library/official-images#1589]
The upstream repo already has a 5.0.1 Dockerfile: https://github.com/docker-library/pypy/blob/master/2/Dockerfile

https://github.com/docker-library/official-images/blob/master/library/pypy needs to be updated.

@tianon can I somehow help out?

**Comment by tianon** [comment]
That update should be pushed up now (https://github.com/docker-library/official-images/pull/1590) -- in the future, if a PR doesn't exist yet you can clone the repo locally and run `./generate-stackbrew-library.sh` to generate the contents necessary for making a PR to `library/pypy` on this repository. :+1:

**Comment by GaretJax** [comment]
Thanks a lot @tianon for both the update and the instructions... will do (I think there will be a new release soonish to fix some bugs ;-) )
