### ISSUE TITLE
Have official images be supported for podman

### ISSUE THREAD

**Issue by trymeouteh** [docker-library/official-images#16066]
Please consider making all of the official images work in podman.

By having each image tested in podman and with instructions on the docker hub image page on the tweaks needed to spin up a container with the image in podman.

**Comment by tianon** [comment]
Sorry, I'm not sure I understand what makes this different from https://github.com/docker-library/official-images/issues/16043?  I can't actually think of any images that _don't_ "support" being run in `podman`, although their usage might be slightly different based on whether you're in rootless mode or not (which was established in https://github.com/docker-library/official-images/issues/16043 to be something that applies to both Docker and Podman, and something that causes many problems for things like file sharing in general, so not something users should enable without understanding the implications of doing so, and definitely not something it'd be appropriate for us to add to the documentation for all images).
