### ISSUE TITLE
New Official JDK and JRE Images using Alpine 3.19

### ISSUE THREAD

**Issue by bantao-kainos** [docker-library/official-images#16080]
The older versions of Alpine have some vulnerabilities.
The latest version of Alpine 3.19 is supposed to not have vulnerabilities ??.
But the official Docker JDK and JRE images are not yet generated with the latest Alpine 3.19 version.
We have a particular need for eclipse-temurin 17 JRE images with Alpine 3.19
What is the eta for the new images to be generated and made available ?

**Comment by tianon** [comment]
per https://hub.docker.com/_/eclipse-temurin: :eyes:

> -	**Where to file issues**:  
> 	[GitHub](https://github.com/adoptium/containers/issues); The [adoptium support](https://adoptium.net/support) page has more information on quality, roadmap and support levels for Eclipse Temurin builds. Vulnerabilities not related to Eclipse Temurin itself should be be raised to their respective projects (e.g Ubuntu vulnerabilities need to be raised directly to the Ubuntu project).

(I think you probably meant to file this over there)

That being said, I don't think "latest version of Alpine 3.19 is supposed to not have vulnerabilities" is completely accurate -- there's a lot of nuance to the situation in general (see also https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves). :heart:
