### ISSUE TITLE
Base image rebuild questions

### ISSUE THREAD

**Issue by powersj** [docker-library/official-images#16164]
Hi,

With the recent glibc CVEs the question came up as to how our Telegraf images get rebuilt with the new base image. It is my understanding that the official images are re-built periodically, but I was curious as to:

* When these rebuilds are triggered?
* How these rebuilds are triggered?
* Can I as a package maintainer force a rebuild?
* Short of launching the image, is there a way to see the last time my image was rebuilt? `docker image inspect telegraf` and looking at `Created`?

Thanks!

**Comment by whalelines** [comment]
1.  The rebuilds are triggered when a new versions of an image's base image is available
2.  These rebuilds are triggered by our build system leveraging bashbrew
3.  Package maintainers cannot force a rebuild, the automated system rebuilds everything as soon as it possibly can
4.  You can find when an image was last updated on Docker Hub, https://hub.docker.com/_/telegraf/tags

**Comment by powersj** [comment]
Thanks for the clarifications!

> You can find when an image was last updated on Docker Hub, https://hub.docker.com/_/telegraf/tags

Is there a way to tell what changed or caused the push? For example, we pushed v1.29.4 yesterday. How can I tell if it was that update or a base image update?

**Comment by smgtkn** [comment]
Hello, thanks for the answer and the question. 
To my understanding, there are 3 reasons why builds for official images occur :

1. Dockerfile update 2. Base update 3. Periodic rebuilds
How often are the 'periodic rebuilds' triggered?

**Comment by tianon** [comment]
Debian and Ubuntu are both rebuilt periodically though (with an approximate cadence of at least once per month, give or take), which leads to your "base update" case for many images.

**Comment by powersj** [comment]
Thanks for the clarifications!
