### ISSUE TITLE
golang:1.22-alpine3.19 amd64

### ISSUE THREAD

**Issue by rez1dent3** [docker-library/official-images#16209]
Hello. I see that the amd64 architecture should be available for the golang:1.22-alpine3.19 image, but it is not.
```
Tags: 1.22.0-alpine3.19, 1.22-alpine3.19, 1-alpine3.19, alpine3.19, 1.22.0-alpine, 1.22-alpine, 1-alpine, alpine
Architectures: amd64, arm32v6, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: 893a2c96ba6154de2ad3663d087998bfda0a04e9
Directory: 1.22/alpine3.19

Tags: 1.22.0-alpine3.18, 1.22-alpine3.18, 1-alpine3.18, alpine3.18
Architectures: amd64, arm32v6, arm32v7, arm64v8, i386, ppc64le, s390x
GitCommit: 893a2c96ba6154de2ad3663d087998bfda0a04e9
Directory: 1.22/alpine3.18
```

https://hub.docker.com/_/golang/tags?page=1&name=1.22-alpine3.19
https://hub.docker.com/_/golang/tags?page=1&name=1.22-alpine3.18

<img width="1286" alt="Screenshot 2024-02-07 at 11 25 47" src="https://github.com/docker-library/official-images/assets/5111255/45888c85-ab1a-48f7-9f0b-d68de2e99e89">
<img width="1291" alt="Screenshot 2024-02-07 at 11 25 55" src="https://github.com/docker-library/official-images/assets/5111255/9c0c5e34-ecbb-4da0-aaa7-78dd3850d132">

**Comment by AlekSi** [comment]
https://github.com/docker-library/golang/issues/509

**Comment by ldez** [comment]
It is because the image is being built https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/golang/

**Comment by Merovius** [comment]
I believe you mean https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/golang/565/console (565, not 564)

**Comment by constantoine** [comment]
Job has finally succeeded. Time to resume working 😆

**Comment by tianon** [comment]
Yep, builds were still in progress.
