### ISSUE TITLE
Apache Solr ARM support is missing for 9.5.0 and 9.5

### ISSUE THREAD

**Issue by ozlerhakan** [docker-library/official-images#16246]
Hi 👋,

There seem to be missing ARM support for solr:9.5.0 https://hub.docker.com/layers/library/solr/9.5.0/images/sha256-68dd584e8e890fa2c2115966a669743b8f5918475e72551ccaecfa6236afcc8b?context=explore&tab=vulnerabilities 

and solr:9.5 https://hub.docker.com/layers/library/solr/9.5/images/sha256-68dd584e8e890fa2c2115966a669743b8f5918475e72551ccaecfa6236afcc8b?context=explore&tab=vulnerabilities

Could you please clarify what could be the problem that ARM doesn't exists on these tags?

Thank you!

**Comment by tianon** [comment]
This should be fixed now -- the builds were probably still in progress at the time you checked (because the release was still pretty fresh).
