### ISSUE TITLE
BusyBox ash MAILPATH HISTFILE

### ISSUE THREAD

**Issue by jasonmader** [docker-library/official-images#1644]
The BusyBox shell in Alpine Linux checks for new mail, but by default it checks for the existance of the file named `MAILPATH` in the current working directory when the environment variable of the same name isn’t set. The shell also saves a history file by default. Both features can be disabled in the ash build for BusyBox, which seems like a good idea for a container OS.

There’s also a file `/etc/profile.d/color_path` that would never be executed by the for loop in `/etc/profile` because the extension is not .sh

```
stat("MAILPATH", 0x7ffe0554bc98)        = -1 ENOENT (No such file or directory)

#if ENABLE_ASH_MAIL
	{ VSTRFIXED|VTEXTFIXED|VUNSET, "MAIL"      , changemail      },
	{ VSTRFIXED|VTEXTFIXED|VUNSET, "MAILPATH"  , changemail      },
#endif

open("/root/.ash_history", O_RDONLY)    = 3

#if ENABLE_FEATURE_EDITING_SAVEHISTORY
	{ VSTRFIXED|VTEXTFIXED|VUNSET, "HISTFILE"  , NULL            },
#endif

```
[ash.c](https://git.busybox.net/busybox/tree/shell/ash.c)

**Comment by yosifkit** [comment]
I don't think that the Alpine image maintainers are watching this repo.  Could you make the issue over there https://github.com/gliderlabs/docker-alpine/issues?
