### ISSUE TITLE
Rust 1.77.2-slim arm64 Images Missing

### ISSUE THREAD

**Issue by bnpfeife** [docker-library/official-images#16581]
My apologies if this is the incorrect place to file this issue. 

I noticed that the arm64 images are missing for `rust:1.77.2-slim-<< codename >>`. It appears that multiple target architectures are [specified](https://github.com/docker-library/official-images/blob/61b66d92c4f88bf0753918660a47c5ed1b4d859a/library/rust#L22) within `library/rust`; however, DockerHub only [shows](https://hub.docker.com/layers/library/rust/1.77.2-slim-bullseye/images/sha256-e3703a692d6689cee0490363bfc8108a9c9e590df6988f2920eb71ab77937c99) amd64 as being available. It also appears that `1.77.1-slim-<< codename >>`, `1.77.0-slim-<< codename >>`, `1.76.0-slim-<< codename >>` all have multi-arch builds available.

Is it possible that I am being impatient and that the other architectures just haven't been pushed yet?

Thanks

**Comment by yosifkit** [comment]
The other architectures are in queue and haven't been built/pushed yet. We also merged [`debian`](https://github.com/docker-library/official-images/pull/16569) yesterday, so it has filled up the queues with rebuilds, making everything take a while.

**Comment by bnpfeife** [comment]
Ah okay, that makes a lot sense. My apologies, I'll close the issue.
