### ISSUE TITLE
An issue with nginx 1.25.5 manifest.

### ISSUE THREAD

**Issue by oxpa** [docker-library/official-images#16625]
Hello,

I'm trying to pull nginx:1.25.5 image from docker.io but get an error:
```
:~$ docker pull docker.io/nginx:1.25.5
1.25.5: Pulling from library/nginx
no matching manifest for linux/amd64 in the manifest list entries
```
At the same time, I can see that the build was successful : https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/nginx/
and the specific image can be pulled with:
```
:~$ docker pull docker.io/amd64/nginx:1.25.5
1.25.5: Pulling from amd64/nginx
13808c22b207: Already exists
c46d32988911: Pull complete
b9d060e68bbc: Pull complete
c028eb95b065: Pull complete
e74ab6743f66: Pull complete
4a666f159bd0: Pull complete
297a65ba6f04: Pull complete
Digest: sha256:9e6b127264e7cd5a52b366323ced6367d4e88f6c4cbd218ba3caf477690d8300
Status: Downloaded newer image for amd64/nginx:1.25.5
docker.io/amd64/nginx:1.25.5
```

Which tells me that the image is in the registry but there may be a problem with a manifest.

Is this something I can fix on my side?

Kind regards,
Oxpa

**Comment by whalelines** [comment]
That image is very recent. It may take a few hours for all os/architecture images to be built and made available.

**Comment by oxpa** [comment]
Fair enough.
Though it usually just doesn't list a new tag in docker.io/library/nginx until it's all built. Or maybe I was just lucky.
Thank you for the update, I'll wait for the issue to resolve itself and close this one.

**Comment by tianon** [comment]
Yep, when the tag canonically is supposed to exist, but there are no builds yet, an empty list is often pushed.  This will almost always only show up for a very short window, but it is normal and expected. :+1:
