### ISSUE TITLE
Broken release: SonarQube 9.9.5 tags do not support the arm64 architecture.

### ISSUE THREAD

**Issue by carminevassallo** [docker-library/official-images#16682]
Dear team,

it looks like something went wrong when merging PR #16668 

As you can see from this screenshot, all the 9.9.5-... tags do not support `arm64` while the other tags published through the same PR support both `amd64` and `arm64`.

Could you please have a look?

![image](https://github.com/docker-library/official-images/assets/23573650/3a923581-5b6b-420d-a9c9-ebe1d01163af)

**Comment by LaurentGoderre** [comment]
Investigating

**Comment by LaurentGoderre** [comment]
The images for arm64 are now available.
