### ISSUE TITLE
missing arm64v8 layers in MariaDB image

### ISSUE THREAD

**Issue by grooverdan** [docker-library/official-images#16885]
There in request;

https://github.com/docker-library/official-images/pull/16872/commits/58eac071498a207cc5fc9e5eea1d38bc197c03c8

And build:

A build: https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/mariadb/lastSuccessfulBuild/console

Just missing on dockerhub:

https://hub.docker.com/_/mariadb/tags

arm64 from #16821 seems to be there correctly.

Closes: https://github.com/MariaDB/mariadb-docker/issues/590

**Comment by LaurentGoderre** [comment]
I believe it's in the queue to be built

**Comment by tianon** [comment]
We had a pretty full pipeline of images to build and some other things that exacerbated it -- the good news is that the `mariadb` image builds are complete, and I believe they're all up now. :+1:

(we're also moving forward on solutions to alleviate the other issues)

**Comment by grooverdan** [comment]
Thank you.
