### ISSUE TITLE
can't update to 8.2.1

### ISSUE THREAD

**Issue by Lennard132** [docker-library/official-images#1701]
When i try to update my owncloud it always fails so what can i do??

**Comment by yosifkit** [comment]
I think this would be better tracked on the [`owncloud` image repo](https://github.com/docker-library/owncloud). What steps are you doing to upgrade? From what version are you upgrading? Are you following the steps on https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html?
