### ISSUE TITLE
Introduce `riscv64` tag for Ubuntu:24.04

### ISSUE THREAD

**Issue by TimePrinciple** [docker-library/official-images#17213]
I noticed there are `.manifest` and tarball for `riscv64` as recorded [here](https://git.launchpad.net/cloud-images/+oci/ubuntu-base/commit/?h=noble-24.04&id=2715bdd4428bf8e95f20dc384f89f5e5c1e6ab37), what is preventing Ubuntu:24.04 from riscv64 platform?

I wonder the viability of introducing `riscv64` tag for Ubuntu:24.04, and if it is viable, what works are required to push this through, much appreciated.

**Comment by tianon** [comment]
Quoting relevant bits of https://hub.docker.com/_/ubuntu:

> -	**Maintained by**:  
> 	[Canonical](https://launchpad.net/cloud-images)
> 
> ...
> 
> -	**Where to file issues**:  
> 	[the cloud-images bug tracker](https://bugs.launchpad.net/cloud-images) (include the `docker` tag)

**Comment by cjdcordeiro** [comment]
UPDATE: these are now available
