### ISSUE TITLE
Rabbitmq update PR not created

### ISSUE THREAD

**Issue by guoard** [docker-library/official-images#17219]
Hi,

Based on the [Docker image lifecycle](https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what), the next step after this [pull request](https://github.com/docker-library/rabbitmq/commit/8f0c1fd9bafcdb016bad4d1a18e9747460131867) hasn't happened. Is there an issue or will it be done later?

**Comment by LaurentGoderre** [comment]
This will be addressed by https://github.com/docker-library/official-images/pull/17222

**Comment by guoard** [comment]
@LaurentGoderre Thanks for your response.
I have a follow-up question: Is the PR process usually automatic, but you handled it manually this time due to an issue? Or does it always need to be done manually? If it's the latter, can a non-maintainer user perform this task?

**Comment by LaurentGoderre** [comment]
@guoard while the creation of the commit is automated, the PRs are still created manually (see previous change to RabbitMQ https://github.com/docker-library/official-images/pull/17205)
