### ISSUE TITLE
Running tests on Darwin

### ISSUE THREAD

**Issue by ceasbz** [docker-library/official-images#1766]
I will trying to run tests on Darwin and no success.

``` bash
readlink: illegal option -- f
usage: readlink [-n] [file ...]
../official-images/test/run.sh: line 25: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

There is a possibility of having this support?

**Comment by tianon** [comment]
There is now [a `Dockerfile` in the root of this repository](https://github.com/docker-library/official-images/blob/b0298d14fada06f5b0addea8ad6c9ac4ab627373/Dockerfile) which [we use](https://github.com/docker-library/official-images/blob/b0298d14fada06f5b0addea8ad6c9ac4ab627373/test-pr.sh#L37) for running the tests in a platform-independent way.  I'd recommend using that for running the tests on OS X. :+1:
