### ISSUE TITLE
Recent change in the ppc64le/ubuntu:noble image

### ISSUE THREAD

**Issue by radarhere** [docker-library/official-images#17833]
Running the ppc64le/ubuntu:noble image on GitHub Actions using aptman/qus, something has changed recently.

To demonstrate, I've put together a simple action, showing that an earlier copy of the image can be pulled, but the latest cannot - https://github.com/radarhere/docker-image-demo/blob/main/.github/workflows/test.yml
```
docker run --rm --privileged aptman/qus -s -- -p ppc64le
docker pull ppc64le/ubuntu:noble-20241009
echo "Debug: ppc64le/ubuntu:noble-20241009 succeeded, but ppc64le/ubuntu:noble will fail"
docker pull ppc64le/ubuntu:noble
```
The result - https://github.com/radarhere/docker-image-demo/actions/runs/11641856836/job/32420818180 - reports that the last command fails with
> no matching manifest for linux/amd64 in the manifest list entries

This also occurs for arm64v8/ubuntu:jammy and s390x/ubuntu:noble, if that is helpful.

So, any idea what has changed recently in the image that has led to this? Is there something in my code that should be updated?

Thanks for your time.

**Comment by tianon** [comment]
It's now an image index, and includes an SBOM, as can be seen while browsing the underlying image data at https://oci.dag.dev/?image=ppc64le/ubuntu:noble

The simplest fix is to include `--platform linux/ppc64le` (which is valid and good for the previous images too).

**Comment by radarhere** [comment]
That works, thanks very much!
