### ISSUE TITLE
when  centos will been taken offline from website ?

### ISSUE THREAD

**Issue by shalk** [docker-library/official-images#17901]
I found `centos` folder have been deleted  https://github.com/docker-library/official-images/pull/17276

But  `https://hub.docker.com/_/centos` web page  is still exist . will hub.docker.com/_/centos  be delete ? and docker pull centos:xxx will fail ?

**Comment by LaurentGoderre** [comment]
CentOS is deprecated and will not be getting more updates. However, the images remain on Hub.
