### ISSUE TITLE
apt update fails in ubuntu:23.10 image 

### ISSUE THREAD

**Issue by kavinask007** [docker-library/official-images#17973]
steps to replicate
* `docker run -it ubuntu:23.10`
* apt update
apt update fails with the message "The repository  'http://archive.ubuntu.com/ubuntu mantic Release' doesnot have a release file"

**Comment by LaurentGoderre** [comment]
Ubuntu 23 is EOL since June. https://wiki.ubuntu.com/Releases You probably need to go to an LTS (22 or 24)
