### ISSUE TITLE
the busybox:glibc image needs to include pthread too

### ISSUE THREAD

**Issue by gdamjan** [docker-library/official-images#1807]
… at least, so that random binaries work in it. only libc is mostly useless.

**Comment by puellanivis** [comment]
https://github.com/docker-library/busybox/pull/12

**Comment by tianon** [comment]
This would be more appropriately filed over at https://github.com/docker-library/busybox.  Since there's a PR open now, I'm going to close this and comment over there instead.  Thanks!
