### ISSUE TITLE
Pulling new version 24.7 failed manifest not found

### ISSUE THREAD

**Issue by omer2500** [docker-library/official-images#18105]
Hi,

when running the command below it gives me the following error
it seems it happens only on version 24.7.0 no matter which tags I use (27.3 works),
I managed to reproduce this on my local machine and with pods on a cluster that uses those images

```
docker pull docker:27.4.0-dind                      
27.4.0-dind: Pulling from library/docker
manifest for docker:27.4.0-dind not found: manifest unknown: manifest unknown
```

is this an issue on my end? or is there a real problem?

Thanks

**Comment by marcosabreu-hotmart** [comment]
I also have this problem with this image

**Comment by rhassanein** [comment]
Seeing an increase in similar errors since `Dec 14 - 06:15 UTC`.

```

Failed to pull image with policy "always": manifest for docker:latest not found: manifest unknown: manifest unknown (manager.go:251:2s)

Job failed: failed to pull image "docker:latest" with specified policies [always]: manifest for docker:latest not found: manifest unknown: manifest unknown (manager.go:251:2s)

Failed to pull image with policy "always": manifest for docker:27.4.0-cli not found: manifest unknown: manifest unknown (manager.go:251:2s)

Job failed: failed to pull image "docker:27.4.0-cli" with specified policies [always]: manifest for docker:27.4.0-cli not found: manifest unknown: manifest unknown (manager.go:251:2s)
```

ref: https://gitlab.com/gitlab-com/gl-infra/production/-/issues/19002#note_2259641160

**Comment by omer2500** [comment]
For anyone who encountered this,
workaround is just using the 27.3.0 tag version

```
docker pull docker:27.3.0-dind
```

**Comment by LaurentGoderre** [comment]
See https://github.com/docker-library/docker/issues/519#issuecomment-2543184153
