### ISSUE TITLE
insecure-registry not registering when docker start

### ISSUE THREAD

**Issue by EwanSadie** [docker-library/official-images#1873]
Had this issue on a few Ubuntu machines.  Some of them was upgraded from 1.6 to 1.11.2
On the machines that was upgraded the $DOCKER_OPTS option was not in the docker.services at all.

I ran the following commands to "fix" it.

sudo service docker stop
sudo nano /lib/systemd/system/docker.service

Replace line
ExecStart=/usr/bin/docker daemon -H fd:// $DOCKER_OPTS
with
ExecStart=/usr/bin/docker daemon --insecure-registry <REGISTRY HOST>:5000

systemctl daemon-reload
sudo service docker start

**Comment by tianon** [comment]
I'm not sure this is filed in the right place (this repo is for collaborating on the official images in general).  Given that it's a usability issue with Docker, it's probably a more appropriate query for the `#docker` IRC channel on Freenode or the [Docker Forums](https://forums.docker.com/).  Thanks!
