### ISSUE TITLE
ubuntu:lucid apt repo was moved to old-releases

### ISSUE THREAD

**Issue by chriskuehl** [docker-library/official-images#1902]
We use the `ubuntu:lucid` image quite a bit to test our code against really old versions of Ubuntu. Unfortunately Ubuntu finally moved the lucid archives from `archive.ubuntu.com` to `old-releases.ubuntu.com`. Now a lot of builds are failing because they can't download packages.

We'd like to make the following change to the base image:

``` diff
--- /etc/apt/sources.list.orig  2016-06-29 17:20:04.484815161 +0000
+++ /etc/apt/sources.list       2016-06-29 17:20:26.495986636 +0000
@@ -1,3 +1,3 @@
-deb http://archive.ubuntu.com/ubuntu lucid main universe
-deb http://archive.ubuntu.com/ubuntu lucid-updates main universe
-deb http://archive.ubuntu.com/ubuntu lucid-security main universe
+deb http://old-releases.ubuntu.com/ubuntu lucid main universe
+deb http://old-releases.ubuntu.com/ubuntu lucid-updates main universe
+deb http://old-releases.ubuntu.com/ubuntu lucid-security main universe
```

I can't find the `ubuntu:lucid` image anywhere in order to make a pull request, though. It was suggested on `#docker` that it may have been archived but never deleted. Is there any chance of updating this image?

(I know it's super EOL, but I think there's a lot of value in having Docker images for old releases, since Docker is by far the easiest way to test code against these legacy systems.)

**Comment by tianon** [comment]
Interesting idea -- we (@paultag and I) created [the `debian/eol` image](https://hub.docker.com/r/debian/eol/) for Debian as a technical curiousity to see if it were easily feasible (and how far we could take it), and I think it has historical value to do so.

That being said, I talked to Canonical about this and they're not interested in providing or supporting this officially (which is understandable), although it's certainly possible to do with a bit of `debootstrap` footwork.

So, uh, TL;DR, this isn't going to happen as part of official images, or as an official Canonical/Ubuntu project, but it's technically possible, and I'm willing to help answer questions or provide further pointers for someone who's attempting it and running into trouble. :smile:

**Comment by tshepang** [comment]
A simple workaround is this line in Dockerfile:

    RUN sed -i 's/archive/old-releases/' /etc/apt/sources.list
