### ISSUE TITLE
Gitlab and discourse

### ISSUE THREAD

**Issue by pierreozoux** [docker-library/official-images#1944]
I think it would be amazing to have Gitlab and discourse official images, but apparently, [the](https://meta.discourse.org/t/can-discourse-ship-frequent-docker-images-that-do-not-need-to-be-bootstrapped/33205/66) [maintainers](https://github.com/docker-library/official-images/issues/718) are reluctant to this.

Can I offer to PR if I offer to maintain it? I can see that ownCloud is maitained by docker it self, and ownCloud never agreed, so why not having discourse and gitlab official images?

Let me know what you think?

**Comment by tianon** [comment]
ownCloud was added before we started asking for upstream approval or support, and it backfired in several cases (hence our change in stance).  Also note cases like `elasticsearch`, etc where we're actively deprecating the official images in favor of upstream's images instead.
