### ISSUE TITLE
postgres delayed startup in downstream images.

### ISSUE THREAD

**Issue by mmmmmrob** [docker-library/official-images#1951]
Hi,

I'm planning to swap over from the official postgres image to mdillon/postgis to start working with postgis features in a site I'm building. mdillon/postgis is a downstream image of the official postgres image.

We use docker in circleci for continuous build and test, and then docker cloud for continuous deployment. This works well with postgres but not with postgis. We have (in essence) three containers: web, test and db. Web has a link to db; test has a link to web.

The postgres docker container starts postgres almost immediately and is ready to receive connections. The postgis image takes a lot longer to ready the postgis extension and start accepting connections. There maybe be other downstream images that delay the startup of postgres too, I guess.

docker recently introduced HEALTHCHECK to allow a container to say when it was ready to receive requests, and to continue to provide a status once running. (https://docs.docker.com/engine/reference/builder/#/healthcheck)

Are there any plans for postgres to implement HEALTHCHECK?

**Comment by tmaier** [comment]
Hi, please check out https://github.com/docker-library/healthcheck/tree/master/postgres and https://hub.docker.com/r/healthcheck/postgres/ for an initial implementation

**Comment by tianon** [comment]
See also https://github.com/docker-library/cassandra/pull/76#issuecomment-246054271 for more concrete thoughts on adding them by default. :+1:
