### ISSUE TITLE
Using bashbrew for private repo

### ISSUE THREAD

**Issue by iceandroidph** [docker-library/official-images#1955]
I tried forking the project and was attempting to keep a private official-images and use the bashbrew to build all. But it seems the go code only works with the official repo. 

Is there quick way to point it to a fork repo?

**Comment by tianon** [comment]
The code itself doesn't really care what it's building -- you just need to set `--library` or `BASHBREW_LIBRARY` to the path on your local system where you've put the manifest files.

Alternatively, if you provide bashbrew with an explicit file path, it'll use that, including if it's a remote URL, for example:
```console
$ bashbrew build ./some-file
$ bashbrew build http://example.com/some-file
$ bashbrew build https://github.com/john/doe/raw/master/library/some-file
```

**Comment by iceandroidph** [comment]
Thanks that worked.

**Comment by yosifkit** [comment]
You can set it in the config file too. :tada: 
```console
$ cat ~/.config/bashbrew/flags
Library: /home/sauron/official-images/library
```
