### ISSUE TITLE
traefik v1.0.1 not published

### ISSUE THREAD

**Issue by emilevauge** [docker-library/official-images#1961]
Hi!

It seems there is an issue with image builds.
The PR https://github.com/docker-library/official-images/pull/1957 has been merged 3 hours ago and the tag v1.0.1 is still not available:
```
docker pull traefik:v1.0.1 
Pulling repository docker.io/library/traefik
Tag v1.0.1 not found in repository docker.io/library/traefik
```

/cc @vdemeester

**Comment by tianon** [comment]
It appears to be up now (https://hub.docker.com/r/library/traefik/tags/). :cry:

We had it built and pushed fairly quickly after the PR was merged, but there was a hiccup in the signing process (we're told it had a large backlog) so it didn't become available until very recently (roughly an hour ago).  Sorry about that! :disappointed:

**Comment by emilevauge** [comment]
OK thanks :)
