### ISSUE TITLE
[Suggestion] No easy language support?

### ISSUE THREAD

**Issue by BeyondLimitation** [docker-library/official-images#1964]
I connected docker mysql container database and create new tables.
And i tried to input Korean in my test table.

But there is a problem. The error message has been returned.
it says
`Error Code: 1366. Incorrect string value: '\xED\x99\x8D\xEA\xB8\xB8...' for column 'name' at row 1
`
This means that i need Korean package+font.
Now i have to figure out how to set locales and this is hard...

So my suggestion is easy locale setting.

**Comment by Moghedrin** [comment]
This isn't an issue with docker or the images, as far as I can tell. There's a [MySQL](https://bugs.mysql.com/bug.php?id=30131) bug report on exactly this behavior.
