### ISSUE TITLE
ubuntu 15.10 image has a core dump inside it

### ISSUE THREAD

**Issue by justincormack** [docker-library/official-images#1978]
```
docker run -it ubuntu:15.10 ls -la /core
-rw------- 1 root root 393216 Jul 18 17:35 /core
```

Looking at it, it is a core dump from aufs utils:

```
file /core
/core: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from 'auplink /mnt/scratch/var-lib-docker/aufs/mnt/a2f242537c4c95d61dd55f423758e8cfef'
```

**Comment by justincormack** [comment]
So does 16.04.

**Comment by tianon** [comment]
Indeed :cry:

See https://github.com/tianon/docker-brew-ubuntu-core/issues/55 for further discussion -- `auplink` from Debian is segfaulting, and for some reason decides that the appropriate behavior in the face of that is to drop a core dump in our image filesystem. :disappointed:

**Comment by yosifkit** [comment]
This is fixed.
