### ISSUE TITLE
haproxy 1.6.7 has not yet been pushed

### ISSUE THREAD

**Issue by jmkgreen** [docker-library/official-images#1982]
https://hub.docker.com/_/haproxy/ lists 1.6.7 but the tags page doesn't feature it and I cannot pull it (doesn't exist).

**Comment by yosifkit** [comment]
Looks like this might be remnants of https://github.com/docker-library/official-images/issues/1961.  I pushed them up again, so hopefully the signing process goes through this time.

**Comment by jmkgreen** [comment]
```
jamesg@virt-04:~$ docker pull haproxy:1.6.7
1.6.7: Pulling from library/haproxy
Digest: sha256:40a365d43a38d4ce3a957fec95eef8a3b8233a5968aed825afcb98ed872c14b0
Status: Image is up to date for haproxy:1.6.7
```
Closing.
