### ISSUE TITLE
The docker tags for php 7.0.9 are not pushed

### ISSUE THREAD

**Issue by keksa** [docker-library/official-images#1997]
The PR for php 7.0.9 (#1974) was merged, but docker image tags were not pushed https://hub.docker.com/r/library/php/tags/

**Comment by yosifkit** [comment]
We also merged an updated Debian base in https://github.com/docker-library/official-images/pull/1988, so the server is still busy rebuilding all the images from Debian including php.  We felt it was better to let php wait for the updated debian base rather than push it twice.

**Comment by yosifkit** [comment]
Closing, we even have `7.0.10` tags now!
