### ISSUE TITLE
standard dump for databases images

### ISSUE THREAD

**Issue by pierreozoux** [docker-library/official-images#2002]
What do you think about providing a standard dump procedure in a Label for major databases images?
Just as a kind of manual, then people are free to use it or not or tune it to their taste.

for instance, we could add this line to mysql image:

```
LABEL dump="mysqldump --skip-lock-tables --single-transaction --all-databases --events -uroot -p$MYSQL_ROOT_PASSWORD' | gzip -9 > /dumps/dump.sql.gz"
```

**Comment by yosifkit** [comment]
I think it would be better to just put it in the documentation.

**Comment by tianon** [comment]
Agreed -- I think this is an odd use of labels, and won't necessarily be something we can write generally, especially with regards to permissions, so is better off going into the documentation. :+1:
