### ISSUE TITLE
From no longer working?

### ISSUE THREAD

**Issue by Samistine** [docker-library/official-images#2003]
I can't seem to get my dockerfile to work. Nothing happens.
https://hub.docker.com/r/samistine/jenkins-master/

**Comment by Samistine** [comment]
![image](https://cloud.githubusercontent.com/assets/7032358/17273719/7a5c1c5a-568d-11e6-9278-d11a4b177b55.png)

**Comment by yosifkit** [comment]
You may want to report this on the specific jenkins repo: https://github.com/jenkinsci/docker/issues.  This repo is for the official images in general and whether or not they exist on the Docker Hub.
