### ISSUE TITLE
haproxy 1.6.7-alpine not found

### ISSUE THREAD

**Issue by winggundamth** [docker-library/official-images#2019]
I'm trying to pull haproxy with 1.6.7-alpine but it said it not found

```bash
$ docker pull haproxy:1.6.7-alpine
Pulling repository docker.io/library/haproxy
Tag 1.6.7-alpine not found in repository docker.io/library/haproxy
```

**Comment by yosifkit** [comment]
Thanks for letting us know. It was built and pushed to the Docker Hub with https://github.com/docker-library/official-images/pull/1942, but it looks like it was lost in the signing process.  I pushed it up again so it should be up shortly.
