### ISSUE TITLE
Unable to build docker images

### ISSUE THREAD

**Issue by thanigaa** [docker-library/official-images#2028]
I tried running the following commands to build docker images, get these errors after cloning,
git clone https://github.com/docker-library/official-images.git mylocalrepo

```console
root@Megatron:~/mylocalrepo (master)# docker build .
Sending build context to Docker daemon 1.693 MB
Step 1 : FROM docker:1.10-git
1.10-git: Pulling from library/docker
e110a4a17941: Pull complete 
49e2842bdfdf: Pull complete 
26e60b21b458: Pull complete 
ec51c463b774: Pull complete 
d106bc5d437f: Pull complete 
Digest: sha256:97eacdd4c79a1e329c75b0a461f47cc28095a5ce3867169709d8008cf150471e
Status: Downloaded newer image for docker:1.10-git
 ---> df8adc85261e
Step 2 : RUN sed -ri -e 'p; s!^!@edge !; s!v[0-9.]+!edge!' /etc/apk/repositories
 ---> Running in 5c472c1e9283
 ---> d284403c05e5
Removing intermediate container 5c472c1e9283
Step 3 : RUN apk add --no-cache 		bash 		go@edge
 ---> Running in 47d80266b074
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
WARNING: The repository tag for world dependency 'go@edge' does not exist
ERROR: Not committing changes due to missing repository tags. Use --force to override.
The command '/bin/sh -c apk add --no-cache 		bash 		go@edge' returned a non-zero code: 255
root@Megatron:~/mylocalrepo (master)#
```

Can u let me know what am missing to build the docker image?

**Comment by tianon** [comment]
Those `temporary error` lines make me wonder if you're just seeing an issue with firewall/network configuration.

**Comment by thanigaa** [comment]
I tried with a simple docker image build with the following dockerfile,
FROM ubuntu:14.04
RUN  apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*

root@Megatron:~/install# docker build -t anu/simpleimage:v1 .
Sending build context to Docker daemon 200.5 MB
Step 1 : FROM ubuntu:14.04
 ---> 0ccb13bf1954
Step 2 : RUN apt-get update   && apt-get install -y wget   && rm -rf /var/lib/apt/lists/*
 ---> Running in 17d3af865f7f
Err http://archive.ubuntu.com trusty InRelease
Err http://archive.ubuntu.com trusty-updates InRelease
Err http://archive.ubuntu.com trusty-security InRelease
Err http://archive.ubuntu.com trusty Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-updates Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-security Release.gpg
  Could not resolve 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease  
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease  
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/InRelease  
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Could not resolve 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Could not resolve 'archive.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package wget
The command '/bin/sh -c apt-get update   && apt-get install -y wget   && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
root@Megatron:~/install# 

I tried setting the http_proxy and https_proxy, this not fixing the issue. 

root@Megatron:~/install# docker build -t anu/simpleimage:v1 .
Sending build context to Docker daemon 200.5 MB
Step 1 : FROM ubuntu:14.04
 ---> 0ccb13bf1954
Step 2 : RUN http_proxy='http://<snipped>:8080' https_proxy='http://<snipped>:8080'
 ---> Running in 265542c2a20c
 ---> 6ed2ce852f5a
Removing intermediate container 265542c2a20c
Step 3 : RUN apt-get -y update   && apt-get install -y wget   && rm -rf /var/lib/apt/lists/*
 ---> Running in d6f7ad9e0d37
Err http://archive.ubuntu.com trusty InRelease
  
Err http://archive.ubuntu.com trusty-updates InRelease
  
Err http://archive.ubuntu.com trusty-security InRelease
  
Err http://archive.ubuntu.com trusty Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-updates Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-security Release.gpg
  Could not resolve 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package wget
The command '/bin/sh -c apt-get -y update   && apt-get install -y wget   && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
root@Megatron:~/install# 

Any clue?

**Comment by tianon** [comment]
`Could not resolve 'archive.ubuntu.com'` definitely lends credence to the firewall/network theory.  Your questions/debugging are going to be more appropriately directed to the [Docker Forums](https://forums.docker.com) or the `#docker` IRC channel on Freenode (since they're not an issue specific to https://github.com/docker-library/official-images).

Regarding setting `http_proxy` and/or `https_proxy`, those need to be set with `ENV` (not `RUN`), or passed via `--build-arg` to `docker build`, ie, `docker build --build-arg http_proxy='...' -t ...`
