### ISSUE TITLE
Provide jetty image

### ISSUE THREAD

**Issue by proppy** [docker-library/official-images#203]
I'd be nice to have a jetty image based on the `_/java` one.

It would have to expose tags with different combination of debian/java/jetty version, and default `:latest` to the sable combinaison (if any) of all 3.

Example:
````
jetty:8-java6-wheezy
jetty:8-java6-jessie
jetty:9-java7-jessie
jetty:9-java8-experimental
```

I'm not sure if a `:onbuild` version would make sense, given that:
- the build usually happens outside of docker
- deps are assembled outside of docker by maven and go
- the entrypoint would be fixed to jetty

/cc @ludoch @ndeloof

**Comment by md5** [comment]
FYI, I took the liberty of starting to work on a Jetty image on the model of the [`tomcat`](https://github.com/docker-library/tomcat) image this evening. My first pass is here: https://github.com/md5/docker-jetty

**Comment by md5** [comment]
I also put up an image on the Docker Hub here: https://registry.hub.docker.com/u/mdillon/jetty

The supported tags are: `7-jre7`, `7-jre8`, `8-jre7`, `8-jre8`, `9-jre7` (aka `latest`), and `9-jre8` (per http://download.eclipse.org/jetty/).

**Comment by md5** [comment]
Docs here: https://github.com/md5/docker-library-docs/tree/add-jetty/jetty

**Comment by tianon** [comment]
> ```bash
> url='git://github.com/docker-library/jetty'
> 
> echo '# maintainer: InfoSiftr <github@infosiftr.com> (@infosiftr)'
> echo '# maintainer: Mike Dillon <mike@embody.org> (@md5)'
> ```

If it means we finally get the elusive @md5 to agree to be an official image maintainer, I'm definitely willing to let this one in the list of images we maintain!

I've not dug in deep, but it's looking pretty reasonable so far. :+1:

Are you sure you don't want to just keep it for yourself and not even involve us at the image level? :smile:
```bash
url='git://github.com/md5/docker-jetty'

echo '# maintainer: Mike Dillon <mike@embody.org> (@md5)'
```

**Comment by md5** [comment]
I can switch it over to `md5/docker-jetty`. I was mainly just unclear if there were CLAs or anything involved with Docker. I suppose I should have a better idea of how this works after watching it for a few weeks.

**Comment by md5** [comment]
Updated https://github.com/md5/docker-jetty/commit/1fc8fda35f83297f016b3a38e7a6937a9b1f290d

**Comment by md5** [comment]
Could you guys answer my implied question about the CLA? Does Docker, Inc need to have the copyright on official images or is that just an artifact of @infosiftr's agreement with @docker? I'll update the copyrights from "Docker, Inc" to myself if there is not a requirement to assign to Docker, Inc.

**Comment by yosifkit** [comment]
@md5, no requirement on copyright to Docker, just expectation of reasonable updates and bug fixes.  So yes it is just an artifact of our own agreement with Docker.

[Official repos docs](http://docs.docker.com/docker-hub/official_repos/); [specifically license info](http://docs.docker.com/docker-hub/official_repos/#license)

**Comment by md5** [comment]
I signed up for the `jetty-announce` list. Assuming I'm not being naive about the type of workload this image will entail, I think I can handle taking care of updates and bug fixes in a timely fashion too.

I'll review those docs and look at creating a PR to pull `jetty` into the official images.

**Comment by yosifkit** [comment]
Awesome, thanks @md5.  I am sure @tianon will pipe in if I forgot something.
