### ISSUE TITLE
node alpine images

### ISSUE THREAD

**Issue by jfrazelle** [docker-library/official-images#2133]
Sup yo :)

I use https://github.com/mhart/alpine-node/ all the time for node alpine images, can it be official?? 

ping @mhart

**Comment by tianon** [comment]
This is more appropriately filed over on https://github.com/nodejs/docker-node, although I think the discussion over in https://github.com/nodejs/docker-node/issues/46 is what you're looking for specifically. :smile: :+1:

**Comment by jfrazelle** [comment]
oooo I was like I can't possibly be the first one hahahaha (searched the wrong repo problems)
