### ISSUE TITLE
Limit Memory Consumption

### ISSUE THREAD

**Issue by gsugambit** [docker-library/official-images#2154]
I can run tons and tons of services on my machine, however, when I start a ES in docker my connection almost always freezes/acts sluggish for 5-10 minutes. Is there a property I could put in my docker compose to limit ES? Do others have this issue? My docker compose has about 14 services (sqls/mongos/java microservices / and ES). I do not see these issues until I run ES

**Comment by gsugambit** [comment]
I'm also running with 8GB / 8 cores on my ubuntu VM running ES

**Comment by yosifkit** [comment]
Have you tried setting Java memory limits or `ES_HEAP_SIZE` as is the elasticsearch [docs](https://www.elastic.co/guide/en/elasticsearch/guide/current/heap-sizing.html)?  It says the default is `1g`, so I am not sure `ES_HEAP_SIZE` will change it

```console
$ docker run -d -e ES_JAVA_OPTS="-Xms1g -Xmx1g" elasticsearch
$ # you could also force a limit through docker that will kill it if it gets too high
$ docker run -d -e ES_JAVA_OPTS="-Xms1g -Xmx1g" -m 1500m elasticsearch
```

**Comment by gsugambit** [comment]
I will try this monday. Thanks!

**Comment by tianon** [comment]
Looks like this is an older issue, so I'm going to close it.  In the future, image specific issues should be filed on the individual image repos (in this case, https://github.com/docker-library/elasticsearch). :+1:
