### ISSUE TITLE
Update elasticsearch, logstash, kibana to latest 5.0-beta1

### ISSUE THREAD

**Issue by agonzalezm** [docker-library/official-images#2188]
Could you update images to latest 5.0-beta1 released last week?

**Comment by yosifkit** [comment]
Their new apt repo is not ready.  See also https://github.com/docker-library/kibana/pull/55 and https://github.com/docker-library/elasticsearch/issues/120

**Comment by tianon** [comment]
Closing in favor of the image-specific issues (since this isn't an issue with the official images in general, and is specific to the `elasticsearch`, `kibana`, and `logstash` images and is more appropriately filed/handled there). :+1:
