### ISSUE TITLE
Neo4j appears ready before it is actually ready when using NEO4J_AUTH

### ISSUE THREAD

**Issue by DeltaWhy** [docker-library/official-images#2196]
When `NEO4J_AUTH` is set to a valid value, the entrypoint script brings the server up to change the password, then stops it before bringing it up again with the final configuration. This breaks scripts that wait for a container to be ready by waiting for a successful TCP or HTTP connection, as the Neo4j container will appear ready and then go down.

https://github.com/neo4j/docker-neo4j-publish/blob/22114d5022d6bd414fc7d34046b7a5f9cfdc930c/3.0.6/community/docker-entrypoint.sh#L41
https://github.com/neo4j/neo4j/issues/7203#issuecomment-249927073

**Comment by tianon** [comment]
This would be more appropriately flied over at https://github.com/neo4j/docker-neo4j/issues -- the maintainers of the `neo4j` image won't necessarily see the problem if it's filed here. :+1:
