### ISSUE TITLE
Oracle Linux tags are not consistent

### ISSUE THREAD

**Issue by Djelibeybi** [docker-library/official-images#2225]
We pushed a change to address the OpenSSL issues, but our tags are no longer consistent (as per the library manifest). Tested by clearing all the images from a box and running `docker pull --all oraclelinux`

The tags `latest`, `7` and `7.2` all point to the same image, but I'm getting different IDs:

```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
oraclelinux         7.2                 3d62999fc909        7 days ago          219.5 MB
oraclelinux         latest              3d62999fc909        7 days ago          219.5 MB
oraclelinux         7                   1988eb5b3fc6        11 weeks ago        278.2 MB
```

The `7.2` and `latest` tags point to the correct (updated) image, while the `7` tag was not updated.

The same thing happened with the `6.8` and `6` tag:

```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
oraclelinux         6.8                 7187d444f0ce        7 days ago          223.1 MB
oraclelinux         6                   175adfa05e40        11 weeks ago        223.1 MB
```

The `6.8` tag was updated but the `6` tag was not. 

Is there a way to trigger a retag/rebuild/push or whatever is required to get the tags back in sync?

**Comment by Djelibeybi** [comment]
Ping @tianon and @yosifkit.

**Comment by tianon** [comment]
Not sure what happened, but I've just fired off a re-push (in progress now). :+1:

**Comment by tianon** [comment]
The tags you've mentioned are now re-pushed to the staging location, and should be re-signed and pushed to `library/` soon-ish.  I'll let you verify and close the issue if/when those actually go up. :heart:

**Comment by Djelibeybi** [comment]
This appears to be fixed now. Thanks @tianon for the quick turnaround.
