### ISSUE TITLE
Add VMware Lightwave as official image

### ISSUE THREAD

**Issue by aizurov-vmw** [docker-library/official-images#2237]
+ @snambakam

Hi there, can we do a pull of #2236 

This is adding an image for VMWare Lightwave.

Thanks,
Andrei

**Comment by tianon** [comment]
Not sure why you've opened an issue on top of the three pull requests you've already opened, but the single open pull request is sufficient for tracking this submission here.  Thanks! :+1:

**Comment by aizurov-vmw** [comment]
My mistake. I wasn't sure if an open issue was needed to track the pull request.

Hopefully everything else is closed up now.

Thanks again!
