### ISSUE TITLE
bashbrew label support

### ISSUE THREAD

**Issue by ehaselwanter** [docker-library/official-images#2294]
how do you think about supporting labels in bashbrew? 

I really like the overall approach and consider to use this workflow for inhouse images, but therefore I would really like to see the support for labels which in my opinion need support for some way to get the information into the Dockerfile. 

I do not so any other way to get a label with the build time in the Dockerfile (or is there a way I just not see?)

Use case: be able to support build date label:

```
BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` .
```

and in the Dockerfile:

```
LABEL org.label-schema.build-date=$BUILD_DATE
```

with

```
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` .
```

**Comment by Moghedrin** [comment]
This information is usually stored in the image, and should be able to be viewed via `docker inspect`. Something like the following should get you a timestamp:

```
$ docker inspect -f '{{.Created}}' [IMAGE]
2014-10-08T19:47:34.61103358Z
```

**Comment by tianon** [comment]
Closing old issue (which appears resolved) :heart:
