### ISSUE TITLE
PHP 7.1 RC6

### ISSUE THREAD

**Issue by lougreenwood** [docker-library/official-images#2340]
The Docker PHP image for PHP 7.1 RC 6 releases isn't yet live (released upstream 4 days ago), in the past these seemed to be released on Docker Hub pretty quickly, so just a friendly nudge for this.

RC6 is the planned final RC release for PHP 7.1 (http://php.net/archive/2016.php#id2016-11-10-2), so it would be good to get this soon so more people can do final tests and prepare for the 7.1 release.

Thanks :)

**Comment by tianon** [comment]
See also https://github.com/docker-library/php/blob/7d058f79e6fdf7b8e97d5004d1098c436d348a47/README.md, especially the following bit:

> See a change merged here that doesn't show up on the Docker Hub yet? Check [the "library/php" manifest file in the docker-library/official-images repo](https://github.com/docker-library/official-images/blob/master/library/php), especially [PRs with the "library/php" label on that repo](https://github.com/docker-library/official-images/labels/library%2Fphp). For more information about the official images process, see the [docker-library/official-images readme](https://github.com/docker-library/official-images/blob/master/README.md).

That being said, I'll see that we make a new update PR later today. :+1:

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/2344 :+1:
