### ISSUE TITLE
NoneType' object has no attribute 'get_n_sub_types'

### ISSUE THREAD

**Issue by SK301127** [docker-library/official-images#2362]
Running the latest cassandra from docker hub.
Table has a used defined type column which in turn contains a column which is a set of another user defined type.

Table
- column A, datatype text
- column B, datatype udt "b"

Type
User defined type "b"
- column b1, datatype text
- column b2, datatype set <text>

Query is simple, select B.b2 from table.

Example:
```
cqlsh:test_space> create type fruitdetails ( name text, color text, vitamins set<text>);
cqlsh:test_space> create table faves (personName text, fruit frozen <fruitdetails>, primary key(personname));
cqlsh:test_space> insert into faves (personname, fruit) values ('alpha', {name:'apple', color:'red', vitamins:{'A', 'C'}});
cqlsh:test_space> insert into faves (personname, fruit) values ('alpha', {name:'orange', color:'orange', vitamins:{'C'}});     
cqlsh:test_space> insert into faves (personname, fruit) values ('beta', {name:'orange', color:'orange', vitamins:{'C'}}); 
cqlsh:test_space> insert into faves (personname, fruit) values ('beta', {name:'banana', color:'yellow', vitamins:{'B','K'}});
cqlsh:test_space> select fruit.vitamins from faves;

 fruit.vitamins
-------------------------
 SortedSet([u'B', u'K'])
       SortedSet([u'C'])

(2 rows)
Failed to format value SortedSet([u'B', u'K']) : 'NoneType' object has no attribute 'get_n_sub_types'
Failed to format value SortedSet([u'C']) : 'NoneType' object has no attribute 'get_n_sub_types'
```

**Comment by tianon** [comment]
Issues with the `cassandra` official image would be more appropriately filed over in https://github.com/docker-library/cassandra/issues.

That being said, this doesn't look like an issue with the image (at first glance -- definitely could be wrong about that), but rather an issue with your configuration or database, so you might be more likely to get help solving it if you post on a Cassandra user group somewhere (and they might be able to help determine whether the issue really is one in the image, in which case it'd be easier to look at fixing). :+1:
