### ISSUE TITLE
crate:latest pointing to old version

### ISSUE THREAD

**Issue by mikethebeer** [docker-library/official-images#2365]
Hi,

`crate:latest` has been updated to 0.56.3 https://github.com/docker-library/official-images/pull/2286 but on docker-hub it still shows an outdated version. It seems also, that the vulnerability scan failed.

![crate-scan-failed](https://cloud.githubusercontent.com/assets/6863216/20423954/9f70fa78-ad73-11e6-8b20-5c221e645ad1.PNG)

![crate-docker](https://cloud.githubusercontent.com/assets/6863216/20423927/76e8d9e0-ad73-11e6-96d7-3b2892dada28.PNG)

I would really appreciate if you can take a look at it. Maybe it was just a build issue and needs to re-triggered again.

**Comment by yosifkit** [comment]
Hmm, it seems that it might just be the Docker Hub interface with the scanning.  I just pulled `crate` and `crate:0.56` and got the same image:
```console
$ docker images crate
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
crate               0.56                3bcaf8f71c06        3 weeks ago         267.8 MB
crate               latest              3bcaf8f71c06        3 weeks ago         267.8 MB
```

@toli, can you check on the scanning to see if we can get this one restarted for `crate:0.56.3`, `crate:0.56`, and `crate:latest` (all three are the same image)?

**Comment by toli** [comment]
i kicked off the scans for all 3, they are taking a bit longer now than before, so it may take some time.
i'll babysit them to make sure they go through

**Comment by toli** [comment]
scans finished, and `ENV CRATE_VERSION=0.56.3` is showing up for `latest`, `0.56` and `0.56.3`

feel free to close this issue as `done`

**Comment by tianon** [comment]
Thanks @toli! :heart: :heart:

**Comment by mikethebeer** [comment]
thanks a lot guys for looking into this 👍
