### ISSUE TITLE
Update Ruby to 2.3.3

### ISSUE THREAD

**Issue by syndbg** [docker-library/official-images#2374]
Ruby 2.3.3 was just released at https://www.ruby-lang.org/en/news/2016/11/21/ruby-2-3-3-released/

If anyone can update the Ruby image that'd be great. 

🙇

**Comment by tianon** [comment]
https://github.com/docker-library/ruby/commit/47a5e9e829661c5e43279e5e808d89274a4e63cd
:smile:

Just needs an update PR here, which either I or @yosifkit will get to later
today. :+1:

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/2376 :+1:
