### ISSUE TITLE
Postgres image creates dangling volume

### ISSUE THREAD

**Issue by Stratouklos** [docker-library/official-images#2427]
Running the official postgres image leaves a dangling volume that needs to be cleaned up manually.

To replicate:
```
docker run -d --name postgres postgres:latest
docker stop postgres
docker rm postgres
docker volume ls -qf dangling=true
```

Output of `docker inspect --format='{{json .Mounts}}' postgres` while container is running
```
{
   "Name": "64d3ac6b6a69e5488fc9f41512f16b594dea7b6283348321f0336f055a639264",
   "Source": "/var/lib/docker/volumes/64d3ac6b6a69e5488fc9f41512f16b594dea7b6283348321f0336f055a639264/_data",
   "Destination": "/var/lib/postgresql/data",
   "Driver": "local",
   "Mode": "",
   "RW": true,
   "Propagation": ""
}
```

**Comment by yosifkit** [comment]
This is expected and will happen on any image that defines a `VOLUME` in their Dockerfile. Docker does not automatically delete volumes of removed containers.  You can use `docker rm -v contianer-name` to delete the stopped container and the volumes used by the container.
