### ISSUE TITLE
chattr not working in openjdk images

### ISSUE THREAD

**Issue by hennr** [docker-library/official-images#2431]
Marking a file as immutable using chattr does not work with the current openjdk images (8u111) but I sadly don't have a clue why...
I've seen this working with older images though.

To reproduce run this docker file wiht `docker build .`
```
FROM openjdk:8u111

ENV TERM linux
ENV DEBIAN_FRONTEND noninteractive

RUN touch foo
RUN chattr +i foo
```

and you will get the error message:

`chattr: Operation not permitted while setting flags on foo`

**Comment by tianon** [comment]
I don't think this is going to be specific to the `openjdk` image (or any specific image, in fact), and is much more likely to be dictated by your Docker graph driver -- notably, AUFS does not support extended attributes, so may be giving this error (https://github.com/docker/docker/issues/1070#issuecomment-22206125).

**Comment by hennr** [comment]
Thanks for the link, I wasn't aware of that.
It leaves me in doubt if I really had it working with an older image...

In case nobody comes up with another thought about it, please feel free to close this issue.

**Comment by cpuguy83** [comment]
More likely security policy (seccomp) blocking this. Would have to check the default profile.... also depends on what you are chattr'ing to.

But also these attributes would not be persisted in build.

**Comment by justincormack** [comment]
It is not blocked by `seccomp`, it actually uses an ioctl and implemented directly by filesystem drivers, not via extended attributes.

Its actually gated by `CAP_LINUX_IMMUTABLE` which we do not grant by default, you can do it in a `docker run` with `docker run --cap-add LINUX_IMMUTABLE`, but we dont currently have a way to change capabilities on `docker build`.

**Comment by justincormack** [comment]
Not sure if it would actually be round tripped to a registry though, currently extended attributes are round tripped to Docker Hub but these attributes may not be.

**Comment by hennr** [comment]
Thanks @justincormack, running with `--cap-add LINUX_IMMUTABLE` does the job for me.
