### ISSUE TITLE
Document for connect to sentry through API

### ISSUE THREAD

**Issue by hmdhasani** [docker-library/official-images#2492]
I think it would be useful if you give an example in docker page of how to connect to sentry through API, as it can be used for configuring the raw sentry and adding projects and ...

**Comment by yosifkit** [comment]
This might be better discussed on https://github.com/getsentry/docker-sentry.  Ping @mattrobenolt

**Comment by mattrobenolt** [comment]
@hmdhasani https://docs.sentry.io/api/ :)
