### ISSUE TITLE
Why does ubuntu:xenial not have security patches applied?

### ISSUE THREAD

**Issue by nathanaeljones** [docker-library/official-images#2519]
Per https://hub.docker.com/r/library/ubuntu/tags/

Is there a regularly updated xenial image?

**Comment by yosifkit** [comment]
The installed packages are determined by Canonical -- we simply consume the tarballs they provide.  We last built them on Dec 14 with the Canonical tarball from Dec 13. https://partner-images.canonical.com/core/ is where our tarballs are hosted.

We usually rebuild them about once a month, so next week is probably our target time to poke them for a new build.  Is there a specific security update (CVE) that would warrant an expedited update?

**Comment by flx42** [comment]
ping, is it time for a xenial rebuild now?
Thank you!

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/2557 :+1:
