### ISSUE TITLE
GlassFish official repository is depricated 

### ISSUE THREAD

**Issue by aribandy** [docker-library/official-images#2522]
Hi,
In the GlassFish official repository , it's mentioned that it's deprecated(This image is officially deprecated as it has been abandoned by the original maintainer. ) . Also https://github.com/docker-library/official-images/blob/master/library/glassfish gives 404 . We are maintainer of GlassFish app server .Could you please let us know what steps we need to follow to take ownership of this repository . Any help would be appreciated .

**Comment by tianon** [comment]
Hi @aribandy!

If you look at https://github.com/docker-library/official-images/commits/master/library/glassfish instead, you can see all the commits which touched that file (which will allow for getting at the old file contents).  The repo for the `Dockerfile`s of the current images is at https://github.com/aws/aws-eb-glassfish-dockerfiles, although it might be worth having a chat with @brunoborges as well, who maintains https://github.com/glassfish/docker (https://hub.docker.com/r/glassfish/server/).

It's probably worth considering publishing the rebirth of this image under Docker Store -- I'd recommend getting in contact with @wol4max (Krish Garimella; krish.garimella@docker.com) and Dan Powers (dan.powers@docker.com) for more information about that.

**Comment by Djelibeybi** [comment]
Yeah, it's probably worth reviewing the official Oracle Dockerfile at https://github.com/oracle/docker-images/tree/master/GlassFish

There are already active discussions between Oracle and Docker about the Store, so that is being covered.

**Comment by tianon** [comment]
Thanks @Djelibeybi, closing the issue since there's nothing more we (the official images maintainers) can do here. :+1:
