### ISSUE TITLE
Update docker/registry readme to use v2

### ISSUE THREAD

**Issue by stevvooe** [docker-library/official-images#2524]
V2 has been out for almost 2 years. Let's update the readme and latest tag to point at version 2 of the registry.

**Comment by tianon** [comment]
+1!  Contents for that are over in https://github.com/docker-library/docs/blob/master/registry/content.md -- want to make a PR or suggest some content I can proxy? :pray:

**Comment by stevvooe** [comment]
@tianon I'm not sure that I would have time to get through a PR right now. I would just update the default example (I think there are comments on the hub link with the equivalent env variables) then add a warning about using the "legacy" registry.

cc @dmcgowan

**Comment by dmcgowan** [comment]
Not sure I follow, the latest tag already points to 2.5.1. Which readme is not referring to v2?

**Comment by stevvooe** [comment]
Here: https://hub.docker.com/_/registry/

**Comment by dmcgowan** [comment]
OK, sounds good. Latest tag is already updated but example is now incorrect, looks like one person already commented on that.

**Comment by tianon** [comment]
@stevvooe ok, fair enough -- I'll go take a look and see if I can make some simple changes to get it closer to being up to speed

Do you two mind if I give you a ping once I've got the PR ready so you can review and make sure it's accurate?

**Comment by stevvooe** [comment]
@tianon Please do.
