### ISSUE TITLE
No OpenJDK on aarch64

### ISSUE THREAD

**Issue by Knight1** [docker-library/official-images#2550]
Hey,

I noticed that the aarch64/openjdk is not here: https://hub.docker.com/u/aarch64/

There is only the old Java repository https://hub.docker.com/r/aarch64/java/ which is deprecated and no longer updated.

CC'd @vielmetti @tianon

**Comment by tianon** [comment]
It appears to be up for me at https://hub.docker.com/r/aarch64/openjdk/ -- are you seeing something different?

**Comment by Knight1** [comment]
```
core@Deimos2 ~ $ docker run -it --rm aarch64/java java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-1~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
```
```
core@Deimos2 ~ $ docker run -it --rm aarch64/openjdk java -version
Unable to find image 'aarch64/openjdk:latest' locally
Pulling repository docker.io/aarch64/openjdk
docker: Tag latest not found in repository docker.io/aarch64/openjdk.
See 'docker run --help'.
```
```
core@Deimos2 ~ $ docker pull aarch64/openjdk
Using default tag: latest
Pulling repository docker.io/aarch64/openjdk
Tag latest not found in repository docker.io/aarch64/openjdk
```

As you see the repository is not found and the aarch64/java version is outdated. The latest java version is 8u111.

**Comment by tianon** [comment]
The repo is there -- the `latest` tag just doesn't exist (due to some format changes I haven't yet accounted for over in https://github.com/tianon/jenkins-groovy).

Also, `aarch64/java` will not be getting _any_ further updates (just like `_/java` -- it's now completely deprecated).

**Comment by tianon** [comment]
See https://hub.docker.com/r/aarch64/openjdk/tags/ for available tags -- I'd recommend using `N-jre` and `N-jdk` rather than the `openjdk-N-...` tags (since they're there by mistake and likely will stop getting updated at some point).

**Comment by Knight1** [comment]
Thank you @tianon 

I was aware of the deprecation that was the reason I tried to use openjdk but without success. With the specific tags the command succeeded.

```
docker run -it --rm aarch64/openjdk:8-jre java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
```

Is it possible that you add some info to the repo for other users where experiencing the same problem?

**Comment by tianon** [comment]
See https://hub.docker.com/r/arm64v8/openjdk/ :balloon:
