### ISSUE TITLE
add golang/debian stretch docker image

### ISSUE THREAD

**Issue by anarcat** [docker-library/official-images#2639]
Debian stretch has this key feature that there's a GCC cross-compiler in the base system that's available ([gcc-arm-linux-gnueabihf](https://packages.debian.org/search?keywords=gcc-arm-linux-gnueabihf)). That package is not available in the `golang:latest` image that I could find.

Could we get an update on the golang/debian image so that it has such a cross-compiler? It's useful to have such a cross-compiler to build ARM binaries with sqlite support, for example. :)

**Comment by yosifkit** [comment]
I think it might be nice to start preparing to migrate to a new Debian release like we are doing with the alpine based version.  Plus, stretch is getting close to becoming stable (well, it is in freeze now, but it still could be 4-5 months until release).  Maybe we do both for golang 1.8 and then only stretch (if it is released) for golang 1.9?

What do you think @tianon?

**Comment by tianon** [comment]
Seems like an OK plan to me (more conservative than we did for the Jessie
release).

**Comment by anarcat** [comment]
okay well, should i add a separate feature request to get a cross-compiler *now* instead? :)

i mean it makes sense to wait for stretch to release, but right now there's no way to build static go binaries in ARM + sqlite (to give an example of my use case) with the golang images. i had to revert to an ugly hack of using a stretch image and slap a bunch of golang stuff on top of it... [this is yuck](https://gitlab.com/anarcat/wallabako/blob/master/.gitlab-ci.yml)... :)

**Comment by tianon** [comment]
What we mean is to add an explicit "stretch" variant of Go 1.8 right now
(essentially replacing the "wheezy" variant which we just removed from
1.8), and only switch the default image once Stretch is officially released
(which might be as soon as Go 1.9, but might have to be the release after
that).

**Comment by anarcat** [comment]
oh. well that would suit me fine. :) should i try and do change this myself? I would be happy to do such a PR...

**Comment by anarcat** [comment]
alright, did just that, in https://github.com/docker-library/golang/pull/146

**Comment by anarcat** [comment]
cool, thanks! will this propagate here automatically?

**Comment by tianon** [comment]
Heh, not automatically, but we do regenerate the manifest files here on a pretty regular basis -- I'll go do a pass and see if we've got a couple we can push in together. :+1:

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/2645
