### ISSUE TITLE
No logo for F# official

### ISSUE THREAD

**Issue by haf** [docker-library/official-images#2688]
<img width="1113" alt="screen shot 2017-02-24 at 17 05 03" src="https://cloud.githubusercontent.com/assets/193115/23310627/752d8244-fab3-11e6-94a1-abb7c46c119a.png">

How to get one in there?

**Comment by tianon** [comment]
We don't have access to update those, but I can cc @toli here who can file an issue internally to see about updating this.  Is the `logo.png` you've got at https://github.com/docker-library/docs/blob/master/fsharp/logo.png the one you'd like to use?
![](https://github.com/docker-library/docs/raw/master/fsharp/logo.png)

**Comment by haf** [comment]
Yes please, that would be great.

**Comment by Moghedrin** [comment]
As of this date, logo is present. Closing the issue!

**Comment by tianon** [comment]
@Moghedrin I think the logo in question here is the one on https://hub.docker.com/search/?isOfficial=1&q=fsharp, which isn't updated :disappointed:

**Comment by Moghedrin** [comment]
Ah! Quite right, hence needing @toli. Don't mind my overenthusiastic closing! :heart:

**Comment by toli** [comment]
i filed the ticket internally, will follow up to nudge the UI team to get this addressed.

**Comment by tianon** [comment]
I'm going to go ahead and close this since there's nothing we can do from the official images side -- hopefully the Hub folks update these logos at some point soon!
