### ISSUE TITLE
[Questions] Is there a way to find the digest for the previously built official images?

### ISSUE THREAD

**Issue by MichaelSimons** [docker-library/official-images#2715]
I have a scenario in which I need access to the Alpine image that contains 3.4.3. I tracked down the [PR](https://github.com/docker-library/official-images/pull/2160/files) where it was introduced but can't find the digest for the built image anywhere. I would like to be able to pull it via alpine@sha256xxxx.

**Comment by yosifkit** [comment]
We have had https://github.com/docker-library/repo-info up since about September 2015, perhaps the sha256 you want is in the history of https://github.com/docker-library/repo-info/tree/master/repos/alpine? I would guess a `git clone` might be easier than github's interface. :smile_cat:

**Comment by MichaelSimons** [comment]
@yosifkit, this is exactly what I was looking for - much appreciated.
