### ISSUE TITLE
Insufficient free space for journal files

### ISSUE THREAD

**Issue by Globegitter** [docker-library/official-images#281]
I am getting the same error as mentioned here: https://github.com/dockerfile/mongodb/issues/9

Booting up the container has worked for me fine multiple times and then all of the sudden it just stopped working without any apparent reason.

If I change my project to use another db container (e.g. postgres) it works, but would like to use mongo. Any idea what the issue could be, since hard disk space shouldn't be it.

**Comment by tianon** [comment]
This should really be opened on the [mongo repo](https://github.com/docker-library/mongo) directly instead.
