### ISSUE TITLE
curl http request hangs on

### ISSUE THREAD

**Issue by mockitor** [docker-library/official-images#2827]
Hi 

i've encountered a problem with docker images below : 
* ubuntu:latest (16.04)
* debian-jessy
* alpine:3.5

i want to execute a http request to 
[http://www.milliyet.com.tr/rusya-dan-abd-ye-kimyasal-silah-dunya-2427577](http://www.milliyet.com.tr/rusya-dan-abd-ye-kimyasal-silah-dunya-2427577) 
via `curl` command below

```bash
curl -L 'http://www.milliyet.com.tr/rusya-dan-abd-ye-kimyasal-silah-dunya-2427577/'
```
result : 
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<base href="http://www.milliyet.com.tr/"/>
<meta http-equiv="X-UA-Compatible" content="IE=9; IE=8; IE=7; IE=EDGE" /><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>
	Rusya'dan ABD'ye kimyasal silah yanıtı - Dünya Haberleri
</title><meta name="Description" content="Rusya, Şam&#39;dan gelen tüm açıklamalara karşın İdlib&#39;deki kimyasal saldırının sorumlu olarak Suriye&#39;yi işaret eden ABD&#39;ye yanıt geldi. Rusya Dışişleri Bakanlığı Silahlanma Kontrol Dairesi Başkanı Mikhail Ulyanov tarafından yapılan açıklamada, Suriye’deki tüm kimyasal silahların 2014 yılında ABD&#39;nin yardımıyla ülke dışına çıkarıldığını söyledi." /><meta property="og:type" content="article" />
    <meta property="og:title" content="Rusya'dan ABD'ye kimyasal silah yanıtı" />
    <m

```

`curl` command hangs on and cannot download this url. 

I've tried same `curl` command on my **ubuntu 16.04 laptop (`en_US.UTF-8`)**  and it works. 

None of news URL cannot be downloaded on [milliyet.com.tr](http://www.milliyet.com.tr) domain .
I thought this problem is a encoding / character issue but i did not success any tr_TR.UTF-8 locales on ubuntu docker images. 

Steps which i tried : 
* generate `tr_TR.UTF-8`  locale on Docker image => not worked
* generate `en_US.UTF-8` locale on Docker image => not worked
* set `ENV LANG en_US.UTF-8` in Dockerfile => not worked 
* set `ENV LANG tr_TR.UTF-8` in Dockerfile => not worked
* set all locale environment variables to `tr_TR.UTF-8` on Docker image => not worked
* installed `icu, icu-libs` packages => not worked
* `requests.get('http://www.milliyet.com.tr/rusya-dan-abd-ye-kimyasal-silah-dunya-2427577/')` with python => not worked

`docker version`
```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

All http requests (`curl`, `wget`, `python urllib`,`python requests`) to this page just hang on. none of them produce error.

Finally i started to think this problem is not about encoding, i guess some libraries missing on docker images. 

Any help would be appreciated.

**Comment by yosifkit** [comment]
I am unable to reproduce this. I tried from `buildpack-deps:curl` (Debian based image with curl and wget), ubuntu:16.04 (`apt-get update` and `apt-get install -y curl`), and alpine:3.5 (`apk add --no-cache curl`) and they all worked fine. :confused:

**Comment by mockitor** [comment]
Problem still occures on our VPS servers which are Ubuntu 16.04 server hosts. 
 @yosifkit  `buildpack-deps:curl` and other images  works on my local ubuntu 16.04 desktop host.   i've tried on 3  different ubuntu 16.04 server instance but result is same.  

Dockerfile : 
```
FROM buildpack-deps:curl

RUN apt-get update &  apt-get install -y curl

CMD ["curl","-L","http://www.milliyet.com.tr/rusya-dan-abd-ye-kimyasal-silah-dunya-2427577/"]
```


@yosifkit what is your environment, can you try on any Ubuntu server host.

**Comment by mockitor** [comment]
hi @yosifkit. 
i think this problem related to docker/docker/issues/2011 and docker/docker/issues/20178, because i've encountered this issue while trying some https pages after viewed docker/docker/issues/2011  . (`https://slack.com`, `https://sputniknews.com/politics/201704061052375509-talks-wont-be-easy-trump-xi/`)
  
i've added `--mtu=1450` argument to `/lib/systemd/system/docker.service` which explained  here : https://rahulait.wordpress.com/2016/02/28/modifying-default-mtu-for-docker-containers/
and problem solved. 

thanks for your efforts
