### ISSUE TITLE
Drupal 8.3 images not on Docker Hub

### ISSUE THREAD

**Issue by juliencarnot** [docker-library/official-images#2836]
Latest 8.3 release has been pushed to https://github.com/docker-library/drupal , but no PR or change is visible on https://hub.docker.com/_/drupal/

**Comment by tianon** [comment]
From https://github.com/docker-library/drupal/blob/master/README.md:

> See a change merged here that doesn't show up on the Docker Hub yet? Check [the "library/drupal" manifest file in the docker-library/official-images repo](https://github.com/docker-library/official-images/blob/master/library/drupal), especially [PRs with the "library/drupal" label on that repo](https://github.com/docker-library/official-images/labels/library%2Fdrupal). For more information about the official images process, see the [docker-library/official-images readme](https://github.com/docker-library/official-images/blob/master/README.md).

See https://github.com/docker-library/official-images/pull/2838.
