### ISSUE TITLE
removal of 20 tag on fedora image

### ISSUE THREAD

**Issue by lsm5** [docker-library/official-images#305]
This was discussed on #docker-library on freenode and I was told older tags would be kept on hub, even though unsupported.

But, since the present f20 image doesn't have rel-eng approval, fedora is hoping to remove the :20 tag from the fedora image once f21 is released, so that we can call the whole thing official.

Comments?

/cc @mattdm @kushaldas @tianon @yosifkit

**Comment by tianon** [comment]
Closing for now -- feel free to ping again if/when we should reopen and reconsider. :wink:
