### ISSUE TITLE
RethinkDB 2.3.6

### ISSUE THREAD

**Issue by lucidfrontier45** [docker-library/official-images#3252]
RethinkDB 2.3.6 was released recently but the latest official docker image is still 2.3.5. Please update it.
https://github.com/rethinkdb/rethinkdb-dockerfiles/blob/master/jessie/2.3.6/Dockerfile.

**Comment by tianon** [comment]
The maintainers of the `rethinkdb` image aren't likely watching issues on this repo, so this would be more appropriately filed over at https://github.com/rethinkdb/rethinkdb-dockerfiles/issues. :+1:

(Looks like they need to make a PR to update https://github.com/docker-library/official-images/blob/master/library/rethinkdb. :+1:)
