### ISSUE TITLE
CentOS7: Couchbase server expects /etc/init.d/functions to be there

### ISSUE THREAD

**Issue by tleyden** [docker-library/official-images#339]
I'm trying to install Couchbase Server with this dockerfile:

https://github.com/couchbaselabs/couchbase-server-docker/blob/master/3.0.1/Dockerfile

but the `/etc/init.d/couchbase-server` script expects an `/etc/init.d/functions` file, which is not in the CentOS image.

https://gist.github.com/tleyden/b46eedf729006d71fd36#file-gistfile1-txt-L23

And so it gives an error: `/etc/init.d/couchbase-server: line 22: /etc/init.d/functions: No such file or directory` 

Any idea why `/etc/init.d/functions` is not on the CentOS7 image?  When I installed CentOS7 from CentOS-7.0-1406-x86_64-DVD.iso, it contained an `/etc/init.d/functions` file.

Steps to reproduce:

```
$ sudo docker run -ti centos /bin/bash
$ yum install -y wget pkgconfig openssl tar hostname
$ rpm --install http://packages.couchbase.com/releases/3.0.1/couchbase-server-community-3.0.1-centos6.x86_64.rpm
```

Result:

```
Warning: Swappiness is not 0.
You can set the swappiness at runtime with
sysctl vm.swappiness=0
Minimum RAM required  : 4 GB
System RAM configured : 3.67 GB

Minimum number of processors required : 4 cores
Number of processors on the system    : 1 cores



/etc/init.d/couchbase-server: line 22: /etc/init.d/functions: No such file or directory

You have successfully installed Couchbase Server.
Please browse to http://f63f31b276ba:8091/ to configure your server.
Please refer to http://couchbase.com for additional resources.

Please note that you have to update your firewall configuration to
allow connections to the following ports: 11211, 11210, 11209, 4369,
8091, 8092, 18091, 18092, 11214, 11215 and from 21100 to 21299.

By using this software you agree to the End User License Agreement.
See /opt/couchbase/LICENSE.txt.
```

**Comment by tleyden** [comment]
Note: centos6.7 has this same issue of missing `/etc/init.d/functions`, and running `yum install -y wget pkgconfig openssl tar hostname` did not work around it.

**Comment by jperrin** [comment]
This still isn't a problem, and still requires that you install the initscripts package. The centos base containers are designed to be small and thus cannot have all possible packages included.

**Comment by tleyden** [comment]
@jperrin thanks, I will make sure to install `initscripts` w/ centos6.7.

**Comment by Tazovsky** [comment]
`yum install initscripts` solved the issue,
