### ISSUE TITLE
[new] Lua official docker image

### ISSUE THREAD

**Issue by italomaia** [docker-library/official-images#3404]
Lua is a brazilian programing language that has been gaining momentum in the last few years. It would be great to have an official image for it. http://lua.org/

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/blob/master/NEW-IMAGE-CHECKLIST.md -- the first step would be to get in touch with Lua upstream / the Lua community to see if they're interested in maintaining such a thing, collaborating on such a thing, or at least not opposed to such a thing existing.

Since this isn't explicitly actionable as-is, I'm going to close, but please do feel free to continue the conversation here!

**Comment by italomaia** [comment]
@tianon got approval/no opposition from the lua community and some degree of support. 
Cooked up some simple docs https://github.com/italomaia/docs/tree/lua-docs and now I'm trying to figure out the road to create a new official image.
Gonna use https://github.com/akornatskyy/docker-library with https://github.com/docker-library/python/ as base. Now, based on https://github.com/docker-library/official-images/blob/master/README.md I'm not entirely sure about what to do next. I create a new repo with the code that creates the official image and tell "here" about it or something? Where can I get help?

**Comment by tianon** [comment]
I found http://lua-users.org/lists/lua-l/2019-03/msg00067.html -- is this the conversation you were referring to?  It doesn't seem to have gotten much traction at all (only two participants other than yourself, and both didn't seem to think having an explicit Lua image has much merit besides the ease of getting a very explicit version), and digging deeper to try and figure out who would even be authoritative on the Lua community's opinion brought me to https://www.lua.org/faq.html#1.8 and thus http://lua-users.org/lists/lua-l/2008-06/msg00407.html, which honestly does not seem very welcoming or encouraging.

It's also a bit odd IMO that https://github.com/lua/lua/graphs/contributors only has three people listed.  Who is maintaining Lua?  Is that information public anywhere?  The website talks a lot about using the mailing lists to communicate with "the community", and that the maintainers read almost every post there, but there's no information about who they are that I can find. :confused:

**Comment by italomaia** [comment]
Official Lua docker images are very helpful for bigger projects (mostly web projects with Lapis) and for library testing purposes as Lua doesn't have an official virtual environment library as of now or multi-version testers like tox. Other common usages of Lua, like gaming and IOT would really not gain much, as they are tailored for specific Lua versions. 

When asking about "authoritative" people, the language core developers usually get involved in discussions that are related to problems, improvements or more fine grained questions involving the language. If something specific is needed from them besides an "**ok, go on**", I can see to it. 

The language only has three core contributors, PUC professors, but other people and students also help. You can reach out to roberto, if you want, through here http://www.inf.puc-rio.br/~roberto/

He seems to be the most active developer.

**Comment by daurnimator** [comment]
Any sort of lua docker image is going to need to be more than just lua itself to be useful; you'd at least want luarocks installed.
But of course many lua packages have C library dependencies, which opens up all sorts of questions about what should be in the final image. This then brings in questions about which in the base distro to use, which has no correct answer.

all in all, I think a lua docker image won't provide any value, what does e.g. this provide that people can't do themselves in a better way?:
```dockerfile
FROM debian
RUN apt-get update && apt-get install lua
ENTRYPOINT lua
```

**Comment by Etiene** [comment]
@tianon, Lua is not maintained on GitHub, that repo is just a mirror. Bugs and issues are discussed on the mailing list.

**Comment by tianon** [comment]
@Etiene sure but it's a faithful mirror of the real VCS used by the team right? (Which should mean GitHub's contributors data is accurate)
