### ISSUE TITLE
Vault 0.8.3 not found

### ISSUE THREAD

**Issue by chrishoffman** [docker-library/official-images#3472]
The vault 0.8.3 PR #3468 was merged and the website was published by we are getting error when pulling.

```
$ docker pull vault:0.8.3
Error response from daemon: manifest for vault:0.8.3 not found
```

**Comment by yosifkit** [comment]
Yeah, the builds are automated but there polling frequency still needs tuning.  I've manually triggered the build for Vault on amd64.

Similar issues: https://github.com/docker-library/rabbitmq/issues/188, https://github.com/docker-library/ruby/issues/159

**Comment by chrishoffman** [comment]
Thanks for your help.  I see that it is now published.

**Comment by tianon** [comment]
I've filed https://github.com/docker-library/official-images/issues/3835 in order to have a central place to track this problem globally more directly. :+1: :heart:
