### ISSUE TITLE
No alpine image for arm32v7

### ISSUE THREAD

**Issue by Serkan-devel** [docker-library/official-images#3550]
An arm port for alpine linux is missing on https://hub.docker.com/u/arm32v7/

**Comment by tianon** [comment]
It's in arm32v6 instead (since Alpine chose to support minimum v6 instead
of v7, especially for the raspberry pis).  Also, those Alpine multiarch
images are not officially supported fully yet, see
https://github.com/gliderlabs/docker-alpine/issues/304.
