### ISSUE TITLE
Make /root directory on Ubuntu 755 instead of 700

### ISSUE THREAD

**Issue by mitar** [docker-library/official-images#356]
Because of issue with aufs (https://github.com/docker/docker/issues/8514) it is not really possible to change permissions of the /root directory to 755 and allow programs running under a different user inside a container to access it. I would suggest that permissions are changed to 755. It is running inside a container anyway so such default is more reasonable.

**Comment by tianon** [comment]
This should really be opened on the [ubuntu image repo](https://github.com/tianon/docker-brew-ubuntu-core) directly instead, but I think it's pretty firmly in the `wontfix` category.
