### ISSUE TITLE
JRuby lists architectures unsupported by parent images

### ISSUE THREAD

**Issue by yosifkit** [docker-library/official-images#3646]
cc @cpuguy83

https://github.com/docker-library/official-images/blob/60a9ef92faebe178621092f8a9a952a2c4853c65/library/jruby#L18-L20

https://github.com/docker-library/official-images/blob/60a9ef92faebe178621092f8a9a952a2c4853c65/library/openjdk#L67-L70

There is also some build failures for `jruby:9*`on arm32v7: https://doi-janky.infosiftr.net/job/multiarch/view/flat/job/arm32v7/job/jruby/2/console

**Comment by cpuguy83** [comment]
Ah shoot, I didn't copy/paste this correctly for the alpine images.

**Comment by cpuguy83** [comment]
arm32v7 error looks just like i386 issues. I'll pull it for now.
