### ISSUE TITLE
maven: no matching manifest for linux/amd64 in the manifest list entries.

### ISSUE THREAD

**Issue by DrStrangepork** [docker-library/official-images#3653]
```
# docker pull maven:3-jdk-8-alpine
3-jdk-8-alpine: Pulling from library/maven
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by DrStrangepork** [comment]
This problem seems to have resolved itself. Any idea why this happened?

**Comment by tianon** [comment]
See the discussion over in https://github.com/docker-library/official-images/pull/3649#issuecomment-340682960; the new update used an unsupported tag, which caused the `amd64` build to fail, so I had to do some manual finangling to make it build properly.

(related issues: docker-library/rabbitmq#188, docker-library/ruby#159, c0b/docker-erlang-otp#75, docker-library/official-images#3472, docker-library/wordpress#239, https://github.com/docker-library/official-images/pull/3622)

**Comment by tianon** [comment]
I've filed https://github.com/docker-library/official-images/issues/3835 in order to have a central place to track this problem globally more directly. :+1: :heart:
