### ISSUE TITLE
Update to latest postgres

### ISSUE THREAD

**Issue by rrrrrrrrramba** [docker-library/official-images#3695]
Postgres has been updated, see https://www.postgresql.org/about/news/1801/.

The libraries are already updated, see https://github.com/docker-library/postgres.

Who can update the manifests?

**Comment by tianon** [comment]
Anyone can submit a PR to perform the update -- see `generate-stackbrew-library.sh` in the PostgreSQL repo, and https://github.com/docker-library/official-images/pull/3698 for what the end result looks like.
