### ISSUE TITLE
Getting error while apt-get update running

### ISSUE THREAD

**Issue by Nivy98** [docker-library/official-images#3703]
Err:46 http://ports.ubuntu.com/ubuntu-ports xenial-security/universe Sources   
  Hash Sum mismatch
its not working

**Comment by yosifkit** [comment]
> In my personal experience, `Hash Sum mismatch` usually means one of the following:
>
> 1. temporary glitch in the mirror / CDN (or mis-generation of mirror files, in the case of non-Debian repositories)
> 2. temporary glitch in local network / firewall or route to mirror / CDN
> 3. glitch in APT cacher (flushing cache usually fixes this)
> 
> Have you tried again to see if the issue resolved itself?

https://github.com/docker-library/openjdk/issues/90#issuecomment-268863365
