### ISSUE TITLE
UTC ALL THE THINGS

### ISSUE THREAD

**Issue by tianon** [docker-library/official-images#390]
`date +%Z` → `UTC`

- [ ] `cirros`: `MST` (@ewindisch)
- [ ] `fedora:21`: `EST` (@lsm5)
- [x] `oraclelinux:6`: `EST`

Created an issue for it so we can track completion. :+1:

**Comment by vaijab** [comment]
+1

**Comment by tianon** [comment]
ping @ewindisch @lsm5 

Status update?:no_mouth:

**Comment by lsm5** [comment]
@tianon @kushaldas built an image with tz corrected, but getting that out via fedora's official release process might take a bit longer (I think). correct me if i'm wrong @kushaldas

**Comment by tianon** [comment]
Is there a strong reason for the official builds to be on `EST`?  It seems really random. :smile:

**Comment by lsm5** [comment]
afaik nope, probably just something that crept in :|

**Comment by subesokun** [comment]
+1
It would be awesome if you allow passing in a configuration parameter when starting the docker container in order to set the time zone. Reading out the time zone from the host might not be always sufficient e.g.:
> If your Jenkins instance is running in a different location than the user's (for example: the server is in NY but users are in LA), then the NY time zone will most probably be used, which may be quite annoying if you need to compare build dates.
> https://wiki.jenkins-ci.org/display/JENKINS/Change+time+zone

An implementation similar to [GITLAB_TIMEZONE](https://github.com/sameersbn/docker-gitlab#available-configuration-parameters) would be great.

**Comment by cpuguy83** [comment]
Because EST is superior to all other time zones, of course :)

**Comment by tianon** [comment]
ping @lsm5 @ewindisch

**Comment by lsm5** [comment]
@tianon, @kushaldas has committed a patch, I'll send out an update to you once it's built in fedora's build system.

**Comment by ewindisch** [comment]
@tianon - the MST setting is imported directly from the upstream cirros project. All CirrOS images for VMs and containers both have this set. Changing it just for Docker could potentially create incompatibilities. I'll file a bug upstream and see what they say.

**Comment by tianon** [comment]
:heart: -- I'd love to at the very least get the rationale for it :+1:

**Comment by ewindisch** [comment]
@tianon pretty sure it's, "Scott Moser lives in MST"

**Comment by tianon** [comment]
hahaha, I can certainly respect that level of narcissism :laughing:

(but I want it from the horse's mouth before I give up, so I appreciate your filing the issue)

**Comment by ewindisch** [comment]
@tianon - cirros is now fixed upstream. Will be in the next release.

**Comment by tianon** [comment]
I saw! :smile:

**Comment by Djelibeybi** [comment]
The OL7 image is UTC. We'll update the OL6 images around the time we publish the OL5 image.

**Comment by Djelibeybi** [comment]
Just pinging this, as all the Oracle Linux images should be UTC now.

**Comment by ewindisch** [comment]
@lsm5 can we confirm this is now fixed in Fedora? If so, this can be closed.

**Comment by lsm5** [comment]
@ewindisch fixed in the latest stable `fedora:latest` but `fedora:21` is still on EDT. I'll check with rel-eng about an update on f21.

**Comment by tianon** [comment]
The state of this transition is probably as good as we're going to get.  All new repositories (and most others) are converted. :+1:
