### ISSUE TITLE
Publish golang:1.9.3 image

### ISSUE THREAD

**Issue by korya** [docker-library/official-images#3926]
As far as I can see a support for GO v1.9.3 was added to https://github.com/docker-library/golang repo in https://github.com/docker-library/golang/commit/2f2f3b620d61f533484f24a568c2ca46e4fda91c . When can we expect an official `golang:1.9.3` image to be published?

Side question: is it an automated process? how long does it usually take to publish an image for recent version of GO?

**Comment by tianon** [comment]
https://github.com/docker-library/golang/blob/master/README.md

> See a change merged here that doesn't show up on the Docker Hub yet? Check [the "library/golang" manifest file in the docker-library/official-images repo](https://github.com/docker-library/official-images/blob/master/library/golang), especially [PRs with the "library/golang" label on that repo](https://github.com/docker-library/official-images/labels/library%2Fgolang). For more information about the official images process, see the [docker-library/official-images readme](https://github.com/docker-library/official-images/blob/master/README.md).

https://github.com/docker-library/official-images/pull/3928

**Comment by tianon** [comment]
We usually get updates published within the next business day after the automated @docker-library-bot commits them.

**Comment by korya** [comment]
OK. Thanks.
