### ISSUE TITLE
Running C++ Applications built with Visual Studio

### ISSUE THREAD

**Issue by kdeenanauth** [docker-library/official-images#403]
Using the instructions provided, it appears trying to compile and run a C++ application isn't supported well yet.

    docker@boot2docker:/c/Users/Kevin/Documents/Docker/mono-c-plus-plus-app$ docker build -t c-plus-plus-app .
    Sending build context to Docker daemon 9.178 MB
    Sending build context to Docker daemon
    Step 0 : FROM mono:3.10-onbuild
    # Executing 4 build triggers
    Trigger 0, COPY . /usr/src/app/source
    Step 0 : COPY . /usr/src/app/source
    Trigger 1, RUN nuget restore -NonInteractive
    Step 0 : RUN nuget restore -NonInteractive
     ---> Running in 71c7e0ff901e
    Trigger 2, RUN xbuild /property:Configuration=Release /property:OutDir=/usr/src/app/build/
    Step 0 : RUN xbuild /property:Configuration=Release /property:OutDir=/usr/src/app/build/
     ---> Running in 7e7a6643c86a
    XBuild Engine Version 12.0
    Mono, Version 3.10.0.0
    Copyright (C) 2005-2013 Various Mono authors

    Build started 01/16/2015 05:57:59.
    __________________________________________________
    /usr/src/app/source/CPlusPlusApp.sln:  warning : Ignoring vcproj 'CPlusPlusApp'.
    /usr/src/app/source/CPlusPlusApp.sln:  warning : Failed to find project eb424bc8-47bf-421e-b413-138c2483497f
    Project "/usr/src/app/source/CPlusPlusApp.sln" (default target(s)):
            Target ValidateSolutionConfiguration:
                    Building solution configuration "Release|Win32".
    Done building project "/usr/src/app/source/CPlusPlusApp.sln".

    Build succeeded.

    Warnings:

    /usr/src/app/source/CPlusPlusApp.sln:  warning : Ignoring vcproj 'CPlusPlusApp'.
    /usr/src/app/source/CPlusPlusApp.sln:  warning : Failed to find project eb424bc8-47bf-421e-b413-138c2483497f

             2 Warning(s)
             0 Error(s)

    Time Elapsed 00:00:00.1701750
    Trigger 3, WORKDIR /usr/src/app/build
    Step 0 : WORKDIR /usr/src/app/build
     ---> Running in b275c3ac8a4e
     ---> 0920b257cda5
    Removing intermediate container 71c7e0ff901e
    Removing intermediate container 7e7a6643c86a
    Removing intermediate container b275c3ac8a4e
    Removing intermediate container fbe7593d732e
    Step 1 : CMD mono ./CPlusPlusApp.exe
     ---> Running in 69b034929140
     ---> 1698b5a50a0a
    Removing intermediate container 69b034929140
    Successfully built 1698b5a50a0a
    docker@boot2docker:/c/Users/Kevin/Documents/Docker/mono-c-plus-plus-app$ docker run c-plus-plus-app
    Cannot open assembly './CPlusPlusApp.exe': No such file or directory.
    docker@boot2docker:/c/Users/Kevin/Documents/Docker/mono-c-plus-plus-app$

**Comment by tianon** [comment]
I think you're looking for [the mono repo](https://github.com/mono/docker/issues). :+1:

**Comment by kdeenanauth** [comment]
Whoops sorry. You're right
