### ISSUE TITLE
Missing Traefik's logo

### ISSUE THREAD

**Issue by emilevauge** [docker-library/official-images#4043]
Hi

Traefik's logo is missing from [search results on Docker Hub](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&q=traefik), even thought we have the logo in the [docker-library Documentation repoitory](https://github.com/docker-library/docs/tree/master/traefik). 
How can we get our logo there, like Swarm ?

![screenshot from 2018-02-23 12-14-55](https://user-images.githubusercontent.com/6207234/36591793-63136ade-1893-11e8-96e2-d2a1c0f53e5a.png)

Thanks :)

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/issues/2688 is another example of this type of problem -- unfortunately, we don't have any control over or even visibility into those, so we can't help directly, but in the past, @programmerq has offered to proxy these types of requests to the internal bug tracker for the appropriate team/product at Docker Inc, so hopefully he's still hip for that. :pray: :heart:

Sorry!

**Comment by vdemeester** [comment]
ping @nandhini915

**Comment by XVincentX** [comment]
@programmerq I'm having the same issue with https://hub.docker.com/_/express-gateway

**Comment by tianon** [comment]
This is now fixed! :+1: :tada:
