### ISSUE TITLE
Rebuild vault 0.9.5 images

### ISSUE THREAD

**Issue by chrishoffman** [docker-library/official-images#4059]
We had a problem with our checksums causing all the 0.9.5 builds to fail.  Can you please rebuild and publish the images?

**Comment by yosifkit** [comment]
We triggered the builds again and they are all green now: https://doi-janky.infosiftr.net/job/multiarch/view/images/view/vault/. They should be available on the Docker Hub.

**Comment by chrishoffman** [comment]
Thanks!
