### ISSUE TITLE
io.js

### ISSUE THREAD

**Issue by jfrazelle** [docker-library/official-images#408]
There should probably be an official docker image for io.js (https://github.com/iojs/io.js). WDYT?

Would this be okay with you all @maxogden?

**Comment by jfrazelle** [comment]
I can contribute it if we decide yes, not trying to create work for anyone else ;)

**Comment by pesho** [comment]
Hey @jfrazelle we have a repo at https://github.com/iojs/docker-iojs for that. It's currently live on Docker Hub at https://registry.hub.docker.com/u/iojs/iojs/ but the intention is to submit it as an official image soon. Please feel free to chime in.

**Comment by rvagg** [comment]
It would be great if the io.js community were able to maintain the official images, the iojs/docker-iojs repo has a number of very engaged developers working on making the image as good as it can be.

**Comment by jfrazelle** [comment]
Yes I think it would be great if the io.js community maintained the images. And you all are definitely on the right track. Sorry if this caused any confusion. Keep doing your thing :) and I will be excited when you all open the PR to add it.
