### ISSUE TITLE
discourse image

### ISSUE THREAD

**Issue by pierreozoux** [docker-library/official-images#4169]
I'd like to reopen #1944

I'm maintaining [this image](https://github.com/libresh/docker-discourse) but I'd like to add tags to make it proper for production usage.

In fact, I'm a bit lazy to make all the plumbing, when I know you have a beautiful pipeline just made for that :)

Would you consider again having an official discourse image?

I really would like to help [all these people](https://meta.discourse.org/search?q=kubernetes) and making it official would also ease the collaboration among all these people.

After this official image, I'd like to PR an official helm chart, and I think it would also be more appropriate to use an officially built docker image rather than the one from my organization.

If I get an approval from the maintainer to have this community effort going on, will it be ok?

Thanks!

Ok, just asked for support from [the maintainers](https://meta.discourse.org/t/community-supported-official-docker-image/83768).

**Comment by tianon** [comment]
Closing in favor of the (appropriate) discussion that's happened / happening in https://meta.discourse.org/t/community-supported-official-docker-image/83768.  Without upstream's buy-in/support, I'm not comfortable with a Discourse official image (especially for the reasons they outline in that very thread -- if the image has issues, it makes them look bad, so it's way better to have them on board).

I think it's also worth pointing out https://github.com/docker-library/docs/pull/1251 given that #1944 references ownCloud specifically.
