### ISSUE TITLE
Rebuild Gradle images

### ISSUE THREAD

**Issue by keeganwitt** [docker-library/official-images#4188]
Please rebuild the Gradle images.  Somehow the Java 10 JDK image has Java 9 in it (despite that now the JDK 10 image has Java 10).

https://github.com/keeganwitt/docker-gradle/issues/53

**Comment by tianon** [comment]
See https://github.com/docker-library/openjdk/issues/180, https://github.com/docker-library/repo-info/issues/23, https://github.com/appropriate/docker-jetty/issues/87, https://github.com/docker-library/tomcat/issues/113, https://github.com/docker-library/buildpack-deps/issues/75, etc.  We're actively working on rebuilding images with our fix (including Gradle).

**Comment by tianon** [comment]
Gradle is fixed and pushed. :+1:

**Comment by tianon** [comment]
(or at least `amd64/gradle` is, and `/_/gradle` will be as soon as https://doi-janky.infosiftr.net/job/put-shared/job/light/ runs, which will be in ~5 minutes)
