### ISSUE TITLE
Need edit access to official page

### ISSUE THREAD

**Issue by arthurdm** [docker-library/official-images#4219]
Hi,

I am the new maintainer of the WebSphere Liberty image (https://github.com/WASdev/ci.docker/blob/master/ga/developer/kernel/Dockerfile#L17) and would like to request "edit" access to this page:   https://hub.docker.com/_/websphere-liberty/ 

I need to fix some old links that are incorrect.

Thanks.

**Comment by yosifkit** [comment]
The content on the Docker Hub is all controlled through the [docs repo](https://github.com/docker-library/docs/).  More specifically in the [websphere-liberty folder](https://github.com/docker-library/docs/tree/master/websphere-liberty).  Just make your edits in anything but `README.md` and it will be generated from the changes.  It will also be used on each of the architecture specific namespaces on the Docker Hub: [`amd64`](https://hub.docker.com/r/amd64/websphere-liberty/), [`i386`](https://hub.docker.com/r/i386/websphere-liberty/), [`ppc64le`](https://hub.docker.com/r/ppc64le/websphere-liberty/), and [`s390x`](https://hub.docker.com/r/s390x/websphere-liberty/).

Let us know if you have any questions. :+1:

**Comment by arthurdm** [comment]
thanks @yosifkit!
