### ISSUE TITLE
Alpine 3.4 reaches its EOL on 2018-05-01, how to proceed with `alpine` tags aliasing `alpine3.4`?

### ISSUE THREAD

**Issue by michael-k** [docker-library/official-images#4275]
Many official images have `*-alpine` tags that alias `*-alpine3.4`.  The reason are stability issues/guarantees as discussed in docker-library/golang#131 and the many linked issues.

As https://github.com/bmw pointed out in docker-library/python#265 Alpine 3.4 will reach its [end of life on 2018-05-01](https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases).  Are there plans to deal with this?  I see the following options (are there more?):

- If `*-alpine` is an alias for `*-alpine3.4`, make it an alias for
  - `*-alpine3.5`.
  - `*-alpine3.7`.
  - `*-alpine3.8` (which should be released at about the same time).
- Since `*-alpineX.Y` should be used by anyone aiming for stability, use `*-alpine` as a rolling tag.
- Drop the `*-alpine` tags.

Is any one of them preferred?

---

Progress list:

- [x] `eggdrop`: https://github.com/eggheads/eggdrop-docker/issues/8#issuecomment-385223204
- [ ] `node`: https://github.com/nodejs/docker-node/pull/725#issuecomment-389923198, https://github.com/nodejs/docker-node/issues/473
- [x] `php`: https://github.com/docker-library/php/pull/650, https://github.com/docker-library/php/issues/504, https://github.com/docker-library/php/pull/646
- [x] `python`: https://github.com/docker-library/python/pull/290, https://github.com/docker-library/python/issues/265
- [ ] `registry`: docker/distribution-library-image#74, docker/distribution-library-image#64, docker/distribution-library-image#62
- [x] `ruby`: https://github.com/docker-library/ruby/pull/210, https://github.com/docker-library/ruby/issues/81

**Comment by tianon** [comment]
Also, once Alpine 3.4 is officially EOL, we should start removing `*-alpine3.4` tags everywhere.

**Comment by tianon** [comment]
From what I can find, the full list of images that still have tags `FROM alpine:3.4` is:

- `eggdrop`
- `node`
- `php`
- `python`
- `registry`
- `ruby`

**Comment by vielmetti** [comment]
`eggdrop` has a change in the works, per https://github.com/eggheads/eggdrop-docker/issues/8#issuecomment-385223204

**Comment by vielmetti** [comment]
The open issue for `php` is https://github.com/docker-library/php/issues/504

**Comment by tianon** [comment]
`registry`: https://github.com/docker/distribution-library-image/pull/74, https://github.com/docker/distribution-library-image/issues/64, https://github.com/docker/distribution-library-image/pull/62

**Comment by tianon** [comment]
(Updated the OP with a proper checkbox-list so we get issue progress indications from GitHub)

**Comment by tianon** [comment]
Looks like `node:6-alpine` and `registry:2.6`/`registry:2.5` are all that's left here, so I'm going to close (in favor of those specific images' issue trackers where these are already more appropriately tracked).
