### ISSUE TITLE
mosquitto 1.5 + multiarch support

### ISSUE THREAD

**Issue by vielmetti** [docker-library/official-images#4358]
Mosquitto 1.5 is out as of May 10. It's an MQTT implementation (client and server) used in IOT networks.

https://github.com/eclipse/mosquitto

It would be terrific to offer a Docker image for Mosquitto 1.5, as well as to provide multiarch support in that image, as expressed at https://github.com/eclipse/mosquitto/issues/815 

Note that Alpine has a full set of images to support a multiarch build, but that they are at 1.4.15-r3 (which is marked as "outdated") in edge.

**Comment by tianon** [comment]
cc @daudetCA

(in the future, image-specific issues like this should be filed directly on the image repos as linked in the image description on Docker Hub, which in this case would be https://github.com/eclipse/mosquitto/issues)

**Comment by wglambert** [comment]
Going to close to redirect to https://github.com/eclipse/mosquitto/issues/669
