### ISSUE TITLE
alpine image for ppc64le is not parity with amd64 platform

### ISSUE THREAD

**Issue by mkumatag** [docker-library/official-images#4439]
ppc64le image is pretty old compared with amd64 platform, can you please us generating the new one?

```
root@localhost:~/policy_ws/src/github.ibm.com/IBMPrivateCloud# docker images | grep alpine
alpine                                     3.6                 77144d8c6bdc        4 months ago        3.97 MB
ppc64le/alpine                             3.6                 daa414b19dcf        7 months ago        4.72 MB
root@localhost:~/policy_ws/src/github.ibm.com/IBMPrivateCloud#
```

**Comment by tianon** [comment]
There's not much (if anything) we can do about this at this level (as noted at https://hub.docker.com/_/alpine/, this should be filed at https://github.com/gliderlabs/docker-alpine/issues) -- this will require rebuilt tarballs at https://github.com/gliderlabs/docker-alpine, which probably even means a new release from Alpine upstream.

**Comment by mkumatag** [comment]
created issue in alpine repo  - https://github.com/gliderlabs/docker-alpine/issues/413
