### ISSUE TITLE
Why can't connect Mac boot2docker mysql images? 

### ISSUE THREAD

**Issue by zhaozhiming** [docker-library/official-images#447]
HI ALL,
I pull the docker mysql:5.7.5 images, and  can connect use this command:

```
docker run -it --link some-mysql:mysql --rm mysql sh -c 'exec mysql -h"$MYSQL_PORT_3306_TCP_ADDR" -P"$MYSQL_PORT_3306_TCP_PORT" -uroot -p"$MYSQL_ENV_MYSQL_ROOT_PASSWORD"' 
```

but can't connect use mac mysql client, I use Navicat for Mysql. Do I have something missed? Thanks.

![screen shot 2015-02-02 at 11 33 50 am](https://cloud.githubusercontent.com/assets/1436694/5995489/6e118932-aacf-11e4-85ba-53322d8ef269.png)

![screen shot 2015-02-02 at 11 33 58 am](https://cloud.githubusercontent.com/assets/1436694/5995491/702ed6ac-aacf-11e4-9821-ee9abfa1c1f7.png)

**Comment by cpuguy83** [comment]
How did you start the mysql container?

The run command above is not using the 192.168.59.103 address, it's using the actual container's address since this is what --link provides.

**Comment by zhaozhiming** [comment]
I use this command to start mysql container, I start the container in the boot2docker, which like as [vagrant][vagrant] and it's a vm with ip 192.168.59.103.

```
docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=mysecretpassword -d mysql
```

I think I know the reason now, maybe it's the root user don't have the remote access, but I don't know how to change the my.conf.

Finally I use the [tutum/mysql][tutum/mysql], it's can generate a admin user make me can remote access and I don't need change anything.


[vagrant]: https://www.vagrantup.com/
[tutum/mysql]: https://registry.hub.docker.com/u/tutum/mysql/tags/manage/

**Comment by cpuguy83** [comment]
If you want to be able to access it from OS X, you need to either the publish port 3306 of the container to a host port or setup a static route on OS X to the container network on boot2docker.

**Comment by zhaozhiming** [comment]
ok, thanks.
