### ISSUE TITLE
alpine image version 3.8 (latest) is broken

### ISSUE THREAD

**Issue by andersla** [docker-library/official-images#4543]
```
$ docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by sfriedel** [comment]
I'm seeing the same thing already for a couple of hours.

I believe the manifest error is related to #3835 and should resolve itself once the image build completes. But at the same time [the build](https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/alpine/) does seem somewhat stuck to me.

**Comment by jessfraz** [comment]
was just about to say the same thing :) ping @tianon @thajeztah

**Comment by tianon** [comment]
Yeah, sorry about this!  See https://github.com/gliderlabs/docker-alpine/issues/418#issuecomment-403054625:

> We had a temporary issue with our main amd64 build host that I've now corrected ... Build was successful, manifest lists should be pushed soon (or already). :+1:

**Comment by thaJeztah** [comment]
Ha! I get pinged all over the place :joy: (also saw https://github.com/gliderlabs/docker-alpine/issues/418#issuecomment-403054625 this morning)

Glad it's resolved!
