### ISSUE TITLE
Update wordpress manifest for 4.9.7

### ISSUE THREAD

**Issue by alex** [docker-library/official-images#4547]
https://github.com/docker-library/wordpress/commit/b7198b18d92c016411c4bc3cdb31711065305605 happened yesterday, upgrading to wordpress 4.9.7, which resolves some security issues https://wordpress.org/news/2018/07/wordpress-4-9-7-security-and-maintenance-release/

Now https://github.com/docker-library/official-images/blob/master/library/wordpress needs to be updated. If someone can suggest what needs to happen, I'm happy to send a PR for it

**Comment by yosifkit** [comment]
It is just a matter of updating library/wordpress with the output of `./generate-stackbrew-library.sh` from the wordpress repo. I have gone ahead and made a PR since there were a couple that needed updating.
