### ISSUE TITLE
USE_ZEND_ALLOC=0 to mitigate SIGSEGV in zend_hash_str_find()

### ISSUE THREAD

**Issue by dachary** [docker-library/official-images#4604]
A [known php allocator bug](https://bugs.php.net/bug.php?id=75375) causes occasional crashes of PHP unless USE_ZEND_ALLOC=0 is set in the environment. A [reproducer was provided](https://github.com/nextcloud/server/issues/10241) and will hopefully allow this rather old problem to be fixed.

In the meantime I suggest USE_ZEND_ALLOC=0 is set to mitigate the problem.

**Comment by tianon** [comment]
I think this has likely been filed in the wrong place -- this is the repo for the official images at large.  If you're having an issue with a specific image, see "where to file issues" in the "quick reference" section of the image description.

**Comment by dachary** [comment]
This issues concerns all images based on php 7+

**Comment by tianon** [comment]
So then https://github.com/docker-library/php would be the appropriate
place to discuss it.

**Comment by dachary** [comment]
Oh, right, my bad. Sorry for the noise!
