### ISSUE TITLE
People keep confusing "dockerfile" with the official library

### ISSUE THREAD

**Issue by stuartpb** [docker-library/official-images#471]
See https://github.com/stuartpb/dokku-rethinkdb-plugin/issues/7#issuecomment-73436903 - I've also gotten an email (on 2014-06-01, when the actual official library was just starting out) asking me why I wasn't using "the official dockerfile image" of RethinkDB because I was using `crosbymichael/rethinkdb` (which largely looks like what the official `rethinkdb` image would come to look like) instead of `dockerfile/rethinkdb` (which... doesn't).

I'm trying to be diplomatic here, but it seems to me that the existence of https://registry.hub.docker.com/repos/dockerfile/, using the Docker logo as its avatar, is problematic with the existence of an *actual* official library. If it was just called `pilwon/`, that would be fine, but the choice of name leads people to think `dockerfile/` is the "official prefix" for "official Docker images",  leading them to miss the *actual* official repos under `/_/` altogether.

I imagine the same confusion would apply for `base/` and `dockerfiles/`, were they publishing updates regularly.

**Comment by md5** [comment]
The use of Docker's logo by @dockerfile does seem problematic. That being said, the [trademark & logo guidelines](https://www.docker.com/legal/trademark_guidelines/) on Docker, Inc's site don't spell out what acceptable uses of their logo are as far as I could tell.

**Comment by md5** [comment]
Looks like this has been worked out: http://blog.docker.com/2015/03/updates-available-to-popular-repos-update-your-images/

**Comment by stuartpb** [comment]
Excellent, glad to see this being worked out!

Why do some of those links point to the library as https://registry.hub.docker.com/_ and some as https://registry.hub.docker.com/u/library ?

**Comment by yosifkit** [comment]
No reason that I know of. They go to the same place.

**Comment by alister** [comment]
I've got a [PR for the dockerfile site](https://github.com/dockerfile/dockerfile.github.io/pull/1) to mark it as depreciated, and link back to that blog post for a better supported/official image.

**Comment by tianon** [comment]
This is resolved. :+1:
