### ISSUE TITLE
Document build process for official images especially for multiarch

### ISSUE THREAD

**Issue by MichaelEFlip** [docker-library/official-images#4777]
I cannot find any documentation how the official images are built for different platforms.
This is what I found out from exploring github and the CI system:
- QEMU is not used for cross-compiling
- There are different nodes for different platforms (https://doi-janky.infosiftr.net/computer/)
- Eventually https://www.worksonarm.com is used for building for ARM platform

It would be nice to have some documentation what is the official and best way to compile for other platforms (not amd64).

**Comment by tianon** [comment]
Good point!  Here's the blurb I've been writing for a WIP FAQ we've been creating: (maybe it answers your questions?)

### How are images built? (especially multiarch)

Images are built via a [semi-complex Jenkins infrastructure](https://doi-janky.infosiftr.net/), and the sources for much of that can be found in [the `github.com/docker-library/oi-janky-groovy` repository](https://github.com/docker-library/oi-janky-groovy).

The infrastructure is a combination of machines provided by Docker, Inc. and several generous donors (for non-`amd64` architectures):

-	`arm32vN`: [WorksOnArm](https://github.com/WorksOnArm/cluster/issues/7)
-	`arm32v6` (selected images): QEMU on Tianon's personal machine; see:
	-	https://github.com/docker-library/busybox/pull/41
	-	https://github.com/docker-library/golang/issues/196
	-	https://github.com/docker-library/memcached/issues/25
	-	https://github.com/docker-library/postgres/issues/420#issuecomment-370033903
	-	https://github.com/docker-library/redis/issues/137
-	`arm64v8`: [Linaro](https://www.linaro.org/)
-	`ppc64le`, `s390x`: [IBM](https://www.ibm.com/)

At a high-level, the image publishing process looks something like this:

1.	images are built on a machine relevant to their architecture
2.	architecture-specific images get pushed to the respective architecture-specific Docker Hub namespace (`amd64/xxx`, `arm64v8/xxx`, `s390x/xxx`, etc)
3.	a manifest list is created for `library/xxx` from the list of architecture-specific artifacts ([caveat docker-library/official-images#3835](https://github.com/docker-library/official-images/issues/3835))

**Comment by tianon** [comment]
The aforementioned FAQ is now public, and this is answered within: https://github.com/docker-library/faq#how-are-images-built-especially-multiarch
