### ISSUE TITLE
amd64 (and i386) build server down, causing issues pulling new image tags

### ISSUE THREAD

**Issue by keeganwitt** [docker-library/official-images#4789]
The following Gradle tags don't have amd64 images:
* https://registry.hub.docker.com/v2/repositories/library/gradle/tags/jre-alpine/ (4.10.0-jre8-alpine, 4.10-jre8-alpine, jre8-alpine, 4.10.0-jre-alpine, 4.10-jre-alpine, jre-alpine)
* https://registry.hub.docker.com/v2/repositories/library/gradle/tags/jdk-alpine/ (4.10.0-jdk8-alpine, 4.10-jdk8-alpine, jdk8-alpine, 4.10.0-jdk-alpine, 4.10-jdk-alpine, jdk-alpine, 4.10.0-alpine, 4.10-alpine, alpine)
* https://registry.hub.docker.com/v2/repositories/library/gradle/tags/jdk7-alpine/ (4.10.0-jdk7-alpine, 4.10-jdk7-alpine, jdk7-alpine)
* https://registry.hub.docker.com/v2/repositories/library/gradle/tags/jre7-alpine/ (4.10.0-jre7-alpine, 4.10-jre7-alpine, jre7-alpine)

**Comment by mhumeSF** [comment]
Looks like the pipeline is still building out the images
https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/gradle/102/console

**Comment by 0l33l** [comment]
The multiarch-amd64 and multiarch-i386 nodes are offline, and has been for a day. The builds will be stuck in the queue until the nodes are restored.

**Comment by tianon** [comment]
Crap, yep; we're working on restoring that infra asap!  Sorry for the trouble. 😰💀

**Comment by tianon** [comment]
Just to be clear, this is the build server outage _coupled_ with https://github.com/docker-library/official-images/issues/3835.

Known affected repos:

- `gradle`
- `wordpress`
- `nginx`

(will try to keep this list up to date as we scramble to get that infrastructure back up)

**Comment by tianon** [comment]
**Update:** I've put a temporary patch in place to build just these three images to fix the interim issue while we work on the larger infrastructure issue (ie, rebuilding our main amd64 build server).

**Comment by aduth** [comment]
Verifying on my end that `docker pull wordpress:cli` is once again working as expected, and we're seeing [builds pass in our Travis environment](https://travis-ci.org/WordPress/gutenberg/builds) which were previously failing.

Thanks for jumping on this so quickly!

**Comment by tianon** [comment]
Yeah, hopefully we can get the proper infrastructure restored soon. :grimacing:

**Comment by keeganwitt** [comment]
Thanks @tianon!

**Comment by tianon** [comment]
We have a slightly-less-temporary server in place now, so normal builds should be resuming. :+1:

**Comment by tianon** [comment]
This isn't entirely fixed (we're still on a somewhat temporary server), but it's fixed enough that I feel OK closing this now.

**Comment by Dragas** [comment]
Is there a way to check which build servers are up? Currently having issues with this as well.

**Comment by Dragas** [comment]
@tianon I see! Thank you for pointing me to the right direction.
