### ISSUE TITLE
Helm Docker library image

### ISSUE THREAD

**Issue by nicklasfrahm** [docker-library/official-images#4793]
I'd like to propose the creation of a [Helm](https://github.com/helm/helm) Docker library image, which could be used for the deployment to Kubernetes. Currently there are a lot of aftermarket images, but there does not seem to be a canonical Docker Helm image. I'd be happy to create one and submit a PR, but before further action, I wanted to verify the idea.

Best regards
Nicklas

**Comment by tianon** [comment]
For us to consider an official Helm image, it will need the support or blessing of the Helm community and will need to meet the guidelines laid out in https://github.com/docker-library/official-images#readme.

I'm curious why a Helm image is necessary though, and why it should be part of the official images?  Isn't the name of this image something that would be embedded in a YAML file distributed by the Helm project that most users don't bother looking at?  (Thus the benefits of discovery, etc provided by being a top-level "official image" aren't real strong.)  There's some potentially related thoughts on this point at https://github.com/docker-library/official-images/pull/4800#issuecomment-422210085.

(Closing, given that there's nothing actionable for us here.  This is a discussion that needs to happen with the Helm community. :heart:)
