### ISSUE TITLE
Updating official ClefOS image

### ISSUE THREAD

**Issue by nealef** [docker-library/official-images#4812]
Hi,
I am ready to update the ClefOS official image and wondered if you could give me a rundown of what I need to do? I am guessing the following:
 
* Create a new tarball from the 7.5.1804 materials
* Git add the tarball
* Git Commit the changes with the –-amend option
* Push
* Update the official-images/library/clefos file with new release 7.5.1804 – anything else in that need updating?
* Add, commit, and push (is this an amend as well?)
 
I’m sure I’ve missed something or got things in the wrong order so your guidance is greatly appreciated. Make no assumptions of what I know – I won’t take offence if you spell it out in excruciating details!
 
Is there a preferred frequency for updates? I am doing it on a release boundary this time but imagine if there are critical fixes then they should get pushed as soon as practical.
 
Thanks, Neale

**Comment by nealef** [comment]
Thanks, for the ```--force``` reminder.

What's the process for updating the official-images/library/clefos file? It currently looks like this:
```
Maintainers: The ClefOS Project <neale@sinenomine.net> (@nealef)
GitRepo: https://github.com/nealef/clefos.git
Constraints: !aufs

Tags: 7, 7.4.1708, latest
GitFetch: refs/heads/7.4.1708
GitCommit: 002827d6daa02a1c26d53c2571cc9024968f21d2
Architectures: s390x
```
Should it then look like:
```
Maintainers: The ClefOS Project <neale@sinenomine.net> (@nealef)
GitRepo: https://github.com/nealef/clefos.git
Constraints: !aufs

Tags: 7.4.1708
GitFetch: refs/heads/7.4.1708
GitCommit: 002827d6daa02a1c26d53c2571cc9024968f21d2
Architectures: s390x

Tags: 7, 7.5.1804, latest
GitFetch: refs/heads/7.5.1804
GitCommit: 002827d6daa02a1c26d53c2571cc9024968f21d2
Architectures: s390x
```
(i.e. GitCommit is same since I am amending?)

**Comment by tianon** [comment]
When you do an amended commit, it gets a new hash (since the value is actually a hash of the commit contents), so `GitCommit` _will_ need to be updated, and you'll want to remove the `7.4.1708` version entirely (so this new version will replace it).  Removing it here will remove it from the "Supported" section on the Hub readme (and will prevent us from spending cycles rebuilding it on the official build server), but the tag will still be available to users who want it.  (See https://github.com/docker-library/official-images#library-definition-files for more detail on this.)

So what you'll have instead is something like this:

```console
Maintainers: The ClefOS Project <neale@sinenomine.net> (@nealef)
GitRepo: https://github.com/nealef/clefos.git
Constraints: !aufs

Tags: 7, 7.5.1804, latest
GitFetch: refs/heads/7.5.1804
GitCommit: foobarbaz (real commit value here)
Architectures: s390x
```

**Comment by nealef** [comment]
Thanks for the hand-holding! I will take a copy of this issue for future reference!

**Comment by nealef** [comment]
Apologies again for making this tedious for you, but based on this push:
```
$ git push --force
Counting objects: 8, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (5/5), 41.43 MiB | 3.12 MiB/s, done.
Total 5 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To ssh://git@github.com/nealef/clefos.git
 + 002827d...a133843 7.4.1708 -> 7.4.1708 (forced update)
[neale@docker clefos]$ git log
commit a13384382290c7aef7012d1353fee4f84ce8548c
Author: Neale Ferguson <neale@sinenomine.net>
Date:   Mon Jan 22 16:50:54 2018 -0500

    Update to 7.5.1804

commit 76e47dd670fb67ec4e7218d5b5f3a36bd5551f35
Author: Neale Ferguson <neale@sinenomine.net>
Date:   Mon Jan 22 16:48:22 2018 -0500

    Initialize Repository
```
My official-images/library/clefos file will now look like:
```
Maintainers: The ClefOS Project <neale@sinenomine.net> (@nealef)
GitRepo: https://github.com/nealef/clefos.git
Constraints: !aufs

Tags: 7, 7.5.1804, latest
GitFetch: refs/heads/7.5.1804
GitCommit: a13384382290c7aef7012d1353fee4f84ce8548c
Architectures: s390x
```

**Comment by tianon** [comment]
(Closing since this is resolved -- hopefully it's detailed enough for the next round; if not, feel free to add on more questions here next time. :+1:)
