### ISSUE TITLE
Question: Why versioned files?

### ISSUE THREAD

**Issue by thorntonrose** [docker-library/official-images#4842]
Just out of curiosity, why do you use versioned files generated from a template rather than using release branches?

**Comment by tianon** [comment]
https://github.com/docker-library/official-images#repeatability :wink:

We need to ensure that the thing we build/tag as (for example) `mysql:5.7.24` either contains MySQL 5.7.24 (or fails to build/tag), and pinning an explicit version gives us that.  Additionally, we use Docker's build cache very heavily, so having an explicit embedded version ensures that when a cache bust needs to happen (new released version, etc), it happens naturally at the exact point in the `Dockerfile` where the relevant bits we need to fetch have changed.
