### ISSUE TITLE
Lots of ARM64v8 images were cancelled - not re-built since

### ISSUE THREAD

**Issue by lag-linaro** [docker-library/official-images#4881]
At your convenience, please visit: https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/

You will see the red circles down the left-hand side.  It looks as though the ones that match-up with a partly-cloudy sky were interrupted for some reason.  Then not subsequently built.  Before this happened each previous image built successfully.

Please could someone prompt a re-build of those projects.  Or provide me with sufficient permissions to do the same please.  If the latter is possible, I can ensure each of the projects are kept in a nice healthy state at all times.

TIA.

**Comment by tianon** [comment]
We've had Debian and Ubuntu updates in the meantime so most of these images have had at least one attempted rebuild.  All currently failing `arm64v8` builds have had a failing build within the last week that's unrelated to the described incident (like `mono` which I've referenced above).

**Comment by lag-linaro** [comment]
Thanks for following up on this @tianon.  I will take a look to see why they are failing in due course.
