### ISSUE TITLE
Erlang/OTP image

### ISSUE THREAD

**Issue by md5** [docker-library/official-images#495]
I'm opening this issue as a place to discuss the possible inclusion of an official `erlang` image in `official-images`.

It looks like a couple of approaches could be taken here. One would be to use the pre-packaged `*.deb` from [Erlang Solutions](https://www.erlang-solutions.com) as is done in the [`rabbitmq`](https://github.com/docker-library/rabbitmq). Another would be to build Erlang from scratch as is done in a few of the Dockerfiles I found in the wild (https://github.com/correl/docker-erlang being the best one I found).

If the Erlang Solutions approach were taken, it could make sense to change the `rabbitmq` image to be based on `erlang` (or maybe an `erlang:slim` image if the `rebar` and `relx` build tools are too heavy). I believe the Erlang Solutions `*.deb` approach would still make it possible to offer an `erlang` base image for a number of different versions (e.g. `R16` and `R17`).

cc/ @correl

**Comment by yosifkit** [comment]
We are definitely open to additions to the official images. This one is not on the close radar for the docker-library team.  I am +1 to the debs from Erlang Solutions since that is one of the ways that erlang recommends to install (http://www.erlang.org/download.html).

**Comment by md5** [comment]
I started something over at https://github.com/synctree/docker-erlang

Given that I personally know next to nothing about Erlang, I'm not going to volunteer that repo for official image status, but I'm hoping to work on improving the image with a client of ours who uses Erlang. Since they know quite a bit about Erlang, I'm hoping that improvement will happen in the near future.

**Comment by yosifkit** [comment]
We have had an erlang image since https://github.com/docker-library/official-images/pull/1075#event-461528096 :smile: :tada:

**Comment by md5** [comment]
Thanks for the follow-up @yosifkit :metal:
