### ISSUE TITLE
Python-3.7.1 

### ISSUE THREAD

**Issue by davidszotten** [docker-library/official-images#4981]
hi. can we please have an image for python 3.7.1 released a few days ago

looks like it landed in `docker-library/python` [3 days ago](https://github.com/docker-library/python/commit/4437475f468147e441561c3906806ef2cceea409)

**Comment by wglambert** [comment]
It's being pushed now https://github.com/docker-library/official-images/pull/4985

https://github.com/docker-library/python#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet
