### ISSUE TITLE
Please rebuild the influxdb 1.6.4 image

### ISSUE THREAD

**Issue by jsternberg** [docker-library/official-images#4989]
We made a mistake while deploying 1.6.4 and uploaded the 1.6.4 package before it was ready. The docker build was already completed. We have updated the package and the signatures and there are code changes necessary to the dockerfiles.

Is it possible to rebuild the image? Thanks.

**Comment by yosifkit** [comment]
The Dockerfiles are designed to not change versions when rebuilt and so the layer that downloads the `deb` is already in Docker cache and so doing `docker build` again won't change anything.  The best solution is to do a package revision bump and add a `influxdb_1.6.4-1_arch.deb` and then bump the `ENV` in the Dockerfile.

**Comment by jsternberg** [comment]
Is it OK if I modify the Dockerfile to just invalidate the cache? Unfortunately, we can't change the upstream.

**Comment by tianon** [comment]
What do you think about adding a simple checksum to the Dockerfile? That
would fix the current issue naturally and provide a trivial mechanism for
fixing it (again, in a natural way) in the future if it ever happens again.

**Comment by tianon** [comment]
Is this still applicable?

**Comment by jsternberg** [comment]
Not on your end. It is on mine I think, but this can be closed.
