### ISSUE TITLE
Unable to pull Groovy JDK8 image

### ISSUE THREAD

**Issue by keeganwitt** [docker-library/official-images#5082]
Users are reporting they can't pull jdk8: https://github.com/groovy/docker-groovy/issues/41
```
$ docker pull groovy:jdk8
jdk8: Pulling from library/groovy
no matching manifest for unknown in the manifest list entries
```
When I try to pull, I get
```
$ docker pull groovy:jdk8
jdk8: Pulling from library/groovy
no supported platform found in manifest list
```

**Comment by yosifkit** [comment]
Yeah, that is just https://github.com/docker-library/official-images/issues/3835 and the fact that we are still rebuilding almost everything because of https://bugs.debian.org/913614 (https://github.com/docker-library/official-images/pull/5070).

**Comment by mamsterla** [comment]
Still seeing this for MacOS - what is the right way to get a jdk8/jre8 for Groovy-2.5.4?

**Comment by grahamlyons** [comment]
I'm still getting an error pulling a Groovy image:
```
$ docker image pull groovy
Using default tag: latest
latest: Pulling from library/groovy
no matching manifest for unknown in the manifest list entries
```

Looks like  groovy/docker-groovy#43 has been merged; does that mean the build should be fixed or will there be a wait?

**Comment by keeganwitt** [comment]
Gotta wait until it gets merged into the repo Docker Library builds from: https://github.com/docker-library/official-images/pull/5165

**Comment by grahamlyons** [comment]
Gotcha. Thanks.

**Comment by keeganwitt** [comment]
Build is [complete](https://travis-ci.org/docker-library/official-images/builds/466814944) and I'm able to pull now.
