### ISSUE TITLE
Support Children and Parents with namespaces

### ISSUE THREAD

**Issue by kilmore** [docker-library/official-images#5083]
I can successfully use namespace to build, tag and push for my private docker repository.  It looks like in order to use the plumbing commands (Children and Parents) the name of them manifest much match the from in the dockerfile. For example if my manifest filename is mightymouse the the from must be something like FROM mightymouse:1.0, not FROM kilmore/mightymouse:1.0. 

The use case is for determining what dependent containers need to be updated when a base image is changed. 

An "easy way" may be to allow for namespace usage in the plumbing.  I am happy to take a crack at this

Thanks!

**Comment by kilmore** [comment]
Pinging, hoping to get a response.

**Comment by yosifkit** [comment]
Sorry for the delay.

We do have a similar situation on each of our architecture builders. We push all the images to namespaces like `amd64` or `arm64v8` but build all the images un-prefixed on the host they run and just tag and push to the correct namespace. This does mean that all our Dockerfiles are always `FROM` the non-namespaced names which may not fit your use case. Anything pushed to the empty namespace is only done with manifest lists via `put-shared`.  (see also [jenkins config repo](https://github.com/docker-library/oi-janky-groovy))

But this does seem reasonable to me; I'm just not sure how deeply the assumption of `FROM` always being non-namespaced is.

What do you think @tianon?

**Comment by tianon** [comment]
I technically have the same issue with a lot of my `tianon/*` images, but I don't often build them `FROM` one another across repos so it doesn't really affect me much.

I definitely share the concerns about how deeply our non-namespaced assumptions go (since we've been assuming that for a long time :sweat_smile:).

**Comment by kilmore** [comment]
Would you be up for me making a modification to basbhrew to support namespaces in the "FROM" dependency tree (which would solve my specific issue). I can make the change and do a pull request.

**Comment by tianon** [comment]
This was fixed by #6054! :+1:
