### ISSUE TITLE
an official network utilities image

### ISSUE THREAD

**Issue by xenoterracide** [docker-library/official-images#5105]
I would love to see a network tools image, that contains tools such as `whois`, `mtr`, `trace`, `ip`, `dig`, `ssh`, `telnet`, etc. currently there are a lot of unofficial images of this sort, but would be nice to have an official image that was safe to run.

**Comment by xenoterracide** [comment]
I'll look into that, but the upstream product that contains this... varies per name, depending on distro... should I request multiple images?

**Comment by xenoterracide** [comment]
I could request separate for bind-tools, and mtr, and whois

**Comment by tianon** [comment]
I think `bind-tools` is a perfect example from which to start -- one of the mailing lists on https://www.isc.org/downloads/bind/ would probably be the appropriate place to hit them up to see if they're interested in participating in this program.

**Comment by J0WI** [comment]
A `bind` image would be great to have in general.

**Comment by tianon** [comment]
That's something to talk to the `bind` community about -- I'm going to close this since it isn't immediately actionable.
