### ISSUE TITLE
Make sure that `gem install json -v '1.8.2'` succeeds before bundling.

### ISSUE THREAD

**Issue by paulomcnally** [docker-library/official-images#522]
Sending build context to Docker daemon 26.47 MB
    Sending build context to Docker daemon 
    Step 0 : FROM rails:onbuild
    # Executing 4 build triggers
    Trigger 0, COPY Gemfile /usr/src/app/
    Step 0 : COPY Gemfile /usr/src/app/
     ---> Using cache
    Trigger 1, COPY Gemfile.lock /usr/src/app/
    Step 0 : COPY Gemfile.lock /usr/src/app/
     ---> Using cache
    Trigger 2, RUN bundle install
    Step 0 : RUN bundle install
     ---> Running in 526e7579b1ee
    Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
    installing your bundle as root will break this application for all non-root
    users on this machine.
    Fetching source index from https://rubygems.org/
    Using rake 10.4.2
    Installing i18n 0.7.0
    
    Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
    
        /usr/local/bin/ruby -r ./siteconf20150226-8-13s6qdv.rb extconf.rb 
    Cannot allocate memory - /usr/local/bin/ruby -r ./siteconf20150226-8-13s6qdv.rb extconf.rb  2>&1
    
    Gem files will remain installed in /usr/local/bundle/gems/json-1.8.2 for inspection.
    Results logged to /usr/local/bundle/extensions/x86_64-linux/2.2.0-static/json-1.8.2/gem_make.out
    An error occurred while installing json (1.8.2), and Bundler cannot continue.
    Make sure that `gem install json -v '1.8.2'` succeeds before bundling.
    INFO[0156] The command [/bin/sh -c bundle install] returned a non-zero code: 5 

## Dockerfile

    FROM rails:onbuild

## Gemfile

    source 'https://rubygems.org'
    
    ruby '2.2.0'
    
    gem 'rails', '4.2.0'
    gem 'sass-rails', '~> 5.0'
    gem 'uglifier', '>= 1.3.0'
    gem 'coffee-rails', '~> 4.1.0'
    gem 'jquery-rails'
    gem 'turbolinks'
    gem 'jbuilder', '~> 2.0'
    gem 'sdoc', '~> 0.4.0', group: :doc
    gem 'devise'
    gem 'dalli'
    gem 'monetize'
    gem 'pg'
    gem 'bower-rails', '~> 0.9.1'
    gem 'momentjs-rails', '>= 2.9.0'
    gem 'bootstrap3-datetimepicker-rails', '~> 4.0.0'
    gem 'devise_invitable'
    gem 'apartment'
    gem 'therubyracer'
    gem 'less-rails'
    gem 'puma'
    gem 'newrelic_rpm'
    gem 'sentry-raven'
    
    group :development do
      gem 'better_errors'
      gem 'guard-ctags-bundler'
      gem 'rb-readline'
      gem 'pry-rails'
      gem 'quiet_assets'
    end
    
    group :development, :test do
      gem 'byebug'
      gem 'guard'
      gem 'rails_12factor'
      # gem 'guard-livereload'
      # gem 'rack-livereload'
      gem 'web-console', '~> 2.0'
      gem 'spring'
    end

## Gemfile.lock

    GEM
      remote: https://rubygems.org/
      specs:
        actionmailer (4.2.0)
          actionpack (= 4.2.0)
          actionview (= 4.2.0)
          activejob (= 4.2.0)
          mail (~> 2.5, >= 2.5.4)
          rails-dom-testing (~> 1.0, >= 1.0.5)
        actionpack (4.2.0)
          actionview (= 4.2.0)
          activesupport (= 4.2.0)
          rack (~> 1.6.0)
          rack-test (~> 0.6.2)
          rails-dom-testing (~> 1.0, >= 1.0.5)
          rails-html-sanitizer (~> 1.0, >= 1.0.1)
        actionview (4.2.0)
          activesupport (= 4.2.0)
          builder (~> 3.1)
          erubis (~> 2.7.0)
          rails-dom-testing (~> 1.0, >= 1.0.5)
          rails-html-sanitizer (~> 1.0, >= 1.0.1)
        activejob (4.2.0)
          activesupport (= 4.2.0)
          globalid (>= 0.3.0)
        activemodel (4.2.0)
          activesupport (= 4.2.0)
          builder (~> 3.1)
        activerecord (4.2.0)
          activemodel (= 4.2.0)
          activesupport (= 4.2.0)
          arel (~> 6.0)
        activesupport (4.2.0)
          i18n (~> 0.7)
          json (~> 1.7, >= 1.7.7)
          minitest (~> 5.1)
          thread_safe (~> 0.3, >= 0.3.4)
          tzinfo (~> 1.1)
        apartment (0.26.1)
          activerecord (>= 3.1.2, < 5.0)
          rack (>= 1.3.6)
        arel (6.0.0)
        bcrypt (3.1.10)
        better_errors (2.1.1)
          coderay (>= 1.0.0)
          erubis (>= 2.6.6)
          rack (>= 0.9.0)
        binding_of_caller (0.7.2)
          debug_inspector (>= 0.0.1)
        bootstrap3-datetimepicker-rails (4.0.0)
          momentjs-rails (>= 2.8.1)
        bower-rails (0.9.2)
        builder (3.2.2)
        byebug (3.5.1)
          columnize (~> 0.8)
          debugger-linecache (~> 1.2)
          slop (~> 3.6)
        celluloid (0.16.0)
          timers (~> 4.0.0)
        coderay (1.1.0)
        coffee-rails (4.1.0)
          coffee-script (>= 2.2.0)
          railties (>= 4.0.0, < 5.0)
        coffee-script (2.3.0)
          coffee-script-source
          execjs
        coffee-script-source (1.9.0)
        columnize (0.9.0)
        commonjs (0.2.7)
        dalli (2.7.2)
        debug_inspector (0.0.2)
        debugger-linecache (1.2.0)
        devise (3.4.1)
          bcrypt (~> 3.0)
          orm_adapter (~> 0.1)
          railties (>= 3.2.6, < 5)
          responders
          thread_safe (~> 0.1)
          warden (~> 1.2.3)
        devise_invitable (1.4.0)
          actionmailer (>= 3.2.6, < 5)
          devise (>= 3.2.0)
        erubis (2.7.0)
        execjs (2.3.0)
        faraday (0.9.1)
          multipart-post (>= 1.2, < 3)
        ffi (1.9.6)
        formatador (0.2.5)
        globalid (0.3.3)
          activesupport (>= 4.1.0)
        guard (2.12.1)
          formatador (>= 0.2.4)
          listen (~> 2.7)
          lumberjack (~> 1.0)
          nenv (~> 0.1)
          notiffany (~> 0.0)
          pry (>= 0.9.12)
          shellany (~> 0.0)
          thor (>= 0.18.1)
        guard-compat (1.2.1)
        guard-ctags-bundler (1.3.1)
          guard (>= 2.0)
          guard-compat (>= 0.1.0)
        hike (1.2.3)
        hitimes (1.2.2)
        i18n (0.7.0)
        jbuilder (2.2.6)
          activesupport (>= 3.0.0, < 5)
          multi_json (~> 1.2)
        jquery-rails (4.0.3)
          rails-dom-testing (~> 1.0)
          railties (>= 4.2.0)
          thor (>= 0.14, < 2.0)
        json (1.8.2)
        less (2.6.0)
          commonjs (~> 0.2.7)
        less-rails (2.6.0)
          actionpack (>= 3.1)
          less (~> 2.6.0)
        libv8 (3.16.14.7)
        listen (2.8.5)
          celluloid (>= 0.15.2)
          rb-fsevent (>= 0.9.3)
          rb-inotify (>= 0.9)
        loofah (2.0.1)
          nokogiri (>= 1.5.9)
        lumberjack (1.0.9)
        mail (2.6.3)
          mime-types (>= 1.16, < 3)
        method_source (0.8.2)
        mime-types (2.4.3)
        mini_portile (0.6.2)
        minitest (5.5.1)
        momentjs-rails (2.9.0)
          railties (>= 3.1)
        monetize (1.1.0)
          money (~> 6.5.0)
        money (6.5.1)
          i18n (>= 0.6.4, <= 0.7.0)
        multi_json (1.10.1)
        multipart-post (2.0.0)
        nenv (0.2.0)
        newrelic_rpm (3.9.9.275)
        nokogiri (1.6.6.2)
          mini_portile (~> 0.6.0)
        notiffany (0.0.5)
          nenv (~> 0.1)
          shellany (~> 0.0)
        orm_adapter (0.5.0)
        pg (0.18.1)
        pry (0.10.1)
          coderay (~> 1.1.0)
          method_source (~> 0.8.1)
          slop (~> 3.4)
        pry-rails (0.3.3)
          pry (>= 0.9.10)
        puma (2.11.1)
          rack (>= 1.1, < 2.0)
        quiet_assets (1.1.0)
          railties (>= 3.1, < 5.0)
        rack (1.6.0)
        rack-test (0.6.3)
          rack (>= 1.0)
        rails (4.2.0)
          actionmailer (= 4.2.0)
          actionpack (= 4.2.0)
          actionview (= 4.2.0)
          activejob (= 4.2.0)
          activemodel (= 4.2.0)
          activerecord (= 4.2.0)
          activesupport (= 4.2.0)
          bundler (>= 1.3.0, < 2.0)
          railties (= 4.2.0)
          sprockets-rails
        rails-deprecated_sanitizer (1.0.3)
          activesupport (>= 4.2.0.alpha)
        rails-dom-testing (1.0.5)
          activesupport (>= 4.2.0.beta, < 5.0)
          nokogiri (~> 1.6.0)
          rails-deprecated_sanitizer (>= 1.0.1)
        rails-html-sanitizer (1.0.1)
          loofah (~> 2.0)
        rails_12factor (0.0.3)
          rails_serve_static_assets
          rails_stdout_logging
        rails_serve_static_assets (0.0.4)
        rails_stdout_logging (0.0.3)
        railties (4.2.0)
          actionpack (= 4.2.0)
          activesupport (= 4.2.0)
          rake (>= 0.8.7)
          thor (>= 0.18.1, < 2.0)
        rake (10.4.2)
        rb-fsevent (0.9.4)
        rb-inotify (0.9.5)
          ffi (>= 0.5.0)
        rb-readline (0.5.2)
        rdoc (4.2.0)
        ref (1.0.5)
        responders (2.1.0)
          railties (>= 4.2.0, < 5)
        sass (3.4.11)
        sass-rails (5.0.1)
          railties (>= 4.0.0, < 5.0)
          sass (~> 3.1)
          sprockets (>= 2.8, < 4.0)
          sprockets-rails (>= 2.0, < 4.0)
          tilt (~> 1.1)
        sdoc (0.4.1)
          json (~> 1.7, >= 1.7.7)
          rdoc (~> 4.0)
        sentry-raven (0.12.3)
          faraday (>= 0.7.6)
        shellany (0.0.1)
        slop (3.6.0)
        spring (1.3.1)
        sprockets (2.12.3)
          hike (~> 1.2)
          multi_json (~> 1.0)
          rack (~> 1.0)
          tilt (~> 1.1, != 1.3.0)
        sprockets-rails (2.2.4)
          actionpack (>= 3.0)
          activesupport (>= 3.0)
          sprockets (>= 2.8, < 4.0)
        therubyracer (0.12.1)
          libv8 (~> 3.16.14.0)
          ref
        thor (0.19.1)
        thread_safe (0.3.4)
        tilt (1.4.1)
        timers (4.0.1)
          hitimes
        turbolinks (2.5.3)
          coffee-rails
        tzinfo (1.2.2)
          thread_safe (~> 0.1)
        uglifier (2.7.0)
          execjs (>= 0.3.0)
          json (>= 1.8.0)
        warden (1.2.3)
          rack (>= 1.0)
        web-console (2.0.0)
          activemodel (~> 4.0)
          binding_of_caller (>= 0.7.2)
          railties (~> 4.0)
          sprockets-rails (>= 2.0, < 4.0)
    
    PLATFORMS
      ruby
    
    DEPENDENCIES
      apartment
      better_errors
      bootstrap3-datetimepicker-rails (~> 4.0.0)
      bower-rails (~> 0.9.1)
      byebug
      coffee-rails (~> 4.1.0)
      dalli
      devise
      devise_invitable
      guard
      guard-ctags-bundler
      jbuilder (~> 2.0)
      jquery-rails
      less-rails
      momentjs-rails (>= 2.9.0)
      monetize
      newrelic_rpm
      pg
      pry-rails
      puma
      quiet_assets
      rails (= 4.2.0)
      rails_12factor
      rb-readline
      sass-rails (~> 5.0)
      sdoc (~> 0.4.0)
      sentry-raven
      spring
      therubyracer
      turbolinks
      uglifier (>= 1.3.0)
      web-console (~> 2.0)

**Comment by md5** [comment]
That `Cannot allocate memory` looks suspicious.

I was just able to build with this `Gemfile` instead of yours:

```Dockerfile
source 'https://rubygems.org'
gem 'json'
```

**Comment by paulomcnally** [comment]
Thanks @md5

**Comment by md5** [comment]
:bow

**Comment by h4wlt** [comment]
I had this same error, the issue I had was due to using a shared file system on Vagrant and windows:

http://joequery.me/guides/bundle-install-text-file-busy/

**Comment by Bv2124** [comment]
i have the error like this when i create a new folder in react native with cli ......using Mac to build android 

An error occurred while installing json (2.6.3), and Bundler cannot continue.
Make sure that `gem install json -v '2.6.3' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  cocoapods was resolved to 1.12.1, which depends on
    cocoapods-core was resolved to 1.12.1, which depends on
      algoliasearch was resolved to 1.27.5, which depends on
        json

✖ Installing Bundler
error Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
Error: Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
<img width="1265" alt="Screenshot 2023-05-30 at 7 27 04 PM" src="https://github.com/docker-library/official-images/assets/115614444/b1cb59ab-afe1-4e30-b0d4-6e77c9314b35">
<img width="447" alt="Screenshot 2023-05-30 at 7 26 27 PM" src="https://github.com/docker-library/official-images/assets/115614444/7a3c8b40-9d75-4f0d-8688-41d346797c7e">
