### ISSUE TITLE
Please update base images frequently.

### ISSUE THREAD

**Issue by NodeGuy** [docker-library/official-images#53]
I see a pattern in many Dockerfiles that looks like this:

```
FROM debian
RUN apt-get update
RUN apt-get --assume-yes dist-upgrade
```

This is redundant and misplaced--it shouldn't be the responsibility of the dependent containers to update the base images.

Can you rebuild the base images frequently enough that `apt-get update` isn't necessary in the dependent containers?  Daily?  Hourly if need be?

Another benefit is that dependent builds would benefit from important security updates quickly (like the Heartbleed fix).

**Comment by devurandom** [comment]
I do not understand how updates to base images are pulled into my system.

Take for example these images on my installation:
```
$ docker images
REPOSITORY           TAG                         IMAGE ID            CREATED              VIRTUAL SIZE
[…]
ubuntu               14.04                       5506de2b643b        11 weeks ago         199.3 MB
ubuntu               latest                      5506de2b643b        11 weeks ago         199.3 MB
```

The Ubuntu image is certainly outdated, since [the official-images repository](https://github.com/docker-library/official-images/blob/master/library/ubuntu) was updated "20 days ago" (according to github). Still the image on my system is far older. Why?

**Comment by Moghedrin** [comment]
@devurandom Your local image doesn't get updated automatically - therefore, the ubuntu image on your machine represents what was available when you last pulled it from the official repo.

If you would like to update your Ubuntu image to match what is currently in the repo, you need to run `docker pull ubuntu`, and then rebuild any of your images that are `from ubuntu`.

As far as the Ubuntu image in the official-images repository being outdated, we update the Ubuntu image as soon as upstream releases their core tarball. If you feel that is not frequent enough, take it up Canonical.

**Comment by devurandom** [comment]
Thanks for this hint!

("outdated" was referring to the image on my system, not to the ones provided by you.)

**Comment by yosifkit** [comment]
`docker pull -a ubuntu` will pull all tags associated with ubuntu (which might be more than you currently have), or just `docker pull ubuntu:tag` for each version you need.

**Comment by Moghedrin** [comment]
Oooh, good catch @yosifkit. Definitely something I should have mentioned! :+1:
