### ISSUE TITLE
Logstash installation extracting from tar.gz

### ISSUE THREAD

**Issue by Moghedrin** [docker-library/official-images#531]
There was some discussion in #530 as to whether installing via their binaries they distribute is the best way to go. In interest of getting the image into the library, @md5 agreed that moving the discussion here sounded good.

Any thoughts/opinions on this matter?

**Comment by md5** [comment]
Looks like @tianon opened docker-library/logstash#3. It's probably better to discuss there.

**Comment by Moghedrin** [comment]
Good call - missed that XD
