### ISSUE TITLE
Orphan branch usage for docker-library repos prevents forks of upstream

### ISSUE THREAD

**Issue by md5** [docker-library/official-images#538]
I just wanted to fork `elasticsearch/elasticseach` to make a fix and found that I can't do so through the Github web interface because I already forked `docker-library/elasticsearch`. Since this is a practice that is common across many of the `docker-library` repositories, I thought I'd raise it as an issue here.

I can of course manually create my own `md5/elasticsearch` repo and push `elasticsearch/elasticsearch` to it, but this makes it harder for me to do PRs against the upstream repo because it wouldn't be consider part of my fork network in that case.

As a workaround, I've forked the original `elasticsearch/elasticsearch` repo into a different organization instead of into my user account, but I don't see what the use of forks and orphan branches as is done in the `docker-library` repos is buying anyone.

**Comment by yosifkit** [comment]
Good point. Originally it was to build from source and hope that they would incorporate it into their repos.  That proved too cumbersome to support multiple versions, but I would not be opposed to somehow fixing the problem.  We currently fork them to have nice links to the upstream repo.

Thoughts @tianon?

**Comment by tianon** [comment]
Just sadness.  Is there any way to force GitHub to disconnect without
deleting the repo?  I'd rather not lose all our watchers. :disappointed:

**Comment by md5** [comment]
I'd try contacting support@github.com to explain the situation. I'd assume
they can unlink the forks on the backend without losing watchers and other
valuable information.

**Comment by tianon** [comment]
Sent out a feeler via https://github.com/contact to see what they can do to help us. :+1:

**Comment by md5** [comment]
There isn't a :crossed_fingers: emoji, so I'll settle for this: :children_crossing:

**Comment by tianon** [comment]
There's good news, and there's bad news.

> Hi Tianon,
> I've queued up detach jobs for the repositories you listed.

(which has already started happening :dancer:)

> Due to the size of the repository networks. We're not able to extract your repositories and their forks from the network. Your collaborators will need to create new forks to continue contributing.

So, that's a downer, but at least it's a manageable one.  No idea how to get the word out very effectively. :disappointed:

**Comment by md5** [comment]
I'm not aware of any forks of the `docker-library` repos that have a significant amount of their owner watchers or stars other than their owners, so hopefully that shouldn't be a big problem.

**Comment by md5** [comment]
That being said, this look correct to me: https://github.com/docker-library/mysql/network/members

**Comment by md5** [comment]
This on the other hand does not: https://github.com/docker-library/postgres/network/members

**Comment by yosifkit** [comment]
Yeah, such sadness.  I think mysql was not originally forked from anything so it would be fine.

**Comment by yosifkit** [comment]
I was trying to craft a search for the now orphaned repos so that we would be able to let users know, but it seems that github won't let me search them.
> repository forks will not be searchable unless the fork has more stars than the parent repository

**Comment by yosifkit** [comment]
So, should we notify people somehow?  Maybe put a note in the README.md in each repo?  Maybe create an issue in each for those that are watching?  Or just do nothing?

**Comment by yosifkit** [comment]
FYI, you can get quite a few with a google search `site:github.com "This is the Git repo of the official Docker image for"`

**Comment by md5** [comment]
Adding a note to the `README.md` sounds workable since most of the forks probably won't have Issues enabled.

As for getting the list of forks, perhaps Github is able to get it from archived data. I know that the "members" tab under the fork network used to show forks or forks correctly (e.g. my forks of docker-library repos showed up under the docker-library fork).

**Comment by md5** [comment]
I was thinking about this some more and wondering how feasible it would be to look at the list of forks in the base repository and see if they contain the same root commit as the `docker-library` repos. I think it should be reasonably straightforward to write such a script and get the list of forks that way, assuming GH can't just tell you.

**Comment by md5** [comment]
So much for that idea: https://github.com/tcsoares84/php-src/commit/80f855114cb4c44eef7aa2a0e22a07e40e97cc03

Looks like the Github API will tell you that commits are part of forks they're not actually part of...

**Comment by md5** [comment]
Unless you guys would like to keep this open for some reason, I'm going to close it.

**Comment by tianon** [comment]
Last I checked we were still in-queue on a few repos -- if they've all cleared, then yeah, let's close this. :+1:

**Comment by tianon** [comment]
Doing a quick scan, it looks like `percona`, `memcached`, and `gcc` are still waiting.

**Comment by tianon** [comment]
Oh, and `httpd`

**Comment by tianon** [comment]
We're finished. :tada:

**Comment by md5** [comment]
The good things in life are worth waiting for :+1:
