### ISSUE TITLE
Ruby 2.6.1

### ISSUE THREAD

**Issue by n-rodriguez** [docker-library/official-images#5381]
Hi there!

It would be nice to have an upgraded version of Docker Ruby.

Thank you!

**Comment by tianon** [comment]
Duplicate of https://github.com/docker-library/ruby/issues/263

I'm on my phone ATM, but if you wanted to help out, you could clone that repository, run `./generate-stackbrew-library.sh`, and open a PR here replacing the contents of `library/ruby` with the output. 👍
