### ISSUE TITLE
Support named Dockerfiles

### ISSUE THREAD

**Issue by md5** [docker-library/official-images#549]
It would be nice if the `official-images` library file format supported named Dockerfiles.

To get the discussion rolling, here's my proposal:

```
# maintainer: io.js Docker team <https://github.com/iojs/docker-iojs> (@iojs)

1.5.1: git://github.com/iojs/docker-iojs@cee0ed5c5bd6db332e6738722158904709e348b4 1.5
1.5: git://github.com/iojs/docker-iojs@cee0ed5c5bd6db332e6738722158904709e348b4 1.5
1: git://github.com/iojs/docker-iojs@cee0ed5c5bd6db332e6738722158904709e348b4 1.5
latest: git://github.com/iojs/docker-iojs@cee0ed5c5bd6db332e6738722158904709e348b4 1.5

1.5.1-onbuild: git://github.com/iojs/docker-iojs@cee0ed5c5bd6db332e6738722158904709e348b4 -f 1.5/Dockerfile.onbuild 1.5
1.5-onbuild: git://github.com/iojs/docker-iojs@cee0ed5c5bd6db332e6738722158904709e348b4 -f 1.5/Dockerfile.onbuild 1.5
1-onbuild: git://github.com/iojs/docker-iojs@cee0ed5c5bd6db332e6738722158904709e348b4 -f 1.5/Dockerfile.onbuild 1.5
onbuild: git://github.com/iojs/docker-iojs@cee0ed5c5bd6db332e6738722158904709e348b4 -f 1.5/Dockerfile.onbuild 1.5

1.5.1-slim: git://github.com/iojs/docker-iojs@e192fd115bd720eca40d6281f5e9ab92a30817d6 -f 1.5/Dockerfile.slim 1.5
1.5-slim: git://github.com/iojs/docker-iojs@e192fd115bd720eca40d6281f5e9ab92a30817d6 -f 1.5/Dockerfile.slim 1.5
1-slim: git://github.com/iojs/docker-iojs@e192fd115bd720eca40d6281f5e9ab92a30817d6 -f 1.5/Dockerfile.slim 1.5
slim: git://github.com/iojs/docker-iojs@e192fd115bd720eca40d6281f5e9ab92a30817d6 -f 1.5/Dockerfile.slim 1.5
```

Basically, support this format:

```
TAG: URL@REF [-f CTX/Dockerfile.named] [CTX]
```

**Comment by yosifkit** [comment]
@tianon and I had discussed this.  I think it was basically this exact syntax too :heart_eyes:.  The current problem is the build server.  It is stuck on a patched version of 1.4, because of the preview v2 registry in python that gave the "this image is verified" message for official images in 1.3.

**Comment by tianon** [comment]
Yeah, this syntax would be sexy because it would basically mean that `bashbrew` just has to take whatever comes after the `git` refs and tack it on the end of `docker build -t ...` as-is. :+1:

Once we can update the build server to 1.5+, let's revisit this.

**Comment by md5** [comment]
> Once we can update the build server to 1.5+, let's revisit this.

SGTM

**Comment by yosifkit** [comment]
So, even with our recent addition of `windowsservercore` based images we have not needed a different named Dockerfile (or even a Dockerfile deeper in the build context).  I'm closing this old issue, but am willing to discuss it if the need for it arises.

**Comment by 7AC** [comment]
This would be useful for building images running Go binaries: it's not uncommon for a Go repo to have a structure like:

```
cmd/
    app1/
        main.go
    app2/
        main.go
Dockerfile-app1
Dockerfile-app2
```

Typically each Dockerfile needs access to the root of the repo in order to build the app, to access some shared libraries and whatnot, hence they cannot be placed in the respective subdirs to resolve the name collision.

**Comment by 7AC** [comment]
I posted a PR here: https://github.com/docker-library/go-dockerlibrary/pull/16

The follow-up would be https://github.com/aristanetworks/official-images/commit/121516b7b0e6a33df2bd22ea24c29f29f4a70f9e but it needs this one to vendor it.
