### ISSUE TITLE
Ghost outdated

### ISSUE THREAD

**Issue by letsjustfixit** [docker-library/official-images#558]
Hey,
There is a new ghost release out there. May I ask who is the official maintainer of that repository?
It might be actually a good idea to have automated builds on relases (could be fetched and checked via releases.atom)
Thanks!

**Comment by md5** [comment]
Looks like this has been updated but not pushed yet: https://github.com/docker-library/ghost/commit/2b93aa26432d878a6d3b40d8cdc918a103ed2661

**Comment by letsjustfixit** [comment]
yepp ive seen it and even built my local image based on it but it would be nice if i could just docker pull ghost instead :)

**Comment by johnjelinek** [comment]
I submitted #559
