### ISSUE TITLE
arm*/node missing tags

### ISSUE THREAD

**Issue by tbe** [docker-library/official-images#5584]
The `arm64v8/node` image is missing some tags. While `arm64v8/node:6.17-alpine` is available from the registry, `arm64v8/node:6-alpine` is not. 

According to https://github.com/xwiki-labs/cryptpad/pull/347#issuecomment-475260431_ this does happen frequently.

**Comment by tianon** [comment]
Looking at https://doi-janky.infosiftr.net/job/multiarch/view/images/view/node/, the latest builds on `arm*/node` have been successful.  Looking at the manifest file, `arm*` is supported on `node:6-alpine`:

https://github.com/docker-library/official-images/blob/fc7f5ff17986df5842d16ba1c615277ece7ff2f4/library/node#L46-L49

Looking at the build log for `arm64v8`, it would appear there's perhaps been a glitch in the Docker Hub API such that it believes the image is pushed when something must have actually failed:

```console
$ manifest-tool inspect arm64v8/node:6-alpine
FATA[0001] manifest unknown: manifest unknown           
```

:disappointed:

**Comment by tianon** [comment]
Figured out a reasonable way to check for the full impact across a repo, and found that this affected all of `arm64v8/node:6.17.0-alpine`, `arm64v8/node:6-alpine`, and `arm64v8/node:6.17-stretch-slim`, which I've pushed all of manually now (and the manifest list at `node:6-alpine` should also update soonish). :+1:
