### ISSUE TITLE
[test] rename python-zlib to python-imports and add bz2

### ISSUE THREAD

**Issue by tianon** [docker-library/official-images#560]
As pointed out in https://github.com/docker-library/python/issues/39, we need to make sure `bz2` loads correctly (especially since it can't be added/fixed after the fact).

To do this, we should rename the current `python-zlib` test to something like `python-imports` and have it do some very rudimentary round-tripping via `bz2` like it does `zlib`.

**Comment by tianon** [comment]
I hear whispers that @yosifkit might want to bikeshed the actual test name to `python-standard-libs` or something to match that one Ruby test we've got.

**Comment by yosifkit** [comment]
That is true. I was thinking that we can include more tests in this one, unless we want to break them out into smaller logical groupings of tests.

If we keep them in one test:
 - it gets big
 - easy comparison of coverage to standard libs
if we split them up:
 - more manageable set of items to test
 - bikeshedding on what the classifications are
    - examples could include: compression, file IO, database interaction, ...
 - we might misclassify one
 - forget one altogether

**Comment by tianon** [comment]
Yeah, one big test isn't likely to have good coverage of verifying actual functionality either, but I'm not totally convinced that we need that (or that it'd be a good thing in general), especially since the core modules straight up fail to load if the support isn't there.

**Comment by denibertovic** [comment]
@tianon @yosifkit So what's the agreed approach here? I'm asking so I can fix the issue that @tianon linked at the beginning.

**Comment by yosifkit** [comment]
Fixing the bug over in `python:slim` should not affect improvements to this test.  Were you looking to make a PR here too? Whether or not you do, I think that we should just rename the test like the title suggests and add a bz2 case in the [python script](https://github.com/docker-library/official-images/blob/master/test/tests/python-zlib/container.py).  If there are other obvious libs to test importing, those are definitely welcome in this test as well.

**Comment by denibertovic** [comment]
@yosifkit yeah I agree that this doesn't keep the stuff over at `python:slim` from being merged. I will however try and add a separate PR for this as well. Thanks.
