### ISSUE TITLE
python:3.6-alpine "unsupported manifest media type and no default available"

### ISSUE THREAD

**Issue by groodt** [docker-library/official-images#5600]
I'm having some issues pulling down the python:3.6-alpine image.

```
❯ docker manifest inspect index.docker.io/python:3.6-alpine
unsupported manifest media type and no default available: application/vnd.docker.distribution.manifest.v1+prettyjws
```

Other versions of python and alpine are working. As does `python:3.6-stretch`.

```
❯ docker manifest inspect index.docker.io/python:3.5-alpine
WORKS
```

```
❯ docker manifest inspect index.docker.io/python:3.6-alpine
FAILS
```

```
❯ docker manifest inspect index.docker.io/python:3.6-stretch
WORKS
```

```
❯ docker manifest inspect index.docker.io/python:3.7-alpine
WORKS
```

Any ideas? It feels like the image needs to be republished, but I'm not sure.

Note: I've opened the same issue at: https://github.com/docker-library/python/issues/385
I'm not sure which project is more appropriate, I'll close the duplicate issue once confirmed.

**Comment by yosifkit** [comment]
Closing in favor of docker-library/python#385
