### ISSUE TITLE
[Question] Adding a "runtime" image for Swift

### ISSUE THREAD

**Issue by ianpartridge** [docker-library/official-images#5651]
(I am [one of the maintainers](https://github.com/docker-library/official-images/blob/29958f4d83cd21938c43fec7410e2e3316195e98/library/swift#L6) of the Swift images.)

Currently, the Swift images come "batteries included" with everything users need to explore the Swift language, build and run programs etc. This means that the images are rather large and include a lot of system packages which are required by the Swift Package Manager and compiler etc.

There is interest in the Swift community in also having a "Swift runtime" image. This would be smaller and only include the system packages and artifacts needed to run an already compiled Swift program. Such an image could perhaps be available via `docker pull swift:runtime`.

Users could then use a multistage `Dockerfile` to produce their final images. Something like (showing the principle only):

```dockerfile
FROM swift:latest as builder
WORKDIR /root
COPY . .
RUN swift build

FROM swift:runtime
WORKDIR /root
COPY --from=builder /root .
CMD ["compiled-binary"]
```

I have prototyped this approach and it seems to work. A similar idea is discussed in this [blog post from Bitnami](https://engineering.bitnami.com/articles/production-variants-of-language-runtime-images-for-docker.html).

My question is whether there are any pitfalls or issues we should be aware of with this approach, and whether the Docker Official Images program would be happy to accept these images.  Thanks.

**Comment by tianon** [comment]
Does Swift use a VM at runtime?  Shouldn't the compiled binary be usable without a "runtime" image?

What you've described sounds very similar to what we typically call "slim" images (see `ruby:slim`, `python:slim`, `openjdk:slim`, etc), where instead of including the full kitchen sink, they only include the bare minimum necessary to run the given tool and everything else is bring-your-own (which typically results in a dramatically smaller image footprint, hence the name "slim").

**Comment by ianpartridge** [comment]
Swift does not use a VM as it is a compiled language. However, Swift does have a runtime which is a collection of shared libraries in `/usr/lib/swift/` that Swift applications dynamically link against. We would envisage including these shared libraries in our "runtime"/"slim" image, along with the system packages that are also required.

Thanks for the pointer towards the other slim images. These looks like the model we should use (it would be nice if the slim image could be defined using a multistage build to copy things out of the full image but it seems that's not currently possible).

Many thanks.
