### ISSUE TITLE
Alpine: multi-arch builders not picking up new changes

### ISSUE THREAD

**Issue by tuan-hoang1** [docker-library/official-images#5708]
Hello,

alpine:3.9.3 (stable) and alpine:20190408 (edge) just got released 2 days ago.

It seems amd64, arm32v6, ppc64le builders have picked up the change and build alpine images.
https://doi-janky.infosiftr.net/job/multiarch/job/arm32v6/job/alpine/
https://doi-janky.infosiftr.net/job/multiarch/job/ppc64le/job/alpine/

```
# DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect alpine:latest | grep arch
            "architecture": "amd64",
            "architecture": "arm",
            "architecture": "ppc64le",
```

The s390x builder however has not received/checked the new change: 
https://doi-janky.infosiftr.net/job/multiarch/job/s390x/job/alpine/

Is there something I could help to make it build the s390x image ?

cc @tianon 
Thanks !

**Comment by tuan-hoang1** [comment]
It seems `s390x` got built : https://doi-janky.infosiftr.net/job/multiarch/job/s390x/job/alpine/

It looks like the builders build the multi-arch images in serial ?

**Comment by tianon** [comment]
Looks like a classic case of https://github.com/docker-library/official-images/issues/3835.
