### ISSUE TITLE
WebSphere Liberty tags not updated

### ISSUE THREAD

**Issue by arthurdm** [docker-library/official-images#5850]
We had a PR for 19.0.0.4 merged earlier this week, and I can see the [docs](https://github.com/docker-library/docs/tree/master/websphere-liberty#supported-tags-and-respective-dockerfile-links) are updated, but the actual Docker Hub [page](https://hub.docker.com/_/websphere-liberty/) for WebSphere Liberty still does not show the new 19.0.0.4 tags.

Is there a reason why the official page is not picking up the doc changes?

**Comment by tianon** [comment]
Doh great catch -- I'd updated some of our credentials, but thanks to DockerCon hadn't noticed the failures in https://doi-janky.infosiftr.net/job/docs/job/library/ yet; should be fixed now, can you confirm?

**Comment by arthurdm** [comment]
thanks @tianon!  yes, fixed now.
