### ISSUE TITLE
websphere-liberty ppc64le images not updated

### ISSUE THREAD

**Issue by naumanna** [docker-library/official-images#5989]
We merged an update to the websphere-liberty images two days ago under #5951.  The [amd64](https://hub.docker.com/r/amd64/websphere-liberty/tags) and [s390x](https://hub.docker.com/r/s390x/websphere-liberty/tags) images were updated quickly, but the [ppc64le](https://hub.docker.com/r/ppc64le/websphere-liberty/tags) images have not updated yet with our new tags.  They show not being updated for 15 days.

**Comment by tianon** [comment]
Doh, looks like something broke on our `ppc64le` build server -- digging in and looking for a fix now.  Thanks for the heads up!

**Comment by naumanna** [comment]
Thanks, I just noticed this also applies to our open-liberty ppc64le images too - https://hub.docker.com/r/ppc64le/open-liberty

**Comment by tianon** [comment]
Yeah, the whole server is having a rough time right now for some reason (still digging to try and figure out what's going on).

**Comment by tianon** [comment]
Looks like we had some varied filesystem corruption -- I've cleared out a few things, reinstalled a few packages, and things seem to be working again.  I've triggered both `ibmjava` and `adoptopenjdk` which when completed should trigger `websphere-liberty` and `open-liberty` but I'll be keeping an eye on it to make sure I didn't miss anything. :+1:

**Comment by tianon** [comment]
Looks good, they're both building now (with other deps of those two in the queue, more failing images will trigger within the next hour).  They should be pushed as soon as they finish building. :+1:

**Comment by naumanna** [comment]
@tianon looks great, thanks for the fast response and fix.
