### ISSUE TITLE
Description of Open Liberty not displaying properly

### ISSUE THREAD

**Issue by arthurdm** [docker-library/official-images#6030]
It seems that the description of the official [Open Liberty](https://hub.docker.com/_/open-liberty/) page is getting cut off too soon.  It's not matching the [full contents](https://github.com/docker-library/docs/blob/master/open-liberty/content.md).

**Comment by tianon** [comment]
Indeed, see the note at the top of the image description:

> **Note:** the description for this image is longer than the Hub length limit of 25000, so has been trimmed.  The full description can be found at [https://github.com/docker-library/docs/tree/master/open-liberty/README.md](https://github.com/docker-library/docs/tree/master/open-liberty/README.md).  See [docker/hub-beta-feedback#238](https://github.com/docker/hub-beta-feedback/issues/238) for more information.

Unfortunately, I believe that limit is still accurate and there's not really anything more we can do. :disappointed:

**Comment by arthurdm** [comment]
thanks @tianon - so I guess the `tags` section contributes to this limit?    The WebSphere Liberty has the same amount of descriptions, but less tags, and it displays fine: https://hub.docker.com/_/websphere-liberty/

**Comment by tianon** [comment]
Yes, every byte/character of the full generated description is part of that
limit (it's a limit on descriptions on the Hub in general, not something we
impose).

**Comment by arthurdm** [comment]
ok thanks.  I will close this then.  We'll see if we can trim the tags, or point to our description in GH.

**Comment by aguibert** [comment]
I think we should look at a better way to present tags for official images that have many label combinations like we do. I've added a comment over in https://github.com/docker/hub-feedback/issues/238#issuecomment-499340328 so we can discuss further

**Comment by tianon** [comment]
There are two primary reasons we currently include a full list of all tags:

1. discoverability, or helping users figure out what tags are available

2. supportability, or helping users figure out whether a given combination is actually going to receive further updates, especially for base image security rebuilds, for example

If we only describe the tagging scheme, we only resolve the first of these -- users are left to their own devices to figure out whether their chosen `version` + `profile` + `java_dist` combination is actually actively supported.

**Comment by aguibert** [comment]
can't we still solve (2) in the same way as with listing out every single tag that is currently supported? In other words, if only `version` 3, 4, and 5 are currently supported, don't show version 1 and 2 as options

**Comment by tianon** [comment]
@aguibert you'll still have the problem of holes in the supported matrix, right?  For example, if you document that versions 1, 2, and 3 are supported and variants foo, bar, and baz, but 3-baz and 2-bar don't exist, how do you convey that?  Maybe you could do a mock-up of the markdown you've got in mind to help illustrate?

**Comment by aguibert** [comment]
I'll think more on the table/matrix option and post back if I can come up with a decent mockup.

A simpler/safer idea I had was to not list out the dockerfile path next to the tag. This would save ~5k chars in the OpenLiberty REAMDE.

```
Instead of this:
-	[`kernel`, `kernel-java8-ibm` (*official/19.0.0.x/kernel/java8/ibmjava/Dockerfile*)](https://github.com/OpenLiberty/ci.docker/blob/ee4e20ea4d0795fc63970fabaa9c02803f86dfa1/official/19.0.0.x/kernel/java8/ibmjava/Dockerfile)
just this:
-	[`kernel`, `kernel-java8-ibm`](https://github.com/OpenLiberty/ci.docker/blob/ee4e20ea4d0795fc63970fabaa9c02803f86dfa1/official/19.0.0.x/kernel/java8/ibmjava/Dockerfile)
```

**Comment by aguibert** [comment]
@tianon Another option would be to allow images to separate labels into two groups: "common" and "other"

Then the generated README could look like:
1. "common" tags and links
2. image-specific content
3. "other" tags and links
That way when the page gets truncated, the "other" tags are the part the viewer doesn't see, rather than truncating off the image-specific content (which is usually helpful info related to using the image).

To control which images are common vs. other, images maintainers could opt in by having their `images.txt` file be like:
```
### Common
    
../official/latest/kernel/java8/ibmjava        kernel-java8-ibm           kernel
../official/latest/kernel/java8/ibmsfj         kernel-java8-ibmsfj
../official/latest/kernel/java8/openj9         kernel-java8-openj9
../official/latest/kernel/java11/openj9        kernel-java11
../official/latest/kernel/java12/openj9        kernel-java12
etc...
### Other
../official/latest/microProfile2/java8/openj9  microProfile2-java8-openj9
../official/latest/microProfile2/java11/openj9 microProfile2-java11
../official/latest/microProfile2/java12/openj9 microProfile2-java12
etc...
```

**Comment by tianon** [comment]
I'm definitely +1 on removing the `Dockerfile` path now.  For context, it was added initially because the previous rendering of Markdown on the Hub was such that [`code` in a link](...) would render without underline and barely noticeable blue color (and no hover behavior either besides the normal cursor change), so it wasn't clear it was even a link without additional non-code text.  Now that that has been corrected/adjusted, I think it's totally reasonable to remove those and will be opening a PR shortly.

**Comment by tianon** [comment]
I've filed an alternative approach to our trimming behavior at https://github.com/docker-library/docs/pull/1514 that I think is a bit more user-friendly while not sacrificing the benefits of the full tag listing. :+1:

**Comment by arthurdm** [comment]
thanks @tianon !
