### ISSUE TITLE
Backport information for vulnerabilities

### ISSUE THREAD

**Issue by smaliakkal** [docker-library/official-images#6189]
photon images are scanned and vulnerabilities are shown for every images.
But for most of the vulnerabilities, backported patches are applied. 

How do we provide this backport information to the scanner ?

**Comment by smaliakkal** [comment]
@yosifkit ,

Any documentation for this process ?

**Comment by tianon** [comment]
That's something we have no control over, nor are we involved in; I'd suggest contacting Docker's support and seeing what you can do to collaborate with them directly to get those marked as resolved properly.

**Comment by smaliakkal** [comment]
Thanks @tianon
