### ISSUE TITLE
Oracle JDKs in library/java official-images

### ISSUE THREAD

**Issue by fayndee** [docker-library/official-images#625]
Is there any plan/roadmap to add the Oracle JDKs in library/java official-images?

As the dockerfile/java repo is going to be deprecated, [pepole are looking for this](https://registry.hub.docker.com/u/library/java/#comments) in the Java official repo.

**Comment by yosifkit** [comment]
As far as I understand it, Oracle Java's licensing does not permit redistribution, so we cannot package it into an image right now.  See [license terms](http://www.oracle.com/technetwork/java/javase/terms/license/index.html) for more information, specifically section 'D. LICENSE TO DISTRIBUTE REDISTRIBUTABLES'.

**Comment by arnaud-deprez** [comment]
As far as I read the license.
In section C. LICENSE TO DISTRIBUTE SOFTWARE. 
"...
 Oracle grants you a non-exclusive, non-transferable, limited license without fees to reproduce and distribute the Software, provided that (i) you distribute the Software complete and unmodified and only bundled as part of, and for the sole purpose of running, your Programs, (ii) the Programs add significant and primary functionality to the Software, (iii) you do not distribute additional software intended to replace any component(s) of the Software, (iv) you do not remove or alter any proprietary legends or notices contained in the Software, (v) you only distribute the Software subject to a license agreement that: (a) is a complete, unmodified reproduction of this Agreement;
..."

If I get it right, it seems we can redistribute it as is without modifying it and that's what we'd like to do.
Is there any lawyer in the docker team ? :-)

**Comment by fayndee** [comment]
Agreed with @arnaud-deprez. Take notice of what has been done in [dockerfile/java](https://registry.hub.docker.com/u/dockerfile/java/), I'm not convinced there is any license problem here. 

Or is there anything you do in the office images which conflicts with the Oracle's redistribution license term?

**Comment by md5** [comment]
I don't think the existence of [`dockerfile/java`](https://github.com/dockerfile/java) has anything one way or the other about whether that image is legal to redistribute.

**Comment by yosifkit** [comment]
- Ubuntu stopped distributing it in the `sun-java6` package when Oracle retired the "Operating System Distributor License for Java" ([lists.ubuntu.com](https://lists.ubuntu.com/archives/ubuntu-security-announce/2011-December/001528.html)).
- The webupd8 ppa for Ubuntu and Debian requires the user to accept the Oracle license in order for their software to download and install Oracle java ([webupd8,org](http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html)).
- Gentoo has a _fetch-restriction_ that requires the user to go to the Oracle website to download the Java tar manually which inclues accepting the license ([wiki.gentoo.org](https://wiki.gentoo.org/wiki/Java)).
- CentOS requires users to go and download the rpm provided by Oracle at java.com and thus accept the Oracle license ([wiki.centos.org](https://wiki.centos.org/HowTos/JavaRuntimeEnvironment)).
- RedHat provides instructions to add a repo maintained by Oracle ([access.redhat.com](https://access.redhat.com/solutions/732883)).

As all of the major upstream Linux distributions are unable to redistribute Oracle java in their own distribution channels, I think it would be wise if we did the same.

**Comment by md5** [comment]
Fantastic summary @yosifkit!

**Comment by arnaud-deprez** [comment]
Indeed, very nice explanation @yosifkit.
I also give a try on [twitter](https://twitter.com/ArnaudDeprez/status/585490410094653441).
Anyway, I think it could be a good idea to add a link to your summary in the official java image doc.
What do you think ?

**Comment by fayndee** [comment]
Thx @yosifkit for the comprehensive summary. 

However, it doesn't mean that Oracle exclusively disallow the redistribution of their JDK. The only problem I could see now, and also probably the reason why all the major Linux distribution did in this way is: Oracle requires all end users of the redistribution accept their EULA. If docker could provide a way to ask user to accept a particular license term before pull an image, it would then solved the problem of redistribution of Oracle JDK, and probably other software alike, in the docker image. It is probably not in any roadmap yet, but definitely worth to consider in the future.

Again, I agree with @arnaud-deprez, it would be better to put the reason why it is not possible to include Oracle's JDK on the official Java image page. Because you are going to use this image to replace an "illegal" but quite popular java image, and people get confused about the missing parts.

Anyway, thx a lots for the clarification!

**Comment by arnaud-deprez** [comment]
@fayndee just to be clear, the open jdk is not an "illegal" stuff, but it's the official open source java development kit.

However, I think we have to find a way to support the official oracle jdk product but we have to be sure we respect the licenses. And while it's not totally clear that we have rights to distribute it, we shouldn't take any risk.
So if you know someone from oracle or whoever who can help on this topic, it's welcome.

**Comment by yosifkit** [comment]
I have a PR to the docs: https://github.com/docker-library/docs/pull/203.  Let me know if I can make any improvements over there.

**Comment by fayndee** [comment]
@arnaud-deprez, I was actually mentioning [dockerfile/java](https://registry.hub.docker.com/u/dockerfile/java/) image, not the OpenJDK :)

@yosifkit, thx for the effort.

**Comment by cpuguy83** [comment]
FYI, I've contacted Oracle about this, waiting for an official response from the Java team.

**Comment by arnaud-deprez** [comment]
@cpuguy83 Thx a lot ! My tweet didn't work lol :-)
Keep us in touch !

**Comment by tianon** [comment]
See also https://github.com/docker-library/docs/pull/203 for the description that's now included on the Hub.

**Comment by isotnikov** [comment]
@cpuguy83 any news from Oracle guys?
