### ISSUE TITLE
Call "curl -f" instead of "curl"

### ISSUE THREAD

**Issue by md5** [docker-library/official-images#628]
By default, `curl` will return a zero exit code for HTTP status codes >= 400. I think it would be appropriate for every `curl` command in the official images to start using `curl -f` to fail on HTTP status codes >= 400.

**Comment by tianon** [comment]
+1 -- I think "-fsSL" is a good set, personally (fail, silent, show errors,
follow redirects)

**Comment by tianon** [comment]
I think we can reasonably say that most if not all images now follow this convention. :smile: :+1:
