### ISSUE TITLE
UTC

### ISSUE THREAD

**Issue by mcandre** [docker-library/official-images#6345]
Calling out that Docker images are best configured with timezone UTC, to reduce the risk of ambiguity and data corruption as people deploy images across many different regions of the world.

**Comment by yosifkit** [comment]
We have a test that runs on every update to every Official Image to error when the image timezone is not UTC. Is there a specific image that you are trying to point out?

https://github.com/docker-library/official-images/tree/75b80e3ebf6b012b2c551768d5b321f8ff7989b0/test/tests/utc
