### ISSUE TITLE
Update Jenkins to latest

### ISSUE THREAD

**Issue by lamielle** [docker-library/official-images#635]
The long discussions in #564 and others concluded in removal of tracking every weekly released version of Jenkins in favor of just LTS releases and using 'latest' to mean just that, the latest weekly.

Could we please get the latest tag updated to 1.607 (or at least something more modern than 1.596)?  There is a very annoying console output scrolling bug that affects 1.596 and (short of switching to a different docker image) there is no workaround.

If there is documentation on how to create a PR for such a change (it appears to just be bumping a hash in the manifest file, where does that hash come from?) I'm more than willing to do so.  I'd just need some pointers.  Thanks!

**Comment by lamielle** [comment]
Additionally, the latest LTS is 1.596.2 which doesn't appear to be what 1.596 refers to.  It would be good to track LTS releases as security and critical fixes are applied.

**Comment by yosifkit** [comment]
The hash in the manifest is a commit from the git repo with the Dockerfile; which in this case would be from https://github.com/cloudbees/jenkins-ci.org-docker.  I would go make an issue there, to let them know that you would like an update.

**Comment by lamielle** [comment]
Thanks for the suggestion @yosifkit!  I've just submitted PR #655 to point 'latest' and 'weekly' at the 1.605 Jenkins build that already exists in cloudbees/jenkins-ci.org-docker.

**Comment by tianon** [comment]
This appears to be resolved now. :smile:  (the `jenkins` official image now _only_ contains LTS releases)
