### ISSUE TITLE
Implement cleanup for "librarytest/*" images after tests complete

### ISSUE THREAD

**Issue by md5** [docker-library/official-images#638]
Adding this issue here to track implementation of the `librarytest/*` image cleanup discussed in #620.

Are we just looking for a `trap _cleanup EXIT` in `run.sh` where `_cleanup` runs a `docker rmi` for all the images in that namespace?

**Comment by tianon** [comment]
I was pondering just a separate "clean.sh" that deletes artifacts like
these so that cleaning them becomes optional and we can keep them around
for the cache benefits if we so choose.  Thoughts?

**Comment by md5** [comment]
That sounds good. It's easy enough to call the separate script from a `trap` and get the best of both worlds of it becomes desirable to do so later.
