### ISSUE TITLE
Request: Add Kibana container

### ISSUE THREAD

**Issue by tracker1** [docker-library/official-images#656]
Given that there are containers for both ElasticSearch and LogStash, it would be nice to have an official container for Kibana.

* https://www.elastic.co/products/kibana

**Comment by md5** [comment]
FYI, you can run Kibana today using the `logstash` image with a command like this:

> docker run -d -p 9292:9292 logstash logstash web

**Comment by tracker1** [comment]
@md5 thanks, will give that a try...

**Comment by md5** [comment]
I agree that there should probably be a dedicated `kibana` image, but I figured I'd offer the suggestion as a short-term option.

**Comment by epelc** [comment]
+1 for a dedicated kibana image

**Comment by tianon** [comment]
Anyone interested in giving https://github.com/docker-library/kibana a pre-release test? :+1:
