### ISSUE TITLE
Question: Darwin base image possible?

### ISSUE THREAD

**Issue by schmunk42** [docker-library/official-images#666]
Is it possible to run [Darwin](http://en.wikipedia.org/wiki/Darwin_(operating_system)) with in a docker container, I suppose not, because it's a BSD?
But since I found almost nothing about it on Google, besides http://www.infoq.com/news/2014/03/docker_0_9
I thought I just ask...

An use case would be to run Xcode command line build tools in a container, although I don't know about any licensing issues at the moment - but Darwin itself would be OSS.

**Comment by tianon** [comment]
This would be really cool, but I don't know of anything besides "darwine"
which would make this even remotely possible (and even "darwine" would be
something you install and run in a Linux-based container, not something to
run Darwin-based containers directly).

**Comment by tianon** [comment]
Still don't know of any way to run Darwin binaries directly on a Linux kernel without something like Darwine (whose latest release according to SourceForge uploads was 2013-08-16).  I'm afraid that without development effort in Docker itself or from the Darwin community, this isn't something that's likely to happen for the official images, and am thus closing.  Feel free to open a new issue if there are any further developments (either in Docker or in the larger Darwin community) which make this more of a real possibility!

**Comment by mcandre** [comment]
Maybe qemu + darwin could hack this together?
