### ISSUE TITLE
Logo of the official Nuxeo image is not the one specified in the documentation

### ISSUE THREAD

**Issue by dmetzler** [docker-library/official-images#6747]
Our Nuxeo official image references the logo contained in the documentation as %LOGO%. (https://github.com/docker-library/docs/blob/master/nuxeo/logo.png).

However, an old logo is still present here https://hub.docker.com/_/nuxeo 
![image](https://user-images.githubusercontent.com/111077/66420621-0d220400-e9bb-11e9-808e-81a59eb36c76.png)

whereas it should be:

![image](https://user-images.githubusercontent.com/111077/66420665-232fc480-e9bb-11e9-8f72-60267afc74b0.png)

I didn't find anything to modify it either in the repo that I maintain or in the documentation.

**Comment by yosifkit** [comment]
Unfortunately the Logo at the top of the page doesn't have a way for us to update it.  It is manually controlled by Docker Inc.  We have been talking to the Hub team to try and get an API for us to be able to update the logo for Official Images (and hopefully users would also have the same API for their own repos published via the Docker Hub).  I've messaged them about this issue and hopefully they'll be able to update the logo (or we get an API soon).

Similar issues in the past: https://github.com/docker-library/official-images/issues/4043, https://github.com/docker-library/docs/issues/1060

**Comment by tianon** [comment]
This is now fixed! :+1: :tada:
