### ISSUE TITLE
Tiny Core Linux

### ISSUE THREAD

**Issue by jakirkham** [docker-library/official-images#6800]
Would be great to have an official image for Tiny Core Linux. This should yield a nice small image size while remaining functional and using GLIBC. This should help users trying to leverage BusyBox today, but finding some basic functionality missing. Also should address the needs of users, who try to add GLIBC into Alpine images (a musl based OS) to achieve small image size while satisfying their dependence on GLIBC.

ref: http://tinycorelinux.net

**Comment by tianon** [comment]
I'm not opposed to a TCL image, and would find it quite interesting. Last I checked the `tce-load` package manager required some patching to work reasonably inside a container (https://github.com/boot2docker/boot2docker/blob/c2b60ab21080d15148948fc6536078251dcfa842/files/tce-load.patch).

That being said, this isn't something we're going to actively work on directly. I'd suggest reaching out to the TCL community to make sure they don't have any objections to such a thing and to try and help determine their level of desire to be involved in such a thing (which we're typically happy to help with if upstream is involved and interested).
