### ISSUE TITLE
Inactive OK button on New Item page.

### ISSUE THREAD

**Issue by medined** [docker-library/official-images#682]
I am unable to create projects. I created my host directory:

mkdir /data/jenkins
chmod 777 /data/jenkins

I am using the following docker command:

docker run \
  --name jenkins \
  -p 28080:8080 \
  -p 50000:50000 \
  --rm=true \
  -v /data/jenkins:/var/jenkins_home \
  jenkins

I can connect to Jenkins on port 28080. And I can click the New Item link. But after entering a project name and selecting 'maven project', then OK button remains inactive and unresponsive.

I see no console error messages.

Have you seen this behaviour before?

**Comment by md5** [comment]
Did you try it without the `-v`? I would have expected you to see an error on the console if it's a permissions error with your data mount, but perhaps not.

I haven't seen this behavior with the `jenkins` image, but the right place to report issues with that image is here: https://github.com/cloudbees/jenkins-ci.org-docker/issues

The folks over there may be better equipped to help you.

**Comment by medined** [comment]
Thanks. I'll ask over there.
