### ISSUE TITLE
Library images are unsigned. DCT dead?

### ISSUE THREAD

**Issue by abeluck** [docker-library/official-images#6838]
This is an intentional duplicate of #5874 which has been *closed* and *ignored* for months.

**Where are the signatures for the official library images?**

If docker has for *some* reason decided to stop signing the official images, please make a public announcement. Otherwise you're leaving us hanging like a teenaged love interest, but with a hella lot more on the line.

**Comment by tianon** [comment]
Please keep the hyperbole to a minimum here.  There has not been a compromise here, and you're frankly barking up the wrong tree in this repository, which is why the previous issue is closed.

As stated in that previous thread, the maintainers of this repository have no control over nor involvement in the signing process of the images we publish (however much we'd love to change that if someone at Docker Inc reading this would like to collaborate on making changes there!).  Yelling about it here does not get the attention of the folks who control that signing process.

What I do know is that the service which Docker runs for signing our images has had some stability issues, but as stated above, nobody on this repository is directly involved there so we really cannot give you any more information than that, however much I wish I could.

**Comment by abeluck** [comment]
Thanks for the reply @tianon. I added the hyperbole merely to get attention. I'll remove the mention of compromise from the title.

I hadn't heard anything back from the docker team in the intervening months, and since that issue (and this repo) were the only public nexus of communication about this issue, I figured here was better than shouting into the void. The closed issue at some point did in fact elicit a reply from the docker team.

Really, I'm merely looking for some communication, even if that is _"It's still broken, but we plan to fix it"_ or _"We may or may not fix it, but either way you probably shouldn't rely on it"_.

**Comment by DevRCRun** [comment]
From the POV of a new docker user this does seem very odd indeed. If I pull node:alpine with content trust enabled I get a 13 month old image with vulnerabilities. If I pull with it enabled I get the eight day old image I was expecting. 

As prospective docker customers I guess we're best talking to them directly about the fact this hasn't exactly inspired confidence!

**Comment by raratiru** [comment]
I am quite amazed landing here... 
Through the [contact form](https://www.docker.com/company/contact) I sent the following question:

> 
> When enabling Docker Content Trust, I receive outdated versions of images, for example Python-3.9.0 instead of Python-3.9.5.
> 
> This seems to be an old issue:
> https://github.com/docker-library/official-images/issues/6838
> 
> Could you please update the docs in a clear way to inform that although DCT provides verified images, quite often they are outdated... a.k.a. insecure?

**Comment by KEINOS** [comment]
At least I want my **base image pulled as DCT** but what I get is the way too old version.
I'm wondering what the "official image" means if the "official" can't sign ...

GitHub Packages Container registry? Maybe?

**Comment by verdverm** [comment]
maybe we can use https://github.com/sigstore/cosign

This would enable multiple signatures to be created and community trust built up for various signatories.

It would add extra steps. Could the pull verification be done with a docker cli plugin?

**Comment by verdverm** [comment]
cc @dlorenc

**Comment by dlorenc** [comment]
I'd be happy to help here if there's interest!

@tianon - is there any possibility of getting signing this stuff with cosign? I'm not sure what it would take.

**Comment by mattmoor** [comment]
+1 happy to help start signing some of this stuff with cosign

**Comment by verdverm** [comment]
would be great to get cosign on the build/push side as well, through a plugin

**Comment by dlorenc** [comment]
I don't actually really know how the docker plugin model works. Do you have any links?

**Comment by sirlatrom** [comment]
> would be great to get cosign on the build/push side as well, through a plugin
> 
> @dlorenc would that make cosign work transparently for the majority of registries and images?
> 
> simple install with `docker plugin install sigstore/cosign-docker-plugin` ?

The `docker plugin` sub command mainly manages daemon side plugins, and only for a small set of interfaces, e.g. volume plugins or authorization plugins. You might want to look into CLI plugins. Consider https://github.com/lukaszlach/clip as an example plugin manager.

**Comment by tianon** [comment]
As far as I'm aware, this issue should be fixed (for a while now, but just getting back around to it :bow:). :+1:

```console
$ docker pull --disable-content-trust=false alpine:3.16
Pull (1 of 1): alpine:3.16@sha256:686d8c9dfa6f3ccfc8230bc3178d23f84eeaf7e457f36f271ab1acc53015037c
docker.io/library/alpine@sha256:686d8c9dfa6f3ccfc8230bc3178d23f84eeaf7e457f36f271ab1acc53015037c: Pulling from library/alpine
2408cc74d12b: Pull complete 
Digest: sha256:686d8c9dfa6f3ccfc8230bc3178d23f84eeaf7e457f36f271ab1acc53015037c
Status: Downloaded newer image for alpine@sha256:686d8c9dfa6f3ccfc8230bc3178d23f84eeaf7e457f36f271ab1acc53015037c
Tagging alpine@sha256:686d8c9dfa6f3ccfc8230bc3178d23f84eeaf7e457f36f271ab1acc53015037c as alpine:3.16
docker.io/library/alpine:3.16

$ docker pull --disable-content-trust=true alpine:3.16
3.16: Pulling from library/alpine
Digest: sha256:686d8c9dfa6f3ccfc8230bc3178d23f84eeaf7e457f36f271ab1acc53015037c
Status: Image is up to date for alpine:3.16
docker.io/library/alpine:3.16
```

**Comment by KEINOS** [comment]
I have confirmed that it has been fixed and even confirmed the `alpine:latest` image. Thank you!

```shellsession
$ docker system prune -af
***snip***

$ docker pull --disable-content-trust=false alpine:latest
Pull (1 of 1): alpine:latest@sha256:686d8c9dfa6f3ccfc8230bc3178d23f84eeaf7e457f36f271ab1acc53015037c
docker.io/library/alpine@sha256:686d8c9dfa6f3ccfc8230bc3178d23f84eeaf7e457f36f271ab1acc53015037c: Pulling from library/alpine
2408cc74d12b: Pull complete 
Digest: sha256:686d8c9dfa6f3ccfc8230bc3178d23f84eeaf7e457f36f271ab1acc53015037c
Status: Downloaded newer image for alpine@sha256:686d8c9dfa6f3ccfc8230bc3178d23f84eeaf7e457f36f271ab1acc53015037c
Tagging alpine@sha256:686d8c9dfa6f3ccfc8230bc3178d23f84eeaf7e457f36f271ab1acc53015037c as alpine:latest
docker.io/library/alpine:latest

$ echo $?
0
```
```shellsession
$ docker system prune -af
***snip***

$ docker pull --disable-content-trust=true alpine:latest
latest: Pulling from library/alpine
2408cc74d12b: Pull complete 
Digest: sha256:686d8c9dfa6f3ccfc8230bc3178d23f84eeaf7e457f36f271ab1acc53015037c
Status: Downloaded newer image for alpine:latest
docker.io/library/alpine:latest

$ echo $?
0
```

<details><summary>Env Info</summary>

```shellsession
$ docker --version
Docker version 20.10.13, build a224086

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1922
```

</details>
