### ISSUE TITLE
Provide latest jre as official docker images

### ISSUE THREAD

**Issue by danieleforberghi** [docker-library/official-images#7046]
Hi,

When do you plan to push the official jre docker images for java 12, 13 and 14? Now it is only JDK.
The latest JRE official images are 11.05 listed in the official images. Thanks in advance. Daniel

**Comment by wglambert** [comment]
https://github.com/docker-library/openjdk/issues/319
>Our builds for OpenJDK 12 come from https://jdk.java.net/12/, and as you can see they're JDK only.

Openjdk 8 and 11 come from https://adoptopenjdk.net/upstream.html which does publish a JRE variant
https://github.com/docker-library/openjdk/issues/272
