### ISSUE TITLE
Does the latest ubuntu18.04 docker image fix the 12/3/2019 kernel vulnerability

### ISSUE THREAD

**Issue by ruowan** [docker-library/official-images#7196]
Here is a kernel vulnerability https://lists.ubuntu.com/archives/ubuntu-security-announce/2019-December/005227.html  which was discovered in December 2019. So has the lastest ubuntu docker image fixed it?

**Comment by wglambert** [comment]
There's no kernel in Docker images
https://www.docker.com/resources/what-container
>Containers share the machine’s OS system kernel
>
>Multiple containers can run on the same machine and share the OS kernel with other containers, each running as isolated processes in user space.

But for future reference the last update was December 17 https://github.com/docker-library/official-images/commits/master/library/ubuntu

And the Ubuntu issue tracker is hosted at https://bugs.launchpad.net/cloud-images

https://hub.docker.com/_/ubuntu/
>Where to file issues:
>* [the cloud-images bug tracker](https://bugs.launchpad.net/cloud-images) (include the docker tag)
