### ISSUE TITLE
Rebuild Kong 1.4.2

### ISSUE THREAD

**Issue by hutchic** [docker-library/official-images#7252]
Related to: https://github.com/Kong/kong/issues/5388

The Kong 1.4.2 Ubuntu arm64 was actually an x86_64 package by accident. This has been resolved and the new released asset is on bintray but we need the `1.4.2` rebuilt please.

I feel like an issue is the best way to achieve this as there's nothing to be updated code-wise in this repository apologies if this isn't correct

**Comment by yosifkit** [comment]
The build server uses Docker build cache, so unfortunately triggering the build job won't change anything. :disappointed:

So the natural way to cause a rebuild is to bump the version with something like a revision number: `ENV KONG_VERSION 1.4.2-r1` or embedding checksums in the line that downloads the artifacts (like [golang](https://github.com/docker-library/golang/blob/c57b5d1851d334d3bc8a966ae5d0769d767ea288/1.13/buster/Dockerfile#L14-L31)).
