### ISSUE TITLE
STOPSIGNAL prevents automatic restart

### ISSUE THREAD

**Issue by osklil** [docker-library/official-images#7322]
Current 1.8.23 haproxy images use "STOPSIGNAL SIGUSR1". A busy HAProxy can take more than 10 seconds to gracefully restart. This means that when restarting the Docker daemon, such HAProxy containers are killed and exit with status 137 (https://success.docker.com/article/what-causes-a-container-to-exit-with-code-137). And this in turn means that they won't be automatically restarted if they are set to ''restart: unless-stopped''.

Unfortunately, I don't know the best solution to this.

**Comment by wglambert** [comment]
I'm not understanding the issue, you've selected the restart policy `unless-stopped` that states "it is not restarted even after Docker daemon restarts."

`docker stop` itself won't trigger the [restart policy](https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy) but a daemon restart will if you don't select `unless-stopped` or `no` (which is default)
https://github.com/moby/moby/issues/38755
>it is restarted only when Docker daemon restarts or the container itself is manually restarted.

The behavior of [docker stop](https://docs.docker.com/engine/reference/commandline/stop/) sends the `STOPSIGNAL` (default `sigterm`) then after a grace period (default 10s) a `sigkill`, so your container didn't stop within the grace period and exited with an error.

You could try enabling the [live-restore](https://docs.docker.com/config/containers/live-restore/) option on the daemon or use another restart-policy

**Comment by tianon** [comment]
You can adjust the default "stop timeout" for a given container via the `--stop-timeout` flag (although we unfortunately cannot put a different default into the image itself, that's a runtime-only setting).  You'll also want to take care that your `TimeoutStopSec` on your Docker daemon in systemd is set high enough to account for your highest container stop timeout.

**Comment by osklil** [comment]
@wglambert I think I  must have misunderstood unless-stopped and always. But the problem I have, is that when I restart the Docker daemon on a host with 100+ containers (all with restart unless-stopped), many HAProxy containers never start - they are marked as "Exited (137)" which means that Docker killed them - because they didn't shut down properly I assume. Other restart unless-stopped containers were started properly.

Anyway, I think you can close this! Thanks for responding and sorry for taking your time!
