### ISSUE TITLE
8u242 for hotspot?

### ISSUE THREAD

**Issue by blyhos** [docker-library/official-images#7426]
It looks like openj9 was updated for 8u242, but I don't see similar updates for the hotspot v8 images.

For example:

8-jre-hotspot (still 8u232 - previous v8, unchanged)
```
Tags: 8u232-b09-jre-hotspot-bionic, 8-jre-hotspot-bionic
SharedTags: 8u232-b09-jre-hotspot, 8-jre-hotspot
Architectures: amd64, arm32v7, arm64v8, ppc64le, s390x
GitCommit: 3b20018f331a9201b86405fbacdebe034bf522bf
Directory: 8/jre/ubuntu
File: Dockerfile.hotspot.releases.full
```

8-jre-openj9 (8u242 - latest v8)
```
Tags: 8u242-b08-jre-openj9-0.18.1-bionic, 8-jre-openj9-bionic
SharedTags: 8u242-b08-jre-openj9-0.18.1, 8-jre-openj9
Architectures: amd64, ppc64le, s390x
GitCommit: 6ef982afbdd32a0b2195c9ee0fa36328535a3c64
Directory: 8/jre/ubuntu
File: Dockerfile.openj9.releases.full
```

**Comment by wglambert** [comment]
The Hotspot images are maintained by [AdoptOpenJDK](https://github.com/AdoptOpenJDK/openjdk-docker)
https://hub.docker.com/_/adoptopenjdk

The OpenJ9 PR https://github.com/docker-library/official-images/pull/7349#issuecomment-578742473
>Hotspot update to jdk8u242-b08 will be in a separate PR as we have a few pending arches for which builds are not available as yet.

Looks like this is the tracking issue for it https://github.com/AdoptOpenJDK/openjdk-docker/issues/274

**Comment by blyhos** [comment]
@wglambert Thank you; I had seen that issue at one point but lost track of it. It seems to me that issue is in a better location. I'll close this issue out and post my question to that issue.
