### ISSUE TITLE
update ubuntu:latest to ubuntu:15.04 (ubuntu:vivid)

### ISSUE THREAD

**Issue by mcandre** [docker-library/official-images#743]
Could we update the tag `ubuntu:latest` to point to Ubuntu 15.04 Vivid Vervet?

**Comment by tianon** [comment]
The "latest" tag for the Ubuntu repo tracks the latest LTS, not the latest
release.

Docker's convention of using "latest" when a tag is unspecified is a
misnomer that wasn't corrected early enough for a simple transition --
"default" would've been a more appropriate name for what this tag actually
means.

**Comment by mcandre** [comment]
Well put.
