### ISSUE TITLE
Cron jobs fail if debian:8.0 based image is started with --net="host"

### ISSUE THREAD

**Issue by jannek-octo3** [docker-library/official-images#744]
I need to use --net="host" parameter for mapping thousands of sylkserver ports. Cron works fine on debian:7.8 image but all cron jobs fail on debian:8.0 image when started with --net="host" parameter.

Using Docker 1.6.2 on Ubuntu 14.04.2 64 bit host that is VirtualBox client in Windows 7 64 bit host.
Reproducible also on AWS EC2 Ubuntu 14.04.2 64 bit host.
```
Dockerfile for reproducing problem:
FROM debian:8.0
RUN apt-get update
RUN export DEBIAN_FRONTEND=noninteractive && apt-get install rsyslog -y
RUN sed -i -e '/exit 101/s/^/#/g' /usr/sbin/policy-rc.d
RUN echo "* * * * * root echo \"Cron works fine\" |logger" >> /etc/crontab

Build and start container:
sudo docker build -t janne:8.0 --rm=true --no-cache=true .
sudo docker run -d -v /var/log/test:/var/log janne:8.0 /bin/bash -c "service rsyslog start; service cron start; while true; do date; sleep 10; done"

Check syslog, "Cron works fine" line is added once in a minute:
tail -f /var/log/test/syslog

Stop container and start with --net="host" parameter:
sudo docker run -d --net="host" -v /var/log/test:/var/log janne:8.0 /bin/bash -c "service rsyslog start; service cron start; while true; do date; sleep 10; done"

Check syslog, "System error" line from CRON is added once in a minute:
tail -f /var/log/test/syslog
```

**Comment by jannek-octo3** [comment]
Problem found on old debian:8.0 image id 41b730702607.
Just tested, reproducible also on latest debian:8.0 image id df2a0347c9d0.

**Comment by yosifkit** [comment]
As far as I can tell, this is not an issue with the image or with docker (https://github.com/docker/docker/issues/5899#issuecomment-131136166)
