### ISSUE TITLE
here, have some base images for older OS's

### ISSUE THREAD

**Issue by mcandre** [docker-library/official-images#747]
I used debootstrap to generate base images for several older debian and ubuntu versions:

https://registry.hub.docker.com/u/mcandre/docker-debian/tags/manage/

https://registry.hub.docker.com/u/mcandre/docker-ubuntu/tags/manage/

Could we tag these into the semi-official "debian" and "ubuntu" DockerHub repos?

**Comment by yosifkit** [comment]
As the [library](https://github.com/docker-library/official-images/tree/master/library) files show, all of the images for debian and ubuntu are maintained by @tianon in [tianon/docker-brew-debian](https://github.com/tianon/docker-brew-debian), [tianon/dockerfiles](https://github.com/tianon/dockerfiles), and [tianon/docker-brew-ubuntu-core](https://github.com/tianon/docker-brew-ubuntu-core).

**Comment by tianon** [comment]
and @paultag :wink:

**Comment by mcandre** [comment]
Thanks for the tip.

https://github.com/tianon/docker-brew-debian/issues/24

https://github.com/tianon/docker-brew-ubuntu-core/issues/31
