### ISSUE TITLE
submitting the nightly build of Fedora rawhide image

### ISSUE THREAD

**Issue by cverna** [docker-library/official-images#7529]
Hi all,

Fedora produces a nightly build of Fedora rawhide, if we wanted to update the official image on the DockerHub that would mean creating a new PR every day which might be a lot of work on the persons processing these requests.

Is there is a more automated process available ? or what would be an acceptable cadence to push newer images ?

Thanks

**Comment by wglambert** [comment]
https://github.com/docker-library/julia/issues/25#issuecomment-434867037

Similar issues: https://github.com/docker-library/official-images/issues/1281, https://github.com/rust-lang-nursery/docker-rust/issues/5, https://github.com/docker-library/docker/issues/125, https://github.com/docker-library/php/issues/825

> Any `nightly` or `dev` image in the official images would still need to maintain the repeatability aspect.  All builds make heavy use of docker build cache so if the `RUN` line does not change, the image would not change.  Base images get updates and cause dependent images to rebuild and we don't want those situations to cause a version bump to the main software of the image.  The only other time an image gets built is via a commit in official-images that changes the respective `library/` file.  `eggdrop` is one image that has a `develop` build that they update once in a while (like https://github.com/docker-library/official-images/pull/3051).

Nightly builds aren't something we can currently do effectively

**Comment by tianon** [comment]
We do have several images what submit a weekly development snapshot, which I think is a reasonable cadence for something like this (exceptions for security updates, etc).

**Comment by cverna** [comment]
> We do have several images that submit a weekly development snapshot, which I think is a reasonable cadence for something like this (exceptions for security updates, etc).

Yeah weekly sounds reasonable to me too, does it matter if we update 1 image (rawhide) or all the active releases (up to 4 images including rawhide) weekly ? 
Since we will put the automation on to make a weekly release it would be nice to update all the images at once.

**Comment by yosifkit** [comment]
> does it matter if we update 1 image (rawhide) or all the active releases (up to 4 images including rawhide) weekly ?

I don't think that will cause any issue on our side. Do the packages in the Fedora images update that often?  To prevent excessive churn of downstream images (on our images as well as users doing `FROM`), we only rebuild the Debian and Ubuntu images about once a month (more often for major security fixes).

**Comment by cverna** [comment]
> > does it matter if we update 1 image (rawhide) or all the active releases (up to 4 images including rawhide) weekly ?
> 
> I don't think that will cause any issue on our side. Do the packages in the Fedora images update that often? To prevent excessive churn of downstream images (on our images as well as users doing `FROM`), we only rebuild the Debian and Ubuntu images about once a month (more often for major security fixes).

I would not think so at least not for the GA release (Beta releases and rawhide are different cases). But now our build system just builds new images every night, we have plans to change this and rebuild only when a package was update (or a certain number of packages). 

Thanks for the answers :+1: , I ll close that issue.
