### ISSUE TITLE
postgres image: POSTGRES_USER is set, --no-password is enabled - BUG

### ISSUE THREAD

**Issue by stepanic** [docker-library/official-images#756]
I think this is BUG.

Only when POSTGRES_PASSWORD is set then postgres user is not able to login --no-password

But when is set POSTGRES_USER and POSTGRES_PASSWORD then custom name user is able to login without password

Tested with terminal: pg_restore and with pgAdmin3

**Comment by yosifkit** [comment]
I am not able to replicate this.  Here are my steps:

```console
$ docker run -it --rm --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -e POSTGRES_USER=joe postgres
# second term
$ docker run -it --link some-postgres:postgres --rm postgres sh -c 'exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U joe --no-password'
psql: fe_sendauth: no password supplied
```

**Comment by stepanic** [comment]
Try to connect as joe user through pgAdmin with empty password it will be able to access database

**Comment by yosifkit** [comment]
Using the same `docker run` I used above, empty password still failed from fresh `pgadmin3`:
```
An error has occurred:

21:10:41: Error: Error connecting to the server: fe_sendauth: no password supplied
```

Adding in the password and it was able to login as "joe".

What is the image id and postgres version of your image?

**Comment by stepanic** [comment]
image is is postgres and I am using the latest version

this is the docker run command

`docker run --name=my-postgres -p 5432:5432 -e POSTGRES_USER=joe -e POSTGRES_PASSWORD=mysecret -d postgres`

when I try to login at pgAdmin as user joe and without password (empty string) I get access to whole database

but when I start container with
`docker run --name=my-postgres -p 5432:5432 -e POSTGRES_PASSWORD=mysecret -d postgres`
everything works as expected with default postgres user

**Comment by yosifkit** [comment]
Are you using the "store password" feature of pgadmin?  If I close pgadmin, remove `.pgpass` from my home directory, and restart pgadmin, it fails to connect and asks for a password as it should.

Here are the images that I am using (9.4.2 will be up on the hub shortly):
```console
$ # local build of 9.4.2, so the id will be different
$ docker images postgres
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
postgres            9.4.1               b733b00eb1ae        3 weeks ago         213.9 MB
postgres            latest              b733b00eb1ae        3 weeks ago         213.9 MB
...
postgres            9.4.2               391c178c65b5        3 days ago          213.9 MB

```

**Comment by stepanic** [comment]
thank you, I will check it, probably this could be issue
