### ISSUE TITLE
update alpine to 3.2

### ISSUE THREAD

**Issue by mcandre** [docker-library/official-images#761]
Could we update alpine:latest and alpine:3.2 per http://alpinelinux.org/posts/Alpine-3.2.0-released.html ?

**Comment by yosifkit** [comment]
I see that @andyshinn has the update in the [docker-alpine repo](https://github.com/gliderlabs/docker-alpine).  Just waiting for the PR here once there are new rootfs branches I think :wink:.

**Comment by andyshinn** [comment]
Reference pull request is https://github.com/gliderlabs/docker-alpine/pull/33. Just fixing up the build script to account for a bug. I'll have an incoming pull request with the updated rootfs git references this evening or tomorrow.

**Comment by yosifkit** [comment]
Awesome, thanks for the info.
