### ISSUE TITLE
OpenJDK:12-jdk and above are shipped without GIT by default

### ISSUE THREAD

**Issue by O5ten** [docker-library/official-images#7671]
As you mention on several of the docker-librarys base-images: 

> To minimize image size, it's uncommon for additional related tools (such as **git** or **bash**) to be included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile (see the alpine image description for examples of how to install packages if you are unfamiliar).

So usually when referring to a non-slim or non-alpine image such as openjdk:11-jdk it is expected to have some basic commands such as specifically git installed. This is no longer the case with openjdk:12-jdk and more recent versions. Likely because of the recent change to **-oracle** & **-oraclelinux7**. 

Let's remember that many of these images are used in CI/CD systems where cloning a repo to build it in maven or with a jdk is usually running in the same image, which is nice because it allows us to avoid pulling an image with specifically git installed. So, seeing as 14-jdk is now the default JDK in many images such as maven as of a few days back, now that our nexus caches are starting to invalidate we are suddenly in a bad situation. Many of our base images used for building stuff are lacking GIT and hence has started to fail. 

**How to reproduce**
```bash
[user@localhost ~]$ docker run -it maven:3.6 bash
Unable to find image 'maven:3.6' locally
3.6: Pulling from library/maven
Digest: sha256:940198ad6fd665b652bb2a6b8e693d69f02f3a83cf243d69f038025530d4b16e
Status: Downloaded newer image for maven:3.6
bash-4.2# git
bash: git: command not found
```

**What i expected to happen**
The same behavior as with an older image, like maven:3.5
```bash
[user@localhost ~]$ docker run -it maven:3.5  bash
Unable to find image 'maven:3.5' locally
3.5: Pulling from library/maven
Digest: sha256:d5c6b61f886178a925283918ac8984f963d279c9a3fdae813d6fc462fef1899c
Status: Downloaded newer image for maven:3.5
root@f4a12b9cfe2f:/# git
usage: git [--version] [--help] [-C <path>] [-c name=value] ... 
```

**Comment by wglambert** [comment]
What you could do is make a derivative Dockerfile `FROM maven:3.6` and add git and other things in.

https://github.com/docker-library/openjdk/issues/311#issuecomment-489685509
>The latest `openjdk` images are built from Oracle as opposed to the previous buildpack-deps

https://github.com/docker-library/openjdk/issues/353#issuecomment-526366255
>Regarding a "fat" version, we'd rather not maintain such an image (duplicate of https://github.com/docker-library/openjdk/issues/311).

**Comment by yosifkit** [comment]
It sounds like your CI failed exactly when it should; to alert you when images get updated with changes you weren't expecting (default jdk 11 to 14: https://github.com/docker-library/official-images/pull/7645).

Depending on how tolerant you want to be to updates, you may want to use a more specific tag like `maven:3.6-jdk-11` (or if you want to control each update, use the sha256 [digest](https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier)).

As far as the `maven` image always including `git` and other source control tools, that should be an issue filed with that image (https://github.com/carlossg/docker-maven/issues/149).
