### ISSUE TITLE
Update Sentry image to latest

### ISSUE THREAD

**Issue by BYK** [docker-library/official-images#7831]
Hi @tianon and @yosifkit,

I've filed an issue over at our repository for Sentry regarding bringing the latest to Docker Hub: https://github.com/getsentry/docker-sentry/issues/211

Can you provide your perspective over there whether the proposed way forward is a good path or not?

**Comment by yosifkit** [comment]
Closing in favor of https://github.com/getsentry/docker-sentry/issues/211
