### ISSUE TITLE
how to add image with a single file(rootfs tar) larger than 100MB?

### ISSUE THREAD

**Issue by openeulerHW** [docker-library/official-images#7982]
I'm not sure if it is suitable to ask the question through filing a issue here, the guideline doesn't seem to metion the point. 
As the pull request https://github.com/docker-library/official-images/pull/7980 shows, our image have a rootfs package larger than 100M. Since github does not allow push such a big file directly, we use git-lfs to push it and thus causing the file cannot be pulled completely using git (it need to be pulled also using git-lfs). It seem to be the reason why this pull request failed the automatic check.
So is it means any official image should not including a package larger than 100M?

**Comment by tianon** [comment]
Added a reply in https://github.com/docker-library/official-images/pull/7980 so we can keep the conversation where the context for it is. :+1:
