### ISSUE TITLE
Kibana 4.1 has not been pushed to hub

### ISSUE THREAD

**Issue by kristofferpeterhansel** [docker-library/official-images#804]
Docker Hub claims the library version of Kibana is 4.1 in the readme file. But there are only 4.0.x versions actually available.

Seems like the definition in this repo was updated 15 hours ago. So maybe it happens after a longer delay? Not really sure what the process for these images are.

**Comment by tianon** [comment]
Should be up now -- sorry for the delay!

**Comment by kristofferpeterhansel** [comment]
Indeed it is. Thanks
