### ISSUE TITLE
What is the difference between a image like `arm32v7/redis` and the image `redis` (that has the `linux/arm/v7` OS/arch)

### ISSUE THREAD

**Issue by rafaeleyng** [docker-library/official-images#8160]
Hello there, I'm trying to make sense of the multi arch thing (and failing miserably). If somebody could help me with the questions below it would help a lot.

Looking at this repo, is see at the README:

![image](https://user-images.githubusercontent.com/4842605/84207377-a132f680-aa87-11ea-9500-ca5cf3db755f.png)

and navigating to the `arm32v7` (only as an example), and looking at the [`arm32v7/redis`](https://hub.docker.com/r/arm32v7/redis/tags) image (again, just as an example), I see the "OS/ARCH":

![image](https://user-images.githubusercontent.com/4842605/84207479-d8a1a300-aa87-11ea-89d5-0630f4ee7ff0.png)

But if I go to the [`redis`](https://hub.docker.com/_/redis/?tab=tags) image, I can see:

![image](https://user-images.githubusercontent.com/4842605/84207601-1dc5d500-aa88-11ea-91b0-3c432d530caa.png)

So, my doubts here are:
1. what is the difference between those images?
2. if I'm on an arm32v7, which one should I use?
3. if I run `docker pull redis`, which one of the "OS/ARCH" will be pulled? Is this dependent on the architecture of my current machine and the Docker client handles this transparently? Or do I need to specify it somehow (and if so, how?)? If it handles automatically, is there a way I can force to pull the image for a specific architecture (different than the current machine)?

Thanks

**Comment by wglambert** [comment]
The digest is the same they're the same exact image. The `arm32v7/redis` is just under the Dockerhub user `arm32v7` for convenience, as people can just browse everything that supports that architecture and is also a guaranteed way to pull that architecture using a "simple tag". Whereas `redis:latest` is a "shared tag" and Docker will auto-detect which architecture to pull.

https://github.com/docker-library/faq#whats-the-difference-between-shared-and-simple-tags

**Comment by tianon** [comment]
See also https://github.com/docker-library/docs/pull/1720, which we added recently to try and help clarify this exact point (it manifests as the "**Note:** ..." bit at the top of the image description at https://hub.docker.com/r/arm32v7/redis).

**Comment by rafaeleyng** [comment]
Thanks, it helped a lot!
