### ISSUE TITLE
Performance issue involving bash with centos6 image

### ISSUE THREAD

**Issue by robertoaloi** [docker-library/official-images#841]
The following command is an order of magnitude more expensive when run via bash (not sh) for no good reason.

````
$ sudo docker run -it centos:centos6 sh -c "time grep -ir test /usr > /tmp/foo"
[...]
real    0m0.556s
user    0m0.406s
sys     0m0.152s

$ sudo docker run -it centos:centos6 sh
sh-4.1# time grep -ir test /usr > /tmp/foo
[...]
real    0m0.559s
user    0m0.434s
sys     0m0.124s
sh-4.1# exit
exit

$ sudo docker run -it centos:centos6 bash
[root@f2beb5daca25 /]# time grep -ir test /usr > /tmp/foo
[...]
real    0m5.503s
user    0m5.411s
sys     0m0.088s
````

The difference is not visible on the centos7 image, which is much faster in all cases.

````
$ sudo docker run -it centos:centos7 sh -c "time grep -ir test /usr > /tmp/foo"                                                               
real    0m0.165s
user    0m0.079s
sys     0m0.086s

$ sudo docker run -it centos:centos7 bash                                                                                                     
[root@597f947e3e39 /]# time grep -ir test /usr > /tmp/foo
real    0m0.172s
user    0m0.084s
sys     0m0.088s

$ sudo docker run -it centos:centos7 sh
sh-4.2# time grep -ir test /usr > /tmp/foo

real    0m0.167s
user    0m0.091s
sys     0m0.075s
````

**Comment by robertoaloi** [comment]
When using bash, the LANG env variable is set to UTF8, which causes grep to be much slower (-i option). export LANG=C brings back performance to normal levels.

**Comment by tianon** [comment]
This isn't really a great place to report this; see https://github.com/docker-library/docs/blob/02c36e647eecb584662c659ed396c98d2f428a80/centos/README.md#issues (from the `centos` image description):

> If you have any problems with or questions about this image, please contact us by submitting a ticket at [https://bugs.centos.org](https://bugs.centos.org) or through a [GitHub issue](https://github.com/CentOS/sig-cloud-instance-images/issues).
