### ISSUE TITLE
Error pulling Oracle Linux from the Hub

### ISSUE THREAD

**Issue by Djelibeybi** [docker-library/official-images#844]
Some users are getting the following error trying to pull oraclelinux (or oraclelinux;7):

    # docker pull oraclelinux
    Pulling repository oraclelinux
    8a2b759d9dd8: Error pulling image (latest) from oraclelinux, HTTP code 400 
    8c3e49cb06dc: Download complete 
    90fed8b1ceab: Error pulling dependent layers 
    FATA[0078] Error pulling image (latest) from oraclelinux, HTTP code 400

However, I can't reproduce the issue on my system. I thought I'd log it here, just in case it's a known issue upstream. The error is being reported by users using CoreOS as the Docker host.

**Comment by tianon** [comment]
This is something you should hit up support@docker.com with -- there's nothing we can do about it (although I imagine it was probably a transitory issue and is likely fixed now).
