### ISSUE TITLE
eclipse-mosquito crashing since a few days

### ISSUE THREAD

**Issue by dersimn** [docker-library/official-images#8564]
This is about images pulled from here: https://hub.docker.com/_/eclipse-mosquitto

I don't know exactly when it started, but since a few days the official images of `eclipse-mosquitto` won't start anymore with the previous settings.

Containers created using read-only config files like `-v mosquitto.conf:/mosquitto/config/mosquitto.conf:ro` are constantly crashing, because of some chmod command not working from inside of the container:

```
# docker logs --tail 10 mqtt
chown: /mosquitto/config/mosquitto.conf: Read-only file system
chown: /mosquitto/config/mosquitto.conf: Read-only file system
chown: /mosquitto/config/mosquitto.conf: Read-only file system
chown: /mosquitto/config/mosquitto.conf: Read-only file system
chown: /mosquitto/config/mosquitto.conf: Read-only file system
chown: /mosquitto/config/mosquitto.conf: Read-only file system
chown: /mosquitto/config/mosquitto.conf: Read-only file system
chown: /mosquitto/config/mosquitto.conf: Read-only file system
chown: /mosquitto/config/mosquitto.conf: Read-only file system
chown: /mosquitto/config/mosquitto.conf: Read-only file system
```

**Comment by wglambert** [comment]
Seems that was addressed a few days ago https://github.com/docker-library/official-images/pull/8548
These were all of the changes to their entrypoint for reference https://githistory.xyz/eclipse/mosquitto/blob/master/docker/1.6/docker-entrypoint.sh

But we (the docker-library) don't directly maintain that image so you'd want to find discussions over at https://github.com/eclipse/mosquitto/issues
https://hub.docker.com/_/eclipse-mosquitto
>Maintained by: [the Eclipse Foundation](https://github.com/eclipse/mosquitto)
>Where to file issues: https://github.com/eclipse/mosquitto/issues

**Comment by dersimn** [comment]
You're right.
