### ISSUE TITLE
Official images build order 

### ISSUE THREAD

**Issue by kavisuresh** [docker-library/official-images#868]
We plan to build couple of official images , in that one image built would be the base image for the other images . Does DockerHub build automatically considers the build order?

**Comment by yosifkit** [comment]
The DockerHub does not build the official images, but the scripts here in the bashbrew folder do build them and ensure that each tag of an image is built after its parent.  Would this be tags within one image that inherit from other tags, like `ros` has (`indigo-ros-core` <- `indigo-ros-base` <- `indigo-robot`)?  Or would this be something like an IBM java image that can be used for WebSphere and other IBM projects?

**Comment by kavisuresh** [comment]
Yes, they are going to be tags within one image that inherit from other tags

**Comment by tianon** [comment]
:+1:
