### ISSUE TITLE
Insecure apache installation

### ISSUE THREAD

**Issue by floki-php** [docker-library/official-images#8792]
After running security analysis on the image built by ```docker run -it --rm --entrypoint /bin/bash /php:7.4-apache -c "apache2 -v" ``` we have concluded that he Apache Version 2.4.38 has security flaws, and the command should built an image with Apache Version 2.4.4+ where these concerns have been addressed.

Any advise or workaround to this issue? Is this the right place to report this issue?

Kindest regards

**Comment by wglambert** [comment]
2.4.38 is the latest for Debian Buster
https://packages.debian.org/buster/apache2
https://security-tracker.debian.org/tracker/source-package/apache2

See https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves
And https://github.com/docker-library/postgres/issues/286#issuecomment-302512767 docker-library/openjdk#161, docker-library/openjdk#112, docker-library/postgres#286, docker-library/drupal#84, docker-library/official-images#2740, docker-library/ruby#117, docker-library/ruby#94, docker-library/python#152, docker-library/php#242, docker-library/buildpack-deps#46, docker-library/openjdk#185.

A CVE doesn't imply having an actual vulnerability, and often is even a false positive (given how most distributions handle versioning/security updates in stable releases). If there are actionable items we can resolve, we're happy to do so (and do so actively). We update all Debian based images to include any updates in apt packages at least monthly (we regenerate the base images and then rebuild all dependent images).
