### ISSUE TITLE
make all the official images support the riscv64 architecture. (if upstream supports riscv64 )

### ISSUE THREAD

**Issue by woa7** [docker-library/official-images#8794]
can we make all the official images support the riscv64 architecture.
if upstream supports riscv64: like busybox, debian, etc

**Comment by tianon** [comment]
We'd be happy to help collaborate on this, if someone were willing to donate some decent hardware (similar to https://github.com/docker-library/official-images/issues/6709).  So far everything I've seen hardware-wise for riscv64 has been dev boards that don't really seem suitable as a proper build/development host.

**Comment by tianon** [comment]
To be explicitly clear, by "decent hardware", I don't just mean a good amount of RAM and a decent CPU speed/core count, but also things like having an actual case that isn't someone's 3D printed hobby and a hard drive that isn't a microSD card, which are things I see the community "borrowing" from ARM that make me extremely frustrated as a fan of these systems and even the smaller form factors of the currently available boards.

**Comment by FireMasterK** [comment]
I'd love to see support for Risc-V too! Perhaps someone over at SiFive could help out with that

**Comment by tianon** [comment]
https://www.sifive.com/boards/hifive-unmatched is looking pretty interesting :eyes:

(M.2, 8GB of RAM, Gigabit ethernet, Mini-ITX form factor...)

**Comment by FireMasterK** [comment]
There's also now a 16GB ram model available now 👀

**Comment by tianon** [comment]
Shots fired!  https://github.com/docker-library/official-images/pull/10502 👀🎉

Thanks to the Debian project, I've got an Unmatched now (https://twitter.com/tianon/status/1413003965889847297). :+1:
