### ISSUE TITLE
Docker hub image for PostgreSQL version 12.4 contains cryptominer

### ISSUE THREAD

**Issue by Antender** [docker-library/official-images#8803]
After ~3 days of uptime postgres process spawns 8 processes with autogenerated names like "0DJbp5eh" which eat up all CPU cores and RAM. Also this processes open connection to Hetzner (136.243.90.99) with some sort of "empty" http server which listens on 80 and 8080 ports.

**Comment by SteeleDesmond** [comment]
Was this issue resolved?

**Comment by tianon** [comment]
See https://github.com/docker-library/postgres/issues/770 for where this was appropriately re-filed, although https://github.com/docker-library/postgres/issues/664 is a similar conversation that's discussed more in good faith.

The TL;DR is that if you're seeing this, you most likely exposed your database server port publicly (very likely by accident) and it was hacked. :grimacing:

**Comment by Antender** [comment]
@SteeleDesmond I, personally, switched to bitnami image and this solved the issue.
