### ISSUE TITLE
Can docker official images be used for commercial purpose ?

### ISSUE THREAD

**Issue by user-mk** [docker-library/official-images#8865]
When i say commercial purpose i mean can docker **official images** be used to create other images and/or run containers of those official images?

**Comment by wglambert** [comment]
Broadly speaking yes you can create derivative images from any existing Dockerfiles and you are encouraged to do so
https://docs.docker.com/docker-hub/official_images/
>The Docker Official Images are a curated set of Docker repositories hosted on Docker Hub. They are designed to:
> - Provide essential base OS repositories (for example, ubuntu, centos) that serve as the starting point for the majority of users.

As for the commercialization of said image you'd want to consult their respective license and terms of use. Licenses for the official images can be found at the bottom of their documentation, for example [Drupal](https://hub.docker.com/_/drupal) which uses GPL 2:
>View [license information](https://www.drupal.org/licensing/faq) for the software contained in this image.
>As with all Docker images, these likely also contain other software which may be under other licenses (such as Bash, etc from the base distribution, along with any direct or indirect dependencies of the primary software being contained).

>As for any pre-built image usage, it is the image user's responsibility to ensure that any use of this image complies with any relevant licenses for all software contained within.
