### ISSUE TITLE
Official registry image rather old

### ISSUE THREAD

**Issue by berlincount** [docker-library/official-images#899]
the last image released with https://github.com/docker-library/official-images/blob/master/library/registry is collecting plenty of dust, while a lot of bugfixes and features went into the codebase.

Please cut a new release.

**Comment by dmp42** [comment]
Ya, it's planned. 2.1 is coming soon. (ref: https://github.com/docker/distribution/issues/703 )

**Comment by yosifkit** [comment]
Done! It was updated just a few days ago: 19a6e439f77a81c99b681cae8831e023d769adcf.
