### ISSUE TITLE
Also publish on GitHub Container Registry (GHCR)

### ISSUE THREAD

**Issue by TrueBrain** [docker-library/official-images#8998]
Have you considered or would you consider also publishing the `official-images` on [GitHub Container Registry (GHCR)](https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/about-github-container-registry) (in addition to Docker Hub)? (see [here](https://github.blog/2020-09-01-introducing-github-container-registry/) for the announcement a while ago).

It would mean these images would also be available at https://github.com/orgs/docker-library/packages and can be pulled via `ghcr.io/docker-library/<package-name>`.

The main reason for this, of course triggered by the Docker Hub policy change about pull limits, is that currently on every GitHub Actions that uses a `FROM` based on these official images, it fetches the image from Docker Hub. As GitHub Actions currently cannot cache Docker Images, this is even for my small amount of projects a lot of traffic and pulls during a day (heavily depending on the amount of Pull Requests that happen, of course). Using GHCR as `FROM` would mean the traffic stays within GitHub infrastructure. To me, that would feel a lot less wasteful; and I would assume it helps both Docker Hub in reducing their traffic, and GitHub Actions in having lower-latency pulls.

Now initially I was considering setting up a repo under my own account that simply pulls from the Docker Hub all official images every night and publish it on GHCR under my own account .. but then I realised it might be more useful to first ask you guys if you have considered this or are willing to consider this.

If this question already has been asked and answered, I do apologize. I could only find a [somewhat related topic](https://github.com/docker-library/official-images/issues/8552) about this, but that is only about retention policy, not about the pull limit.

**Comment by trademark18** [comment]
I'm running into the same issue only on AWS CodeBuild instead of Github Actions.  

For what it's worth, AWS is [about to release their own public container registry](https://aws.amazon.com/blogs/containers/advice-for-customers-dealing-with-docker-hub-rate-limits-and-a-coming-soon-announcement/).  Perhaps the image could be continuously deployed across the various major platforms to allow flexibility to users.

> AWS will deliver a new public container registry that will allow developers to share and deploy container images publicly. This new registry will allow developers to store, manage, share, and deploy container images for anyone to discover and download. Developers will be able to use AWS to host both their private and public container images, eliminating the need to use different public websites and registries. Public images will be geo-replicated for reliable availability around the world and offer fast downloads to quickly serve up images on-demand. Anyone (with or without an AWS account) will be able to browse and pull containerized software for use in their own applications. Developers will be able use the new registry to distribute public container images and related files like helm charts and policy configurations for use by any developer. A new website will allow anyone to browse and search for public container images, view developer provided details, and see pull commands — all without needing to sign in to AWS.

**Comment by tianon** [comment]
We have no current plans to push any official images to GHCR (or any other registry).
