### ISSUE TITLE
Rebuild Varnish Docker 6.4.0 image tag with latest Debian base image

### ISSUE THREAD

**Issue by pacifier17** [docker-library/official-images#9095]
I see that Varnish Docker 6.4.0 image tag was last built 2 months ago: https://hub.docker.com/_/varnish?tab=tags&name=6.4.0

This image is based on debian:buster-slim image which I see was updated a month ago: https://hub.docker.com/_/debian?tab=tags&page=1&name=buster-slim

Since the Varnish image was not rebuilt using the latest debian:buster-slim image it now has some vulnerability in it which are supposed to be fixed by the latest version

**Would you be able to help rebuild this Varnish image tag to fix this vulnerability?**

I am unable to use the latest 6.5.0 version as it has some breaking metrics changes that are messing around with our monitoring code.

**Comment by tianon** [comment]
If you look at https://hub.docker.com/_/varnish, you'll see that only 6.0.7 and 6.5.1 are actively supported, so unfortunately they will be the only tags that actually get rebuilt.

**Comment by pacifier17** [comment]
Ohh ok, so there is no way we can do an adhoc build for this tag as a one-time operation?

We just need to use this version for some more time so that we can do the appropriate changes to our monitoring solution and then we can upgrade to the latest 6.5.1 version.

**Comment by tianon** [comment]
We will not be doing an ad-hoc build for this, but you certainly can -- you'll just need to walk back in time on https://github.com/varnish/docker-varnish/blob/f26947e3a1d7ab5e3e76114d58e54f0ddee13534/fresh/debian/Dockerfile until you find the version you're looking for (or recreate it).

I think https://github.com/varnish/docker-varnish/blob/2459369407fbf77df75d6948ee48de8c814fb3e4/fresh/debian/Dockerfile is likely what you're after, which you should be able to attempt a rebuild of via something like:

`docker build https://github.com/varnish/docker-varnish.git#2459369407fbf77df75d6948ee48de8c814fb3e4:fresh/debian`

**Comment by tianon** [comment]
(you'll want to also include `--pull` and `--tag` as appropriate for your environment so you can make sure it's up-to-date and so that you can push it somewhere, but if you plan to keep this long-term you'll want to copy the whole relevant build context into a repository you control so you can maintain it over time)
