### ISSUE TITLE
IBM Java Docker images to use ubuntu:20.04

### ISSUE THREAD

**Issue by jayasg12** [docker-library/official-images#9431]
This issue is raised to inform everyone that , IBM Java8 official docker images are currently built on ubuntu:18.04 as base and it will be upgraded to ubuntu:20.04 (Latest available LTS version) . Docker images will be upgraded in the month of Feb. 
Request all the stakeholders to take necessary action to migrate to ubuntu:20.04 before Feb.

Note : ubuntu:18.04 docker image with latest java will not be generated post upgrade.  If there is any concern please raise it before the upgrade.

**Comment by jayasg12** [comment]
@arthurdm FYI

**Comment by jayasg12** [comment]
As there is no ubuntu:20.04 base image for i386 arch.  Base image upgrade is put on hold for Feb release.  
It will be handled in next release or before that based on internal discussions . I will keep this issue updated with the same. Thanks !!

**Comment by jayasg12** [comment]
Hi @arthurdm Request Websphere decision/inputs on upgrading ubuntu version from 18.04 to 20.04 for supported architectures.

**Comment by arthurdm** [comment]
Hi @jayasg12 - we don't foresee any issues as the AdoptOpenJDK images we're using are already on Ubuntu 20.04.

**Comment by arthurdm** [comment]
hi @jayasg12 - can you please confirm that the updated IBM Java images based on Ubuntu 20.04 will still support the i386 platform?   WebSphere Liberty is currently using that platform (from IBM Java), https://github.com/docker-library/official-images/blob/master/library/websphere-liberty

**Comment by jayasg12** [comment]
Hi @arthurdm , 
   yes , we will still support i386 IBM Java docker images for ubuntu , since we don't have ubuntu 20.04 for i386 , it will be based on 18.04 for i386 alone.

**Comment by tianon** [comment]
That doesn't sound like a great experience for your users 😕

What I would suggest instead (if both are actually useful) is adding explicit labels for the underlying OS version and letting users choose, similar to Python, Go, etc.

**Comment by jayasg12** [comment]
Hi @tianon , 
    Since ubuntu stopped release post 18.04 for i386 we will continue to deliver i386 on ubuntu 18.04 until its EOL i,e 2023. 
As per current policy , IBM will support only the latest ubuntu LTS version i,e. 20.04 for IBM Java docker images .

**Comment by tianon** [comment]
To me, that sounds like a really strong argument for one or the other of:

- dropping support for `i386`

- adjusting the support policy to include 18.04 _and_ latest LTS
