### ISSUE TITLE
Include timezone tables and content in default container.

### ISSUE THREAD

**Issue by jpirkey** [docker-library/official-images#944]
The MySQL timezone tables should be included as part of the default container.

I tried to do this manually, but the `mysql_tzinfo_to_sql` command fails since it is not handling the zonefile correctly:
```
root@d790b4abf1b1:/# mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
ERROR 1406 (22001) at line 39124: Data too long for column 'Abbreviation' at row 1
```

```
root@d790b4abf1b1:/# cat /etc/timezone 
Etc/UTC
```

Reference: https://bugs.mysql.com/bug.php?id=68861, https://bugs.mysql.com/bug.php?id=20545

**Workaround for now**:
```
mysql_tzinfo_to_sql /usr/share/zoneinfo | sed -e "s/Local time zone must be set--see zic manual page/local/" | mysql -u root mysql
```

**Comment by tianon** [comment]
I think this is more appropriate over at https://github.com/docker-library/mysql, but I think this was actually fixed by https://github.com/docker-library/mysql/pull/80.

**Comment by jpirkey** [comment]
Thanks.  I had pulled a fresh download 3 days ago (or at least I thought) and it was not in it still.  And yes, thanks for moving it to the correct place.  Closing this.
