### ISSUE TITLE
Adding the Red Hat Universal Base Image as an official image

### ISSUE THREAD

**Issue by bstinsonmhk** [docker-library/official-images#9445]
First I'd like to make some introductions, @fatherlinux and @brianwcook are the points of contact for the [Red Hat Universal Base Image](https://developers.redhat.com/products/rhel/ubi). 

It would be great to use this issue to discuss any questions they might have, and to reference against the PR when ready to add this entry to the library. 

We should review the [README](https://github.com/docker-library/official-images#contributing-to-the-standard-library) and the [Review Criteria](https://github.com/docker-library/official-images/blob/master/NEW-IMAGE-CHECKLIST.md) as we generate our Pull request. 

Scott, Brian: What questions do we have here? We chatted a little bit about signing the other day I remember.

**Comment by grooverdan** [comment]
I'd like to see to see UBI in the notable exceptions https://github.com/docker-library/official-images#repeatability so that official images can be based on UBI

**Comment by tianon** [comment]
We're definitely open to UBI becoming part of the program, and would love to have more conversation around that, but it will not be added as an exception.

We frankly don't love the Windows base image exceptions (and have considered even consuming them into top-level images), but they're necessary for running containers at all on Windows due to the way Windows containers work (which is also why that list is very specific about which of the `mcr.microsoft.com` images are considered acceptable, and the implementation details of our checks for that are even more particular about which specific tags are considered acceptable).

**Comment by grooverdan** [comment]
Related, just saw the Red Hat announcement - https://developers.redhat.com/articles/2021/05/25/red-hat-universal-base-image-and-docker-hub-why-should-developers-care

**Comment by LenzGr** [comment]
As we were just trying to submit updated images by ourselves (we migrated from CentOS 8 to UBI), I was wondering if there's any update or outlook on this topic? What's missing and how could we help in getting this resolved?

**Comment by fatherlinux** [comment]
@justincormack and I discussed this a few weeks back, and I think Docker is working on a long term solution. It's a much more difficult problem than I had originally thought. Originally, I asked if we could just push the UBI image into an Official repository, but Justin pointed out that this creates other problems.

Just might have more information, or he might be able to point us in the direction of the right person to work with.

**Comment by curiositycasualty** [comment]
Sorry to add a notification to everyone's inbox.

Are there anymore updates on this? Anything I can help with to get this over the finish line?
Correct me if I'm wrong, but it seems like we're waiting on feedback from @justincormack?

**Comment by gdams** [comment]
Not that it's likely to sway the outcome of this discussion but Eclipse Temurin has discussed swapping the Centos base image with UBI. There's obviously no way to proceed right now because the UBI image isn't "allowed". Might be worth restarting this conversation.

**Comment by fatherlinux** [comment]
@gdams actually, thank you for bringing this up! For the UBI team, this *is* indeed a big deal. We're definitely still working on this, and this is a good kick in the butt to get it going again. I'll reach out to @justincormack offline and try to get this moving. I "think" we are past the technical blockers we had when this was first requested.

**Comment by yosifkit** [comment]
https://github.com/docker-library/official-images/pull/13533 :tada: 

We have an initial test of adding ubi images as a base for a limited set of official images. Although we are not ready to add other images, we hope to be able to have others also add `ubi` as we improve the tooling to support it.

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/issues/13608 -> https://github.com/docker-library/official-images/pull/13613 :sob:

Will revisit with a slightly less convenient naming scheme.

**Comment by tianon** [comment]
Reporting back that #13614 seems to be working OK and we should be good to go now. :smile:

**Comment by tianon** [comment]
See also https://github.com/docker-library/official-images/pull/13908 (which has more words/detail about UBI specifically).
