### ISSUE TITLE
Alpine 3.13

### ISSUE THREAD

**Issue by Razican** [docker-library/official-images#9457]
A new Alpine version (3.13) [has been released](https://alpinelinux.org/posts/Alpine-3.13.0-released.html). It would be nice to provide packages for it.

**Comment by yosifkit** [comment]
From your title changes, I assume you are talking about an Alpine 3.13 based image for Rust. You need to ask their maintainers over in their repo: https://github.com/rust-lang/docker-rust/issues (or directly maybe give them a PR).
