### ISSUE TITLE
hello-world latest image don't have amd64, s390x version anymore

### ISSUE THREAD

**Issue by glours** [docker-library/official-images#9562]
<img width="1252" alt="Screen Shot 2021-02-03 at 19 52 58" src="https://user-images.githubusercontent.com/705411/106794659-71a9ad80-6659-11eb-91d6-6d491fbe27aa.png">

**Comment by tianon** [comment]
https://github.com/docker-library/postgres/issues/813#issuecomment-772745645

> Ugh, this is probably related to / caused by the recent outage: https://status.docker.com/pages/history/533c6539221ae15e3f000031

All `hello-world` tags should be fixed now.

**Comment by glours** [comment]
Thanks @tianon 

```sh
docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
0e03bdcc26d7: Pull complete
Digest: sha256:31b9c7d48790f0d8c50ab433d9c3b7e17666d6993084c002c2ff1ca09b96391d
Status: Downloaded newer image for hello-world:latest
docker.io/library/hello-world:latest```

**Comment by tianon** [comment]
Just in case anything else is affected, I've scheduled a recalculation across all images (since we know at least `hello-world` and `postgres` were affected), so that should roll out over the next few minutes/hours (depending on how long each takes -- it's ~150 jobs :cold_sweat:).
